### ISSUE TITLE
Export fails - out of memory exception

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1012]
```
2015-05-19 11:41:22 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
extension: 1bp
start: 0
token: 91x47du6cbub6e0bFfl2
query: <query model="genomic" view="Chromosome.locatedFeatures.feature.id" sortOrder="Chromosome.locatedFeatures.feature.primaryIdentifier ASC" constraintLogic="A and B and C and D" name="ChromLocation_Gene" ><constraint path="Chromosome.locatedFeatures.feature.chromosomeLocation" type="Location" /><constraint path="Chromosome.locatedFeatures.feature" type="Gene" /><constraint path="Chromosome.organism" type="Organism" /><constraint path="Chromosome.primaryIdentifier" op="=" value="2L" code="A" /><constraint path="Chromosome.organism.name" op="=" value="Drosophila melanogaster" code="B" /><constraint path="Chromosome.locatedFeatures.feature.chromosomeLocation.start" op="&gt;" value="1" code="C" /><constraint path="Chromosome.locatedFeatures.feature.chromosomeLocation.end" op="&lt;" value="50000" code="D" /></query>
filename: ChromLocation_Gene
format: fasta
java.lang.OutOfMemoryError: Java heap space

  at java.util.Arrays.copyOf(Arrays.java:2367)
  at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
  at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
  at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
  at java.lang.StringBuilder.append(StringBuilder.java:132)
  at org.intermine.objectstore.query.ClobAccess.toString(ClobAccess.java:205)
  at org.intermine.bio.web.export.SequenceExporter.createSequenceFeatureWithExtension(SequenceExporter.java:262)
  at org.intermine.bio.web.export.SequenceExporter.export(SequenceExporter.java:166)
  at org.intermine.bio.web.export.SequenceExporter.export(SequenceExporter.java:130)
  at org.intermine.bio.webservice.BioQueryService.execute(BioQueryService.java:195)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.core.WebServiceServlet.respond(WebServiceServlet.java:73)
  at org.intermine.webservice.server.core.WebServiceServlet.doGet(WebServiceServlet.java:114)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
 ...
```

**Comment by julie-sullivan** [comment]
This was related to my specific webapp.
