### ISSUE TITLE
OBO converter - fails on creating synonyms. 

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1013]
Here is the error

```
Caused by: java.sql.SQLException: Error writing to database, running statement COPY OntologyTermSynonym (class, type, id, name) FROM STDIN BINARY, data size = 7664723
at org.intermine.sql.writebatch.FlushJobPostgresCopyImpl.flush(FlushJobPostgresCopyImpl.java:56)
at org.intermine.sql.writebatch.Batch$BatchFlusher.run(Batch.java:461)
at java.lang.Thread.run(Thread.java:695)
Caused by: org.postgresql.util.PSQLException: ERROR: index row size 2784 exceeds maximum 2712 for index "ontologytermsynonym__key"
  Hint: Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
  Where: COPY ontologytermsynonym, line 18743
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:966)
at org.postgresql.core.v3.QueryExecutorImpl.writeToCopy(QueryExecutorImpl.java:856)
at org.postgresql.core.v3.CopyInImpl.writeToCopy(CopyInImpl.java:51)
at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:179)
at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:161)
at org.intermine.sql.writebatch.FlushJobPostgresCopyImpl.flush(FlushJobPostgresCopyImpl.java:51)


```

**Comment by julie-sullivan** [comment]
@kkarra - It looks like it's failing on creating a synonym key. The key includes: 

* class
* type
* id
* name

How can any of these be over 2000 bytes? What kind of ontology names are these!? ha. The longest GO term name is 200 something. My suggestions:

1. Check the data. This seems wrong. This is for the synonym not for the actual term.
2. Take the name out of the key. Queries will still work but they will just be slower.

**Comment by julie-sullivan** [comment]
@kkarra Can I close this ticket?

**Comment by kkarra** [comment]
I tried option #2 (take name out of key) and that seems to have worked.
