### ISSUE TITLE
HumanMine - fix SNP displayer

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1025]
There is a displayer that doesn't display on the report page.

Also, this error message could be made to be useful.

```
24/05/15,20:50:29 ERROR org.intermine.web.struts.InterMineExceptionHandler     - java.lang.NullPointerException
        at org.intermine.web.struts.ReportDisplayerController.execute(ReportDisplayerController.java:43)
        at org.intermine.web.struts.ModifyDetails.ajaxShowDisplayer(ModifyDetails.java:296)
        at sun.reflect.GeneratedMethodAccessor1983.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:269)
        at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:170)
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425
```

**Comment by julie-sullivan** [comment]
We don't do overlapping features anymore:

```
    private PathQuery snpToGene(String snpPrimaryIdentifier) {
        PathQuery query = new PathQuery(im.getModel());
        query.addViews(
                "SNP.primaryIdentifier", // will be skipped, required for query to run

                "SNP.overlappingFeatures.gene.id",
                "SNP.overlappingFeatures.gene.primaryIdentifier",

                "SNP.overlappingFeatures.gene.name",
                "SNP.overlappingFeatures.gene.symbol",
                "SNP.locations.start",
                "SNP.overlappingFeatures.gene.locations.start",
                "SNP.overlappingFeatures.gene.locations.end",
                "SNP.overlappingFeatures.direction"
        );

        query.addOrderBy("SNP.primaryIdentifier", OrderDirection.ASC);

        query.addConstraint(Constraints.eq("SNP.primaryIdentifier", snpPrimaryIdentifier));
        query.addConstraint(Constraints.type("SNP.overlappingFeatures", "GeneFlankingRegion"));
        query.addConstraint(Constraints.eq("SNP.overlappingFeatures.distance", "10.0kb"));

        return query;
    }
```

**Comment by julie-sullivan** [comment]
@rachellyne This displayer (SNP to gene) doesn't work anymore because we don't do overlaps. 

1. What should we replace it with?
2. Should we restore overlaps? We got rid of them for performance reasons.

**Comment by julie-sullivan** [comment]
@rachellyne Should we replace this with SNVs?

**Comment by rachellyne** [comment]
I expect so.  I don't remember what the displayer did.
