### ISSUE TITLE
Report page - error message is cryptic

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1026]
Which collection? Why did it fail? 

```
25/05/15,14:44:44 ERROR org.intermine.web.struts.InterMineExceptionHandler     - java.lang.NullPointerException
        at org.intermine.web.struts.CollectionDetailsAction.execute(CollectionDetailsAction.java:74)
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
        at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
        at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
```

**Comment by julie-sullivan** [comment]
not enough info, past me.
