### ISSUE TITLE
FlyMine: chromosomes are golden path fragments

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1052]
```
2015-06-25 15:34:33 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
query: <query model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.goAnnotation.ontologyTerm.identifier Gene.goAnnotation.ontologyTerm.name Gene.overlappingFeatures.secondaryIdentifier Gene.overlappingFeatures.available Gene.overlappingFeatures.dataSets.id" sortOrder="Gene.secondaryIdentifier ASC" constraintLogic="A and B and C" name="GOterm_genesDrosDelDeletion" ><constraint path="Gene.goAnnotation.ontologyTerm" type="GOTerm" /><constraint path="Gene.overlappingFeatures" type="ChromosomalDeletion" /><constraint path="Gene.overlappingFeatures.dataSets.name" op="=" value="DrosDel P-element and Deletion collection" code="C" /><constraint path="Gene.organism.name" op="=" value="Drosophila melanogaster" code="A" /><constraint path="Gene.goAnnotation.ontologyTerm.name" op="=" value="gap junction" code="B" /></query>
summaryPath: Gene.overlappingFeatures.dataSets.id
format: jsonrows
java.lang.RuntimeException: ObjectStore error has occurred in size()

  at org.intermine.objectstore.query.ResultsBatches.size(ResultsBatches.java:236)
  at org.intermine.objectstore.query.Results.size(Results.java:269)
  at org.intermine.api.query.QueryExecutor.uniqueColumnValues(QueryExecutor.java:233)
  at org.intermine.webservice.server.query.result.QueryResultService.setHeaderAttributes(QueryResultService.java:165)
  at org.intermine.webservice.server.query.result.QueryResultService.execute(QueryResultService.java:105)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.query.result.QueryResultServlet.runService(QueryResultServlet.java:61)
  at org.intermine.webservice.server.query.result.QueryResultServlet.doPost(QueryResultServlet.java:43)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
 ...
 caused by: org.intermine.objectstore.ObjectStoreQueryDurationException: Estimated time to run query(27986458014) greater than permitted maximum (10000000000): IQL query: SELECT DISTINCT a1_.a7_ AS a2_, COUNT(*) AS a3_ FROM (SELECT DISTINCT a1_, a6_, a3_, a4_, a4_.id AS a7_ FROM org.intermine.model.bio.Gene AS a1_, org.intermine.model.bio.GOAnnotation AS a2_, org.intermine.model.bio.ChromosomalDeletion AS a3_, org.intermine.model.bio.DataSet AS a4_, org.intermine.model.bio.Organism AS a5_, org.intermine.model.bio.GOTerm AS a6_ WHERE (a1_.goAnnotation CONTAINS a2_ AND a1_.overlappingFeatures CONTAINS a3_ AND a3_.dataSets CONTAINS a4_ AND a1_.organism CONTAINS a5_ AND a2_.ontologyTerm CONTAINS a6_ AND LOWER(a5_.name) LIKE 'drosophila melanogaster' AND LOWER(a6_.name) LIKE 'gap junction' AND LOWER(a4_.name) LIKE 'drosdel p-element and deletion collection')) AS a1_ GROUP BY a1_.a7_ ORDER BY COUNT(*) DESC, SQL query: SELECT DISTINCT a1_.a7_ AS a2_, COUNT(*) AS a3_ FROM (SELECT DISTINCT a1_.briefDescription AS a1_briefDescription, a1_.chromosomeId AS a1_chromosomeId, a1_.chromosomeLocationId AS a1_chromosomeLocationId, a1_.cytoLocation AS a1_cytoLocation, a1_.description AS a1_description, a1_.downstreamIntergenicRegionId AS a1_downstreamIntergenicRegionId, a1_.id AS a1_id, a1_.length AS a1_length, a1_.name AS a1_name, a1_.organismId AS a1_organismId, a1_.primaryIdentifier AS a1_primaryIdentifier, a1_.score AS a1_score, a1_.scoreType AS a1_scoreType, a1_.secondaryIdentifier AS a1_secondaryIdentifier, a1_.sequenceId AS a1_sequenceId, a1_.sequenceOntologyTermId AS a1_sequenceOntologyTermId, a1_.symbol AS a1_symbol, a1_.upstreamIntergenicRegionId AS a1_upstreamIntergenicRegionId, a6_.description AS a6_description, a6_.id AS a6_id, a6_.identifier AS a6_identifier, a6_.name AS a6_name, a6_.namespace AS a6_namespace, a6_.obsolete AS a6_obsolete, a6_.ontologyId AS a6_ontologyId, a3_.available AS a3_available, a3_.chromosomeId AS a3_chromosomeId, a3_.chromosomeLocationId AS a3_chromosomeLocationId, a3_.confirmedByGenetics AS a3_confirmedByGenetics, a3_.confirmedByPCR AS a3_confirmedByPCR, a3_.cytoLocation AS a3_cytoLocation, a3_.element1Id AS a3_element1Id, a3_.element2Id AS a3_element2Id, a3_.id AS a3_id, a3_.length AS a3_length, a3_.name AS a3_name, a3_.organismId AS a3_organismId, a3_.primaryIdentifier AS a3_primaryIdentifier, a3_.score AS a3_score, a3_.scoreType AS a3_scoreType, a3_.secondaryIdentifier AS a3_secondaryIdentifier, a3_.sequenceId AS a3_sequenceId, a3_.sequenceOntologyTermId AS a3_sequenceOntologyTermId, a3_.symbol AS a3_symbol, a4_.dataSourceId AS a4_dataSourceId, a4_.description AS a4_description, a4_.id AS a4_id, a4_.name AS a4_name, a4_.publicationId AS a4_publicationId, a4_.url AS a4_url, a4_.version AS a4_version, a4_.id AS a7_ FROM Gene AS a1_, GOAnnotation AS a2_, ChromosomalDeletion AS a3_, DataSet AS a4_, Organism AS a5_, GOTerm AS a6_, GeneGoAnnotation AS indirect0, OverlappingFeaturesSequenceFeature AS indirect1, BioEntitiesDataSets AS indirect2 WHERE a1_.id = indirect0.Gene AND indirect0.GoAnnotation = a2_.id AND a1_.id = indirect1.SequenceFeature AND indirect1.OverlappingFeatures = a3_.id AND a3_.id = indirect2.BioEntities AND indirect2.DataSets = a4_.id AND a1_.organismId = a5_.id AND a2_.ontologyTermId = a6_.id AND LOWER(a5_.name) LIKE 'drosophila melanogaster' AND LOWER(a6_.name) LIKE 'gap junction' AND LOWER(a4_.name) LIKE 'drosdel p-element and deletion collection') AS a1_ GROUP BY a1_.a7_ ORDER BY a3_ DESC, a1_.a7_ LIMIT 5000

  at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1215)
  at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1131)
  at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.execute(ObjectStoreInterMineImpl.java:1022)
  at org.intermine.objectstore.query.ResultsBatches.fetchBatchFromObjectStore(ResultsBatches.java:192)
  at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:241)
  at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:146)
  at org.intermine.objectstore.query.ResultsBatches.getBatch(ResultsBatches.java:164)
  at org.intermine.objectstore.query.ResultsBatches.size(ResultsBatches.java:234)
  at org.intermine.objectstore.query.Results.size(Results.java:269)
  at org.intermine.api.query.QueryExecutor.uniqueColumnValues(QueryExecutor.java:233)
  at org.intermine.webservice.server.query.result.QueryResultService.setHeaderAttributes(QueryResultService.java:165)
  at org.intermine.webservice.server.query.result.QueryResultService.execute(QueryResultService.java:105)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.query.result.QueryResultServlet.runService(QueryResultServlet.java:61)
  at org.intermine.webservice.server.query.result.QueryResultServlet.doPost(QueryResultServlet.java:43)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

```

This query wouldn't run:

```

<template name="GOterm_genesDrosDelDeletion" title="GO term name [D. melanogaster] --&gt; All genes with DrosDel deletions." comment="">
  <query name="GOterm_genesDrosDelDeletion" model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.goAnnotation.ontologyTerm.identifier Gene.goAnnotation.ontologyTerm.name Gene.overlappingFeatures.secondaryIdentifier Gene.overlappingFeatures.available" longDescription="Show all D. melanogaster genes that have been annotated with a particular GO term and the DrosDel deletions which would delete these genes.  Show whether the deletion is available. (Data Source: GO, FlyBase, DrosDel)." sortOrder="Gene.secondaryIdentifier asc" constraintLogic="A and B and C">
    <pathDescription pathString="Gene.goAnnotation" description="Go annotation"/>
    <pathDescription pathString="Gene.overlappingFeatures" description="DrosDel deletion"/>
    <pathDescription pathString="Gene.goAnnotation.ontologyTerm" description="GO term"/>
    <constraint path="Gene.goAnnotation.ontologyTerm" editable="false" type="GOTerm"/>
    <constraint path="Gene.overlappingFeatures.dataSets.name" code="C" editable="false" op="=" value="DrosDel P-element and Deletion collection"/>
    <constraint path="Gene.overlappingFeatures" editable="false" type="ChromosomalDeletion"/>
    <constraint path="Gene.organism.name" code="A" editable="false" op="=" value="Drosophila melanogaster"/>
    <constraint path="Gene.goAnnotation.ontologyTerm.name" code="B" editable="true" description="GO Term" op="=" value="gap junction"/>
  </query>
</template>
```

**Comment by julie-sullivan** [comment]
other "bad" queries:

 * GOterm_genesDrosDelDeletion

**Comment by julie-sullivan** [comment]
* Chromosome_CRMOverlappingInsertion
* PointMutation_Gene_Chromosome

**Comment by julie-sullivan** [comment]
These are chromosomes:

* rDNA
* 211000022278604
* 211000022278522

**Comment by julie-sullivan** [comment]
```
FB2015_03=# SELECT feature.feature_id,feature.name,feature.organism_id FROM feature, cvterm     WHERE feature.type_id = cvterm.cvterm_id
                   AND cvterm.name = 'chromosome' ;
 feature_id |           name            | organism_id 
------------+---------------------------+-------------
   23159230 | unspecified               |           1
   23159219 | X                         |           1
   23159222 | 4                         |           1
   23159223 | Y                         |           1
   23159221 | 3                         |           1
   23159220 | 2                         |           1
   67439085 | dmel_mitochondrion_genome |           1
   10711770 | dmel_mitochondrion_genome |           1
(8 rows)
```

@rachellyne Does that look right to you?

**Comment by julie-sullivan** [comment]
```
FB2015_03=# SELECT feature.feature_id,feature.name,feature.organism_id FROM feature, cvterm     WHERE feature.type_id = cvterm.cvterm_id
                   AND cvterm.name = 'chromosome_arm' ;

 feature_id |      name      | organism_id 
------------+----------------+-------------
   10713330 |                |         214
   10712471 |                |         214
   62049273 |                |           1
   62049280 |                |           1
   62049449 |                |           1
   62049333 |                |           1
   62049384 |                |           1
   62049563 |                |           1
   10712918 |                |         214
   10712050 |                |         214
   44395171 |                |           7
          6 | X_r3           |           1
          3 | 3R_r3          |           1
          5 | 4_r3           |           1
          4 | 3L_r3          |           1
          1 | 2L_r3          |           1
          2 | 2R_r3          |           1
    4554731 | 2Rnew_11460001 |           1
    3214121 | 2L_r4          |           1
    3214122 | 2R_r4          |           1
    3214124 | 3R_r4          |           1
    3214123 | 3L_r4          |           1
    3214125 | X_r4           |           1
    3208383 | 4_r4           |           1
          7 | U_r3           |           1
   11494722 | 2_r5           |           1
   26139133 | YHet_r5        |           1
   11494721 | 2_r5           |           1
   11494723 | X_r5           |           1
   11494725 | 3_r5           |           1
   11494726 | 3_r5           |           1
   11494724 | 4_r5           |           1
   26139136 | Uextra_r5      |           1
   26139131 | 2RHet_r5       |           1
   26139130 | 2LHet_r5       |           1
   26139134 | 3LHet_r5       |           1
   26139135 | 3RHet_r5       |           1
   11494727 | U_r5           |           1
   26139132 | XHet_r5        |           1
   55526198 |                |           1
   23159228 | 4              |           1
   23159229 | Y              |           1
   23159225 | 4              |           1
   23159226 | Y              |           1
   23159227 | X              |           1
   23159224 | X              |           1
   31765643 |                |         238
   31765646 |                |         372
   10713409 |                |         214
   10713099 |                |         214
   44885629 |                |           1
(51 rows)

```

**Comment by rachellyne** [comment]
It looks as though the chromosomes (and arms) have loaded correctly but we don't have the heterochromatin (het) and now we have a load of contig ids in addition - we don't load these as chromosomes.

**Comment by julie-sullivan** [comment]
@rachellyne How do I fix?

**Comment by rachellyne** [comment]
It might be ok - the het regions are now incorporated into the main arms, so that's why we don't have them.  There are now a smaller number of scaffolds so we might want to load them - i'll look a bit further.

**Comment by julie-sullivan** [comment]
@rachellyne Okay, let me know what I can do. I think it's going to take a bit of thought to adapt these changes to how flymine does things.

**Comment by rachellyne** [comment]
It looks mostly fine.  To be correct, if we load the extra scaffolds I think the correct SO_term is unassigned_supercontig.  What did we do previously - just ignore these?  We don't load them, so must have ignored them somehow?  Do we model assembly units with in any other databases?

**Comment by rachellyne** [comment]
Also - mitochondrion genome is missing from beta.

**Comment by julie-sullivan** [comment]
> Also - mitochondrion genome is missing from beta.

@rachellyne How I do fix?

**Comment by julie-sullivan** [comment]
> It looks mostly fine. 

@rachellyne Okay. But there are still lots of wrong templates, and the overlaps are wrong.

**Comment by julie-sullivan** [comment]
> To be correct, if we load the extra scaffolds I think the correct SO_term is unassigned_supercontig.  What did we do previously - just ignore these?  We don't load them, so must have ignored them somehow?  Do we model assembly units with in any other databases?

@rachellyne I don't know.

**Comment by rachellyne** [comment]
I meant just the chromosomes look ok.

**Comment by julie-sullivan** [comment]
@rachellyne Oh ha! You got my hopes up ...

**Comment by rachellyne** [comment]
Well, we didn't load the scaffolds before so maybe we shouldn't change - I don't think there will be much data attached to them.  We must have excluded them somehow before or has the CHADO database model changed more significantly?  Can we just exclude those feature ids?  They all start 211.

**Comment by julie-sullivan** [comment]
no problem, will exclude features of "unassigned_supercontig" type. I see here we tried to exclude golden paths and ultra_scaffolds:

https://github.com/intermine/intermine/blob/beta/bio/sources/chado-db/main/src/org/intermine/bio/dataconversion/FlyBaseProcessor.java#L712-L713

**Comment by julie-sullivan** [comment]
@rachellyne You said I hadn't fixed this?

**Comment by rachellyne** [comment]
There are a huge number of contigs as chromosomes - it's messing up the chromosome viewer.

**Comment by julie-sullivan** [comment]
```
FB2017_01=# SELECT cvterm.name FROM feature, cvterm     WHERE feature.type_id = cvterm.cvterm_id and feature.uniquename = '211000022278880';
        name        
--------------------
 golden_path_region
(1 row)

```

Golden path regions are still being loaded.

**Comment by julie-sullivan** [comment]
Removing golden path regions caused this error:

```
Caused by: java.lang.NullPointerException
        at org.intermine.bio.dataconversion.FlyBaseProcessor.makeAndStoreLocation(FlyBaseProcessor.java:1065)
        at org.intermine.bio.dataconversion.FlyBaseProcessor.copyInsertionLocations(FlyBaseProcessor.java:1162)
        at org.intermine.bio.dataconversion.FlyBaseProcessor.extraProcessing(FlyBaseProcessor.java:902)
        at org.intermine.bio.dataconversion.SequenceProcessor.process(SequenceProcessor.java:186)
        at org.intermine.bio.dataconversion.ChadoDBConverter.process(ChadoDBConverter.java:158)
        at org.intermine.task.DBConverterTask.execute(DBConverterTask.java:86)
        ... 31 more

```

I have to remove insertions that are located on golden paths too.

**Comment by rachellyne** [comment]
We are still getting some additional chromosomes - e.g. we have a D. mel chromosome 2 (with no located features).  For D. mel we should have 2L, 2R, 3L, 3R, 4, X and Y.  For release6 most of the heterochromatin was incorporated into the main chromosome arms, but we still have 2H, 3H etc.  We also have XL and XR etc - I think X and Y have always been just X and Y, not divided into arms. There are also three scaffolds still appearing : 211000022278760, 211000022279188 and 211000022280328 and an unmapped scaffold: Unmapped_Scaffold_8_D1580_D1567.

**Comment by julie-sullivan** [comment]
@rachellyne I am putting golden paths back in. I don't know how to solve this problem. I don't know how to tell the "good" chromosomes from the bad.

**Comment by julie-sullivan** [comment]
@rachellyne I am going to close this ticket. If you can come up with a way for me to tell which are the "good" chromosomes in FlyBase, please reopen.
