### ISSUE TITLE
Simple objects fail to show in results tables with outer joins

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1053]
Running this query in humanmine fails:

```
<query name="" model="genomic" view="SNV.consequences.transcript.primaryIdentifier SNV.primaryIdentifier" longDescription="">
  <join path="SNV.consequences.transcript" style="OUTER"/>
  <constraint path="SNV" op="LOOKUP" value=" rs118136425" extraValue=""/>
</query>
```

With this error:

```
26/06/15,08:37:42 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
start: 0
size: 250
query: <query model="genomic" view="SNV.consequences.description SNV.consequences.transcript.primaryIdentifier" ><join path="SNV.consequences.transcript" style="OUTER"/><constraint path="SNV.id" op="=" value="92751200" code="A" /></query
>
format: json
java.lang.RuntimeException: ObjectStore error has occurred (in get)

  at org.intermine.objectstore.query.Results.get(Results.java:233)
  at org.intermine.objectstore.query.Results$Iter.hasNext(Results.java:378)
  at org.intermine.webservice.server.core.TableRowIterator.hasNext(TableRowIterator.java:485)
  at org.intermine.webservice.server.query.result.TableRowService.runPathQuery(TableRowService.java:108)
  at org.intermine.webservice.server.query.result.QueryResultService.execute(QueryResultService.java:106)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.query.result.QueryResultServlet.runService(QueryResultServlet.java:61)
  at org.intermine.webservice.server.query.result.QueryResultServlet.doPost(QueryResultServlet.java:43)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
 ...
 caused by: org.intermine.objectstore.ObjectStoreException: Object is of wrong type while converting results: null

  at org.intermine.objectstore.intermine.ResultsConverter.convert(ResultsConverter.java:254)
  at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1229)
  at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1124)
  at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.execute(ObjectStoreInterMineImpl.java:1015)
  at org.intermine.objectstore.query.ResultsBatches.fetchBatchFromObjectStore(ResultsBatches.java:192)
  at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:241)
  at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:146)
  at org.intermine.objectstore.query.ResultsBatches.getBatch(ResultsBatches.java:164)
  at org.intermine.objectstore.query.ResultsBatches.getRowsFromBatch(ResultsBatches.java:139)
  at org.intermine.objectstore.query.Results.range(Results.java:197)
  at org.intermine.objectstore.query.Results.get(Results.java:226)
  at org.intermine.objectstore.query.Results$Iter.hasNext(Results.java:378)
  at org.intermine.webservice.server.core.TableRowIterator.hasNext(TableRowIterator.java:485)
  at org.intermine.webservice.server.query.result.TableRowService.runPathQuery(TableRowService.java:108)
  at org.intermine.webservice.server.query.result.QueryResultService.execute(QueryResultService.java:106)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.query.result.QueryResultServlet.runService(QueryResultServlet.java:61)
  at org.intermine.webservice.server.query.result.QueryResultServlet.doPost(QueryResultServlet.java:43)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
 ...
 caused by: java.lang.ClassCastException: org.intermine.model.bio.Consequence cannot be cast to org.intermine.model.InterMineObject

  at org.intermine.objectstore.intermine.ResultsConverter.fetchObjectPathExpression(ResultsConverter.java:391)
  at org.intermine.objectstore.intermine.ResultsConverter.convert(ResultsConverter.java:228)
  at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1229)
  at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1124)
  at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.execute(ObjectStoreInterMineImpl.java:1015)
  at org.intermine.objectstore.query.ResultsBatches.fetchBatchFromObjectStore(ResultsBatches.java:192)
  at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:241)
```

**Comment by julie-sullivan** [comment]
@rachellyne Maybe we could have a template that would do a similar query, to help us test.

**Comment by julie-sullivan** [comment]
![simple-outer](https://cloud.githubusercontent.com/assets/1663057/8379439/fe96538e-1c17-11e5-8226-0960652e2ad5.png)

**Comment by julie-sullivan** [comment]
It seems the collections on report pages use outer joins by default, hence the error. We should be able to configure the webconfig-model to use inner joins instead.

**Comment by julie-sullivan** [comment]
Didn't throw an error, which is good. But didn't show the "type" correctly either:

![simple-objs](https://cloud.githubusercontent.com/assets/1663057/8672837/e6065470-2a29-11e5-99c4-574bbd8a8af3.png)

**Comment by julie-sullivan** [comment]
@rnsmith Never mind, user error.

**Comment by julie-sullivan** [comment]
@rnsmith It works great. I checked gene, protein and publication report pages. All looks good. What else would you suggest I test for this pull request?

**Comment by rnsmith** [comment]
I think that's probably it - if the objectstore tests pass and outer joins work with normal and simple objects that should be good.
