### ISSUE TITLE
FlyMine: flyfish failed on dull pointer exception

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1065]
```
Wed Jul  1 18:44:14 BST 2015

starting command: ant -v -Dsource=fly-fish


BUILD FAILED
/data/code/intermine/imbuild/integrate.xml:54: The following error occurred while executing this line:
/data/code/intermine/imbuild/source.xml:330: java.lang.NullPointerException
        at org.intermine.sql.DatabaseUtil.getTableName(DatabaseUtil.java:608)
        at org.intermine.dataloader.DataLoaderHelper.getPrimaryKeyTableNames(DataLoaderHelper.java:334)
        at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:95)
        at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:63)
        at org.intermine.dataloader.ObjectStoreDataLoaderTask.execute(ObjectStoreDataLoaderTask.java:128)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)

```

**Comment by julie-sullivan** [comment]
Duplicate, see #985
