### ISSUE TITLE
More queries link in summary area on http://www.flymine.org/ fails

### ISSUE THREAD

**Issue by justinccdev** [intermine/intermine#1067]
Reports "Unable to load user profile".  Manually clicking templates tab is fine.  Other mines (humanmine, ratmine, synbiomine) appear to work ok.

**Comment by julie-sullivan** [comment]
```
java.lang.RuntimeException: Unable to load user profile
	at org.intermine.api.profile.TagManager.getUserProfile(TagManager.java:661)
	at org.intermine.api.profile.TagManager.checkUserExists(TagManager.java:94)
	at org.intermine.api.profile.TagManager.getTags(TagManager.java:413)
	at org.intermine.web.struts.ReportController.categoriseBasedOnTags(ReportController.java:291)
	at org.intermine.web.struts.ReportController.execute(ReportController.java:175)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
```

**Comment by justinccdev** [comment]
Same failure if you go the templates tab and then select any category to filter on.

**Comment by julie-sullivan** [comment]
Works now after a restart.
