### ISSUE TITLE
error connecting to chado db

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1078]
I was running a build and got this error when running the ID resolver. For fly, this queries the flybase chado db. I assume I am running out of connections? 

```
BUILD FAILED
/data/code/intermine/imbuild/integrate.xml:54: The following error occurred while executing this line:
/data/code/intermine/imbuild/source.xml:253: java.lang.IllegalArgumentException: mRNA IdResolver has no data for taxonId: '7227'.
        at org.intermine.bio.dataconversion.IdResolver.checkTaxonId(IdResolver.java:83)
        at org.intermine.bio.dataconversion.IdResolver.countResolutions(IdResolver.java:220)
        at org.intermine.bio.dataconversion.MirandaGFF3RecordHandler.getTarget(MirandaGFF3RecordHandler.java:79)
        at org.intermine.bio.dataconversion.MirandaGFF3RecordHandler.process(MirandaGFF3RecordHandler.java:62)
        at org.intermine.bio.dataconversion.GFF3Converter.process(GFF3Converter.java:358)
        at org.intermine.bio.dataconversion.GFF3Converter.parse(GFF3Converter.java:226)
        at org.intermine.bio.task.GFF3ConverterTask.execute(GFF3ConverterTask.java:241)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
        at org.intermine.task.Integrate.performAction(Integrate.java:223)
        at org.intermine.task.Integrate.performAction(Integrate.java:135)
        at org.intermine.task.Integrate.execute(Integrate.java:127)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.Main.runBuild(Main.java:809)
        at org.apache.tools.ant.Main.startAnt(Main.java:217)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)



Total time: 1 minute 40 seconds
Thu Jul  9 19:10:05 BST 2015

finished


ERROR: 256
failed with exit code 0: ant -v -Dsource=miranda


```

**Comment by julie-sullivan** [comment]
Maybe up the total number of connections, since this is our dev server. @rnsmith ?

**Comment by julie-sullivan** [comment]
@sergiocontrino Can you run a thale build on the beta branch for me? To see if these are julie-specific issues?

**Comment by rnsmith** [comment]
It looks like Hikari has a `ConnectionProxy` referencing a connection that has ceased to exist. It looks like it may not be a case of running out of connections. Could it be that the idResolver is closing a connection then trying to use it again? We'd need to see the whole stacktrace to see where the issue is.

It may also be a problem with too many connections but the flybase database should have it's own pool.

**Comment by julie-sullivan** [comment]
Thanks @rnsmith! I've edited the above msg to include the full stacktrace. I'll investigate the ID resolver.

**Comment by julie-sullivan** [comment]
```
2015-07-10 09:13:13 INFO  org.intermine.bio.dataconversion.FlyBaseIdResolverFactory     - dbxref query returned 67309 rows.
2015-07-10 09:13:13 INFO  org.intermine.bio.dataconversion.FlyBaseIdResolverFactory     - QUERY: select c.cvterm_id from cvterm c, cv where c.cv_id = cv.cv_id and cv.name = 'SO' and c.name ='mRNA'
2015-07-10 09:13:13 ERROR org.intermine.bio.dataconversion.FlyBaseIdResolverFactory     - org.postgresql.util.PSQLException: This connection has been closed.
```

**Comment by julie-sullivan** [comment]
I didn't have the number of connections set for the chado data source. I am dumb.
