### ISSUE TITLE
QueryBuilder: not handling collections correctly

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1088]
Last week I forked the master branch of Intermine (latest commit 233c6c6bca3).

I was trying to create collections with the following in my source additions.xml,

```
<class name="Gene" extends="SequenceFeature" is-interface="true">
<collection name="snps" referenced-type="SNP" reverse-reference="geneIdentifier"/>
</class>

<class name="SNP" extends="SequenceFeature" is-interface="true">
<attribute name="synonymous" type="java.lang.Boolean"/>
<collection name="geneIdentifier" referenced-type="Gene" reverse-reference="snps"/>
</class>
```

I am able to get the collection to display, as expected in the results page. 
But in Query Builder, if I try to query Gene and its SNP collection, I get the following error as the result when I run the query:

> Error: Could not find snps in undefined when parsing Gene.snps.synonymous

I tried the same configuration on an old instance of Intermine (forked on Feb 12, 2015) and the query builder works fine.

Was there any drastic changes to the way collections are handled on the webapp between these two versions?

**Comment by julie-sullivan** [comment]
```
Error: Could not find snps in undefined when parsing Gene.snps.primaryIdentifier
    at http://cdn.intermine.org/js/intermine/imjs/3.14.0/im.js:1141:17
    at Function.7.PathInfo.parse (http://cdn.intermine.org/js/intermine/imjs/3.14.0/im.js:1148:7)
    at Model.6.Model.getPathInfo (http://cdn.intermine.org/js/intermine/imjs/3.14.0/im.js:827:23)
    at Model.6.__bind [as getPathInfo] (http://cdn.intermine.org/js/intermine/imjs/3.14.0/im.js:788:61)
    at Query.9.Query.getPathInfo (http://cdn.intermine.org/js/intermine/imjs/3.14.0/im.js:1925:88)
    at 231.liftPathAndType (http://cdn.intermine.org/js/intermine/im-tables/2.0.0-beta/imtables.js:24756:21)
    at Array.map (native)
    at UndoStep.231.module.exports.UndoStep.initialize (http://cdn.intermine.org/js/intermine/im-tables/2.0.0-beta/imtables.js:24799:41)
    at UndoStep.232.Backbone.View (http://cdn.intermine.org/js/intermine/im-tables/2.0.0-beta/imtables.js:26242:21)
    at UndoStep.CoreView [as constructor] (http://cdn.intermine.org/js/intermine/im-tables/2.0.0-beta/imtables.js:255:45)

```

**Comment by julie-sullivan** [comment]
From Deepak Unni.

**Comment by julie-sullivan** [comment]
There were no error messages in the tomcat logs.

**Comment by joshkh** [comment]
Pinning this here for investigation:
Error thrown at https://github.com/intermine/imjs/blob/v3.14.0/src/path.coffee#L212

**Comment by julie-sullivan** [comment]
This is fixed in the current release.
