### ISSUE TITLE
Report page: error when trying to make a list from a collection

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1090]
From @JoelRichardson 

Another issue… when I try to save a list from a collection on a report page, I'm getting a "service failed" error. 
Here's an example error:

```
15/07/15,16:26:18 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
tags: 
listName: Sequence Feature List (Wed Jul 15 2015 16:26:14 GMT-0400 (EDT))
query: <query model="genomic" view="Gene.targets.target.id" ><join path="Gene.targets.target" style="OUTER"/><constraint path="Gene.id" op="=" value="7634344" code="A" /><constraint path="Gene.targets.id" op="IS NOT NULL" /></query>
name: Sequence Feature List (Wed Jul 15 2015 16:26:14 GMT-0400 (EDT))
java.lang.IllegalArgumentException: Query has incorrect number of SELECT elements.

  at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.addToBagFromQuery(ObjectStoreWriterInterMineImpl.java:1195)
  at org.intermine.api.profile.InterMineBag.addToBagFromQuery(InterMineBag.java:786)
  at org.intermine.webservice.server.query.QueryToListService.generateListFromQuery(QueryToListService.java:154)
  at org.intermine.webservice.server.query.QueryToListService.execute(QueryToListService.java:95)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.query.QueryToListServlet.runService(QueryToListServlet.java:59)
  at org.intermine.webservice.server.query.QueryToListServlet.doPost(QueryToListServlet.java:46)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
```

The query looks OK to me. I can paste it into the query builder and run it with no problem. 

Oh, I should mention, this is in trying to upgrade to InterMine 1.5.3.

**Comment by julie-sullivan** [comment]
I went to debug this on my local machine and it works. : / I see the problem on beta flymine though.

**Comment by julie-sullivan** [comment]
I can't replicate the problem locally or on beta flymine any more. On the master branch (1.5.6) or the 1.5.3 code. Everything is behaving as expected.

**Comment by joshkh** [comment]
I can't replicate this either. Like MouseMine I set both use.localstorage to false (which if enabled will override the automatic expanding or collapsing of collections) and web.collections.expandonload to false, and everything works as expected.

**Comment by julie-sullivan** [comment]
Same problem as https://github.com/intermine/intermine/issues/1089#issuecomment-121922290

**Comment by JoelRichardson** [comment]
Well, so far I don't see a pattern. Sometimes it works to save a list from a collection and sometimes it doesn't. I added some log statements and got the following additional info. The "wrong" number of select parameters is 2. Here's an example of a query it doesn't like:
```sql
SELECT DISTINCT a2_, a2_.member AS a3_ 
FROM org.intermine.model.bio.ComplexClusterRegion AS a1_, org.intermine.model.bio.MGIClusterHasMember AS a2_ 
WHERE (a1_.members CONTAINS a2_ 
AND a1_.id = 9300703 AND a2_.id IS NOT NULL)
```
and the corresponding XML query
```xml
<query model="genomic" view="ComplexClusterRegion.members.member.id" >
  <join path="ComplexClusterRegion.members.member" style="OUTER"/>
  <constraint path="ComplexClusterRegion.id" op="=" value="9300703" code="A" />
  <constraint path="ComplexClusterRegion.members.id" op="IS NOT NULL" />
</query>
```

**Comment by JoelRichardson** [comment]
I did find an example in FlyMine that results in an error. I don't know if it's really the same thing vecause I can't see the logs, but it looks the same from this end. (1) go the the report page for FBal0000008. (2) scroll down to the table labelled "7 phenotype annotations" . (3) Try to save the one allele as a list. Choose the one with path "Allele > Phenotype Annotations > Allele". You will get the error.

I realize this is a contrived example - no one would actually do this (probably). But everything else I tried at FlyMine worked ok. 

Again, I'm still looking for a consistent pattern for when the error shows up.

**Comment by chenyian-nibio** [comment]
I think I got the same problem reported by the user. 
I GUESS the problem is due to the outer join. Seems that when saving the list, the query for getting internal ids depends on the original query. If the original query contains outer join, the system will uses outer join to retrieve the internal ids for saving as a list. However, InterMine won't distinct the results for outer join queries. If there are redundant ids, the number will not match the expected number and finally get the exception.

You can reproduce this error by trying this query in FlyMine:
```
<query name="" model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.primaryIdentifier Gene.organism.name Gene.goAnnotation.evidence.code.code Gene.goAnnotation.ontologyTerm.identifier Gene.goAnnotation.ontologyTerm.name" longDescription="" sortOrder="Gene.secondaryIdentifier asc">
  <join path="Gene.goAnnotation.evidence.code" style="OUTER"/>
  <join path="Gene.goAnnotation.ontologyTerm" style="OUTER"/>
  <join path="Gene.organism" style="OUTER"/>
  <constraint path="Gene" op="LOOKUP" value="zen"/>
</query>

```
Then if you try to save the ontology terms, you will see the error. (11 not equal 10)
