### ISSUE TITLE
FlyMine: Queries using overlaps are failing

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1095]
Running this query causes an error:

http://beta.flymine.org/beta/template.do?name=GOterm_genesDrosDelDeletion&scope=all

```
2015-07-30 11:34:37 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
query: <query model="genomic" view="Gene.secondaryIdentifier Gene.symbol Gene.goAnnotation.ontologyTerm.identifier Gene.goAnnotation.ontologyTerm.name Gene.overlappingFeatures.secondaryIdentifier Gene.overlappingFeatures.available Gene.organism.id" sortOrder="Gene.secondaryIdentifier ASC" constraintLogic="A and B and C" name="GOterm_genesDrosDelDeletion" ><constraint path="Gene.overlappingFeatures" type="ChromosomalDeletion" /><constraint path="Gene.goAnnotation.ontologyTerm" type="GOTerm" /><constraint path="Gene.organism.name" op="=" value="Drosophila melanogaster" code="A" /><constraint path="Gene.overlappingFeatures.dataSets.name" op="=" value="DrosDel P-element and Deletion collection" code="C" /><constraint path="Gene.goAnnotation.ontologyTerm.name" op="=" value="gap junction" code="B" /></query>
summaryPath: Gene.organism.id
format: jsonrows
java.lang.RuntimeException: ObjectStore error has occurred in size()

  at org.intermine.objectstore.query.ResultsBatches.size(ResultsBatches.java:236)
  at org.intermine.objectstore.query.Results.size(Results.java:269)
  at org.intermine.api.query.QueryExecutor.uniqueColumnValues(QueryExecutor.java:233)
  at org.intermine.webservice.server.query.result.QueryResultService.setHeaderAttributes(QueryResultService.java:165)
  at org.intermine.webservice.server.query.result.QueryResultService.execute(QueryResultService.java:105)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.query.result.QueryResultServlet.runService(QueryResultServlet.java:61)
  at org.intermine.webservice.server.query.result.QueryResultServlet.doPost(QueryResultServlet.java:43)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
 ...
 caused by: org.intermine.objectstore.ObjectStoreQueryDurationException: Estimated time to run query(28121797210) greater than permitted maximum (10000000000): IQL query: SELECT DISTINCT a1_.a7_ AS a2_, COUNT(*) AS a3_ FROM (SELECT DISTINCT a1_, a6_, a3_, a4_, a4_.id AS a7_ FROM org.intermine.model.bio.Gene AS a1_, org.intermine.model.bio.GOAnnotation AS a2_, org.intermine.model.bio.ChromosomalDeletion AS a3_, org.intermine.model.bio.Organism AS a4_, org.intermine.model.bio.DataSet AS a5_, org.intermine.model.bio.GOTerm AS a6_ WHERE (a1_.goAnnotation CONTAINS a2_ AND a1_.overlappingFeatures CONTAINS a3_ AND a1_.organism CONTAINS a4_ AND a3_.dataSets CONTAINS a5_ AND a2_.ontologyTerm CONTAINS a6_ AND LOWER(a4_.name) LIKE 'drosophila melanogaster' AND LOWER(a6_.name) LIKE 'gap junction' AND LOWER(a5_.name) LIKE 'drosdel p-element and deletion collection')) AS a1_ GROUP BY a1_.a7_ ORDER BY COUNT(*) DESC, SQL query: SELECT DISTINCT a1_.a7_ AS a2_, COUNT(*) AS a3_ FROM (SELECT DISTINCT a1_.briefDescription AS a1_briefDescription, a1_.chromosomeId AS a1_chromosomeId, a1_.chromosomeLocationId AS a1_chromosomeLocationId, a1_.cytoLocation AS a1_cytoLocation, a1_.description AS a1_description, a1_.downstreamIntergenicRegionId AS a1_downstreamIntergenicRegionId, a1_.id AS a1_id, a1_.length AS a1_length, a1_.name AS a1_name, a1_.organismId AS a1_organismId, a1_.primaryIdentifier AS a1_primaryIdentifier, a1_.score AS a1_score, a1_.scoreType AS a1_scoreType, a1_.secondaryIdentifier AS a1_secondaryIdentifier, a1_.sequenceId AS a1_sequenceId, a1_.sequenceOntologyTermId AS a1_sequenceOntologyTermId, a1_.symbol AS a1_symbol, a1_.upstreamIntergenicRegionId AS a1_upstreamIntergenicRegionId, a6_.description AS a6_description, a6_.id AS a6_id, a6_.identifier AS a6_identifier, a6_.name AS a6_name, a6_.namespace AS a6_namespace, a6_.obsolete AS a6_obsolete, a6_.ontologyId AS a6_ontologyId, a3_.available AS a3_available, a3_.chromosomeId AS a3_chromosomeId, a3_.chromosomeLocationId AS a3_chromosomeLocationId, a3_.confirmedByGenetics AS a3_confirmedByGenetics, a3_.confirmedByPCR AS a3_confirmedByPCR, a3_.cytoLocation AS a3_cytoLocation, a3_.element1Id AS a3_element1Id, a3_.element2Id AS a3_element2Id, a3_.id AS a3_id, a3_.length AS a3_length, a3_.name AS a3_name, a3_.organismId AS a3_organismId, a3_.primaryIdentifier AS a3_primaryIdentifier, a3_.score AS a3_score, a3_.scoreType AS a3_scoreType, a3_.secondaryIdentifier AS a3_secondaryIdentifier, a3_.sequenceId AS a3_sequenceId, a3_.sequenceOntologyTermId AS a3_sequenceOntologyTermId, a3_.symbol AS a3_symbol, a4_.commonName AS a4_commonName, a4_.genus AS a4_genus, a4_.id AS a4_id, a4_.name AS a4_name, a4_.shortName AS a4_shortName, a4_.species AS a4_species, a4_.taxonId AS a4_taxonId, a4_.id AS a7_ FROM Gene AS a1_, GOAnnotation AS a2_, ChromosomalDeletion AS a3_, Organism AS a4_, DataSet AS a5_, GOTerm AS a6_, GeneGoAnnotation AS indirect0, OverlappingFeaturesSequenceFeature AS indirect1, BioEntitiesDataSets AS indirect2 WHERE a1_.id = indirect0.Gene AND indirect0.GoAnnotation = a2_.id AND a1_.id = indirect1.SequenceFeature AND indirect1.OverlappingFeatures = a3_.id AND a1_.organismId = a4_.id AND a3_.id = indirect2.BioEntities AND indirect2.DataSets = a5_.id AND a2_.ontologyTermId = a6_.id AND LOWER(a4_.name) LIKE 'drosophila melanogaster' AND LOWER(a6_.name) LIKE 'gap junction' AND LOWER(a5_.name) LIKE 'drosdel p-element and deletion collection') AS a1_ GROUP BY a1_.a7_ ORDER BY a3_ DESC, a1_.a7_ LIMIT 5000

  at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1208)
  at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1124)
  at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.execute(ObjectStoreInterMineImpl.java:1015)
  at org.intermine.objectstore.query.ResultsBatches.fetchBatchFromObjectStore(ResultsBatches.java:192)
  at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:241)
  at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:146)
  at org.intermine.objectstore.query.ResultsBatches.getBatch(ResultsBatches.java:164)
  at org.intermine.objectstore.query.ResultsBatches.size(ResultsBatches.java:234)
  at org.intermine.objectstore.query.Results.size(Results.java:269)
  at org.intermine.api.query.QueryExecutor.uniqueColumnValues(QueryExecutor.java:233)
  at org.intermine.webservice.server.query.result.QueryResultService.setHeaderAttributes(QueryResultService.java:165)
  at org.intermine.webservice.server.query.result.QueryResultService.execute(QueryResultService.java:105)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.query.result.QueryResultServlet.runService(QueryResultServlet.java:61)
  at org.intermine.webservice.server.query.result.QueryResultServlet.doPost(QueryResultServlet.java:43)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

```

**Comment by julie-sullivan** [comment]
from FlyMine

```
2015-07-30 14:22:27 WARN  org.intermine.sql.precompute.QueryOptimiser     - Optimiser failed to parse query - the query will still be executed but precomputed tables won't be used. Query: SELECT DISTINCT a1_.a6_ AS a2_, a1_.a5_ AS a3_, a1_.a7_ AS a4_, a1_.a8_ AS a5_, a1_.a10_ AS a6_, a1_.a9_ AS a7_, SUM(a1_.a3_) AS a8_ FROM (SELECT COUNT(*) AS a3_, a1_.a2_ AS a4_, a2_.a3_ AS a5_, a2_.a2_ AS a6_, a2_.a4_ AS a7_, a2_.a5_ AS a8_, WIDTH_BUCKET(a1_.a2_, a2_.a2_, ((a2_.a3_)::NUMERIC * (1.01)::NUMERIC), a2_.a6_) AS a9_, a2_.a6_ AS a10_ FROM (SELECT a1_.a7_ AS a2_ FROM (SELECT DISTINCT a1_.briefDescription AS a1_briefDescription, a1_.chromosomeId AS a1_chromosomeId, a1_.chromosomeLocationId AS a1_chromosomeLocationId, a1_.cytoLocation AS a1_cytoLocation, a1_.description AS a1_description, a1_.downstreamIntergenicRegionId AS a1_downstreamIntergenicRegionId, a1_.id AS a1_id, a1_.length AS a1_length, a1_.name AS a1_name, a1_.organismId AS a1_organismId, a1_.primaryIdentifier AS a1_primaryIdentifier, a1_.score AS a1_score, a1_.scoreType AS a1_scoreType, a1_.secondaryIdentifier AS a1_secondaryIdentifier, a1_.sequenceId AS a1_sequenceId, a1_.sequenceOntologyTermId AS a1_sequenceOntologyTermId, a1_.symbol AS a1_symbol, a1_.upstreamIntergenicRegionId AS a1_upstreamIntergenicRegionId, a6_.description AS a6_description, a6_.id AS a6_id, a6_.identifier AS a6_identifier, a6_.name AS a6_name, a6_.namespace AS a6_namespace, a6_.obsolete AS a6_obsolete, a6_.ontologyId AS a6_ontologyId, a3_.available AS a3_available, a3_.chromosomeId AS a3_chromosomeId, a3_.chromosomeLocationId AS a3_chromosomeLocationId, a3_.confirmedByGenetics AS a3_confirmedByGenetics, a3_.confirmedByPCR AS a3_confirmedByPCR, a3_.cytoLocation AS a3_cytoLocation, a3_.element1Id AS a3_element1Id, a3_.element2Id AS a3_element2Id, a3_.id AS a3_id, a3_.length AS a3_length, a3_.name AS a3_name, a3_.organismId AS a3_organismId, a3_.primaryIdentifier AS a3_primaryIdentifier, a3_.score AS a3_score, a3_.scoreType AS a3_scoreType, a3_.secondaryIdentifier AS a3_secondaryIdentifier, a3_.sequenceId AS a3_sequenceId, a3_.sequenceOntologyTermId AS a3_sequenceOntologyTermId, a3_.symbol AS a3_symbol, a1_.id AS a7_ FROM Gene AS a1_, GOAnnotation AS a2_, ChromosomalDeletion AS a3_, DataSet AS a4_, Organism AS a5_, GOTerm AS a6_, GeneGoAnnotation AS indirect0, OverlappingFeaturesSequenceFeature AS indirect1, BioEntitiesDataSets AS indirect2 WHERE a1_.id = indirect0.Gene AND indirect0.GoAnnotation = a2_.id AND a1_.id = indirect1.SequenceFeature AND indirect1.OverlappingFeatures = a3_.id AND a3_.id = indirect2.BioEntities AND indirect2.DataSets = a4_.id AND a1_.organismId = a5_.id AND a2_.ontologyTermId = a6_.id AND LOWER(a5_.name) LIKE 'drosophila melanogaster' AND LOWER(a6_.name) LIKE 'dna%' AND LOWER(a4_.name) LIKE 'drosdel p-element and deletion collection') AS a1_) AS a1_, (SELECT DISTINCT MIN(a1_.a7_) AS a2_, MAX(a1_.a7_) AS a3_, AVG(a1_.a7_) AS a4_, STDDEV(a1_.a7_) AS a5_, LEAST(20,(MAX(a1_.a7_) - MIN(a1_.a7_))) AS a6_ FROM (SELECT DISTINCT a1_.briefDescription AS a1_briefDescription, a1_.chromosomeId AS a1_chromosomeId, a1_.chromosomeLocationId AS a1_chromosomeLocationId, a1_.cytoLocation AS a1_cytoLocation, a1_.description AS a1_description, a1_.downstreamIntergenicRegionId AS a1_downstreamIntergenicRegionId, a1_.id AS a1_id, a1_.length AS a1_length, a1_.name AS a1_name, a1_.organismId AS a1_organismId, a1_.primaryIdentifier AS a1_primaryIdentifier, a1_.score AS a1_score, a1_.scoreType AS a1_scoreType, a1_.secondaryIdentifier AS a1_secondaryIdentifier, a1_.sequenceId AS a1_sequenceId, a1_.sequenceOntologyTermId AS a1_sequenceOntologyTermId, a1_.symbol AS a1_symbol, a1_.upstreamIntergenicRegionId AS a1_upstreamIntergenicRegionId, a6_.description AS a6_description, a6_.id AS a6_id, a6_.identifier AS a6_identifier, a6_.name AS a6_name, a6_.namespace AS a6_namespace, a6_.obsolete AS a6_obsolete, a6_.ontologyId AS a6_ontologyId, a3_.available AS a3_available, a3_.chromosomeId AS a3_chromosomeId, a3_.chromosomeLocationId AS a3_chromosomeLocationId, a3_.confirmedByGenetics AS a3_confirmedByGenetics, a3_.confirmedByPCR AS a3_confirmedByPCR, a3_.cytoLocation AS a3_cytoLocation, a3_.element1Id AS a3_element1Id, a3_.element2Id AS a3_element2Id, a3_.id AS a3_id, a3_.length AS a3_length, a3_.name AS a3_name, a3_.organismId AS a3_organismId, a3_.primaryIdentifier AS a3_primaryIdentifier, a3_.score AS a3_score, a3_.scoreType AS a3_scoreType, a3_.secondaryIdentifier AS a3_secondaryIdentifier, a3_.sequenceId AS a3_sequenceId, a3_.sequenceOntologyTermId AS a3_sequenceOntologyTermId, a3_.symbol AS a3_symbol, a1_.id AS a7_ FROM Gene AS a1_, GOAnnotation AS a2_, ChromosomalDeletion AS a3_, DataSet AS a4_, Organism AS a5_, GOTerm AS a6_, GeneGoAnnotation AS indirect0, OverlappingFeaturesSequenceFeature AS indirect1, BioEntitiesDataSets AS indirect2 WHERE a1_.id = indirect0.Gene AND indirect0.GoAnnotation = a2_.id AND a1_.id = indirect1.SequenceFeature AND indirect1.OverlappingFeatures = a3_.id AND a3_.id = indirect2.BioEntities AND indirect2.DataSets = a4_.id AND a1_.organismId = a5_.id AND a2_.ontologyTermId = a6_.id AND LOWER(a5_.name) LIKE 'drosophila melanogaster' AND LOWER(a6_.name) LIKE 'dna%' AND LOWER(a4_.name) LIKE 'drosdel p-element and deletion collection') AS a1_) AS a2_ GROUP BY a1_.a2_, a2_.a3_, a2_.a2_, a2_.a4_, a2_.a5_, a2_.a6_) AS a1_ GROUP BY a1_.a6_, a1_.a5_, a1_.a7_, a1_.a8_, a1_.a9_, a1_.a10_ ORDER BY a1_.a9_, a1_.a6_, a1_.a5_, a1_.a7_, a1_.a8_, a1_.a10_, a8_ LIMIT 5000

```

**Comment by julie-sullivan** [comment]
The SQL being run by live flymine. This query runs.

```
2015-07-30 14:25:30 INFO                              sqllogger     - (VERBOSE) iql: SELECT DISTINCT a1_.a7_ AS a2_, COUNT(*) AS a3_ FROM (SELECT DISTINCT a1_, a6_, a3_, a4_, a4_.id AS a7_ FROM org.intermine.model.bio.Gene AS a1_, org.intermine.model.bio.GOAnnotation AS a2_, org.intermine.model.bio.ChromosomalDeletion AS a3_, org.intermine.model.bio.DataSet AS a4_, org.intermine.model.bio.Organism AS a5_, org.intermine.model.bio.GOTerm AS a6_ WHERE (a1_.goAnnotation CONTAINS a2_ AND a1_.overlappingFeatures CONTAINS a3_ AND a3_.dataSets CONTAINS a4_ AND a1_.organism CONTAINS a5_ AND a2_.ontologyTerm CONTAINS a6_ AND LOWER(a5_.name) LIKE 'drosophila melanogaster' AND LOWER(a6_.name) LIKE 'gap junction' AND LOWER(a4_.name) LIKE 'drosdel p-element and deletion collection')) AS a1_ GROUP BY a1_.a7_ ORDER BY COUNT(*) DESC
generated sql: SELECT DISTINCT a1_.a7_ AS a2_, COUNT(*) AS a3_ FROM (SELECT DISTINCT a1_.briefDescription AS a1_briefDescription, a1_.chromosomeId AS a1_chromosomeId, a1_.chromosomeLocationId AS a1_chromosomeLocationId, a1_.cytoLocation AS a1_cytoLocation, a1_.description AS a1_description, a1_.downstreamIntergenicRegionId AS a1_downstreamIntergenicRegionId, a1_.id AS a1_id, a1_.length AS a1_length, a1_.name AS a1_name, a1_.organismId AS a1_organismId, a1_.primaryIdentifier AS a1_primaryIdentifier, a1_.score AS a1_score, a1_.scoreType AS a1_scoreType, a1_.secondaryIdentifier AS a1_secondaryIdentifier, a1_.sequenceId AS a1_sequenceId, a1_.sequenceOntologyTermId AS a1_sequenceOntologyTermId, a1_.symbol AS a1_symbol, a1_.upstreamIntergenicRegionId AS a1_upstreamIntergenicRegionId, a6_.description AS a6_description, a6_.id AS a6_id, a6_.identifier AS a6_identifier, a6_.name AS a6_name, a6_.namespace AS a6_namespace, a6_.obsolete AS a6_obsolete, a6_.ontologyId AS a6_ontologyId, a3_.available AS a3_available, a3_.chromosomeId AS a3_chromosomeId, a3_.chromosomeLocationId AS a3_chromosomeLocationId, a3_.confirmedByGenetics AS a3_confirmedByGenetics, a3_.confirmedByPCR AS a3_confirmedByPCR, a3_.cytoLocation AS a3_cytoLocation, a3_.element1Id AS a3_element1Id, a3_.element2Id AS a3_element2Id, a3_.id AS a3_id, a3_.length AS a3_length, a3_.name AS a3_name, a3_.organismId AS a3_organismId, a3_.primaryIdentifier AS a3_primaryIdentifier, a3_.score AS a3_score, a3_.scoreType AS a3_scoreType, a3_.secondaryIdentifier AS a3_secondaryIdentifier, a3_.sequenceId AS a3_sequenceId, a3_.sequenceOntologyTermId AS a3_sequenceOntologyTermId, a3_.symbol AS a3_symbol, a4_.dataSourceId AS a4_dataSourceId, a4_.description AS a4_description, a4_.id AS a4_id, a4_.name AS a4_name, a4_.publicationId AS a4_publicationId, a4_.url AS a4_url, a4_.version AS a4_version, a4_.id AS a7_ FROM Gene AS a1_, GOAnnotation AS a2_, ChromosomalDeletion AS a3_, DataSet AS a4_, Organism AS a5_, GOTerm AS a6_, GeneGoAnnotation AS indirect0, OverlappingFeaturesSequenceFeature AS indirect1, BioEntitiesDataSets AS indirect2 WHERE a1_.id = indirect0.Gene AND indirect0.GoAnnotation = a2_.id AND a1_.id = indirect1.SequenceFeature AND indirect1.OverlappingFeatures = a3_.id AND a3_.id = indirect2.BioEntities AND indirect2.DataSets = a4_.id AND a1_.organismId = a5_.id AND a2_.ontologyTermId = a6_.id AND LOWER(a5_.name) LIKE 'drosophila melanogaster' AND LOWER(a6_.name) LIKE 'gap junction' AND LOWER(a4_.name) LIKE 'drosdel p-element and deletion collection') AS a1_ GROUP BY a1_.a7_ ORDER BY a3_ DESC, a1_.a7_ LIMIT 5000
optimised sql: SELECT DISTINCT a1_.a7_ AS a2_, COUNT(*) AS a3_ FROM (SELECT DISTINCT P20948.a1_briefDescription, P20948.a1_chromosomeId, P20948.a1_chromosomeLocationId, P20948.a1_cytoLocation, P20948.a1_description, P20948.a1_downstreamIntergenicRegionId, P20948.a1_id, P20948.a1_length, P20948.a1_name, P20948.a1_organismId, P20948.a1_primaryIdentifier, P20948.a1_score, P20948.a1_scoreType, P20948.a1_secondaryIdentifier, P20948.a1_sequenceId, P20948.a1_sequenceOntologyTermId, P20948.a1_symbol, P20948.a1_upstreamIntergenicRegionId, a6_.description AS a6_description, a6_.id AS a6_id, a6_.identifier AS a6_identifier, a6_.name AS a6_name, a6_.namespace AS a6_namespace, a6_.obsolete AS a6_obsolete, a6_.ontologyId AS a6_ontologyId, a3_.available AS a3_available, a3_.chromosomeId AS a3_chromosomeId, a3_.chromosomeLocationId AS a3_chromosomeLocationId, a3_.confirmedByGenetics AS a3_confirmedByGenetics, a3_.confirmedByPCR AS a3_confirmedByPCR, a3_.cytoLocation AS a3_cytoLocation, a3_.element1Id AS a3_element1Id, a3_.element2Id AS a3_element2Id, a3_.id AS a3_id, a3_.length AS a3_length, a3_.name AS a3_name, a3_.organismId AS a3_organismId, a3_.primaryIdentifier AS a3_primaryIdentifier, a3_.score AS a3_score, a3_.scoreType AS a3_scoreType, a3_.secondaryIdentifier AS a3_secondaryIdentifier, a3_.sequenceId AS a3_sequenceId, a3_.sequenceOntologyTermId AS a3_sequenceOntologyTermId, a3_.symbol AS a3_symbol, intermine_default.dataSourceId AS a4_dataSourceId, intermine_default.description AS a4_description, intermine_default.id AS a4_id, intermine_default.name AS a4_name, intermine_default.publicationId AS a4_publicationId, intermine_default.url AS a4_url, intermine_default.version AS a4_version, intermine_default.id AS a7_ FROM precomp_190739 AS P20948, GOAnnotation AS P20956, ChromosomalDeletion AS a3_, DataSet AS intermine_default, GOTerm AS a6_, GeneGoAnnotation AS P20957, OverlappingFeaturesSequenceFeature AS indirect1, BioEntitiesDataSets AS indirect0 WHERE P20948.a1_id = P20957.Gene AND P20957.GoAnnotation = P20956.id AND P20948.a1_id = indirect1.SequenceFeature AND indirect1.OverlappingFeatures = a3_.id AND a3_.id = indirect0.BioEntities AND indirect0.DataSets = intermine_default.id AND P20956.ontologyTermId = a6_.id AND LOWER(P20948.a2_name) LIKE 'drosophila melanogaster' AND LOWER(a6_.name) LIKE 'gap junction' AND LOWER(intermine_default.name) LIKE 'drosdel p-element and deletion collection') AS a1_ GROUP BY a1_.a7_ ORDER BY COUNT(*) DESC, a1_.a7_ LIMIT 5000
bag tables: 0 ms, generate: 1 ms, optimise: 51 ms,  ms,  estimate: 0 ms, execute: 56 ms, convert results: 0 ms, extra queries: 0 ms, total: 108 ms, rows: 1
```

**Comment by julie-sullivan** [comment]
whoops Location table doesn't have the correct index.

```
flymine-beta-2015-jul-27=# \d location
        Table "public.location"
     Column      |  Type   | Modifiers
-----------------+---------+-----------
 intermine_start | integer |
 intermine_end   | integer |
 strand          | text    |
 id              | integer | not null
 featureid       | integer |
 locatedonid     | integer |
 class           | text    |
Indexes:
    "location_pkey" UNIQUE CONSTRAINT, btree (id)
    "location__end" btree (intermine_end)
    "location__feature" btree (featureid, id)
    "location__locatedon" btree (locatedonid, id)
    "location__start" btree (intermine_start)
    "location__strand_equals" btree (lower(strand))
    "location__strand_like" btree (lower(strand) text_pattern_ops)
```

HumanMine does, so I've done something wrong with FlyMine

```
humanmine-build=# \d location
        Table "public.location"
     Column      |  Type   | Modifiers
-----------------+---------+-----------
 intermine_start | integer |
 intermine_end   | integer |
 strand          | text    |
 id              | integer | not null
 featureid       | integer |
 locatedonid     | integer |
 class           | text    |
Indexes:
    "location_pkey" UNIQUE CONSTRAINT, btree (id)
    "location__end" btree (intermine_end)
    "location__feature" btree (featureid, id)
    "location__int4range" spgist (int4range(intermine_start, intermine_end))
    "location__key_all" btree (locatedonid, featureid, intermine_end, intermine_start, strand, id)
    "location__start" btree (intermine_start)
    "location__strand_equals" btree (lower(strand))
    "location__strand_like" btree (lower(strand) text_pattern_ops)
```

I've removed the extra postprocess here 94e81cc672ace38bc9d98ed468a820a2459220af

**Comment by julie-sullivan** [comment]
For some reason there are bad locations in FlyMine, where end > start. This caused the overlap index to silently fail and all overl

1. Update error message. Currently reads "Index location__int4range index already existed.org" Which is not accurate.

2. Fatal error when encountering a bad location. This is a data error. We need the locations to be correct, so the build should fail loudly.

> ERROR: range lower bound must be less than or equal to range upper bound

**Comment by julie-sullivan** [comment]
They all are length 1 which is a really small space between genes. 

This is for intergenic_region_chr211000022278309_1111..1110

```

flymine-beta-2015-jul-30=# select * from location where intermine_start > intermine_end;
 intermine_start | intermine_end | strand |    id     | featureid | locatedonid |              class               
-----------------+---------------+--------+-----------+-----------+-------------+----------------------------------
            1111 |          1110 | 1      | 218024510 | 218024509 |   112054956 | org.intermine.model.bio.Location
            1135 |          1134 | 1      | 218024528 | 218024527 |   112057052 | org.intermine.model.bio.Location
            1006 |          1005 | 1      | 218024534 | 218024533 |   112057759 | org.intermine.model.bio.Location
            1013 |          1012 | 1      | 218024610 | 218024609 |   113945555 | org.intermine.model.bio.Location
            1357 |          1356 | 1      | 218024616 | 218024615 |   114075668 | org.intermine.model.bio.Location
             314 |           313 | 1      | 218330186 | 218330185 |   120630399 | org.intermine.model.bio.Location
(6 rows)

```

**Comment by julie-sullivan** [comment]
Chromosome 211000022278309 has a length of 1110 so there are no intergenic regions at all. I'll update the code to fix this.

Also, I don't know if we should be storing 211000022278309 as a chromosome. I don't think that's right.

**Comment by julie-sullivan** [comment]
Now fails correctly:

```
Caused by: java.sql.SQLException: Failed to create location__int4range. You likely have bad locations. 
	at org.intermine.bio.postprocess.CreateLocationOverlapIndex.create(CreateLocationOverlapIndex.java:88)
	at org.intermine.bio.postprocess.PostProcessOperationsTask.execute(PostProcessOperationsTask.java:272)
	... 22 more
Caused by: org.postgresql.util.PSQLException: ERROR: range lower bound must be less than or equal to range upper bound
```
