### ISSUE TITLE
FlyMine: postprocess failed on UTR references

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1135]
```
Caused by: Operation was:create-utr-references
        at org.intermine.bio.postprocess.PostProcessOperationsTask.execute(PostProcessOperationsTask.java:232)
        ... 22 more
Caused by: java.lang.IllegalArgumentException: Couldn't set field "Transcript.fivePrimeUTR" to "FivePrimeUTR [chromosome=111000092, chromosomeLocation=182110596, cytoLocation=null, gene=null, id=182110597, length=22, name=null, organism=111000001, primaryIdentifier="FBtr0071388-5-prime-utr", score=null, scoreType=null, secondaryIdentifier=null, sequence=182110598, sequenceOntologyTerm=null, symbol=null]" (a org.intermine.model.bio.FivePrimeUTRShadow)
        at org.intermine.util.DynamicUtil.setFieldValue(DynamicUtil.java:164)
        at org.intermine.model.bio.TranscriptShadow.setFieldValue(TranscriptShadow.java:494)
        at org.intermine.bio.postprocess.CreateReferences.createUtrRefs(CreateReferences.java:405)
        at org.intermine.bio.postprocess.PostProcessOperationsTask.execute(PostProcessOperationsTask.java:120)
        ... 22 more
Caused by: java.lang.NullPointerException
        at org.intermine.util.DynamicUtil.setFieldValue(DynamicUtil.java:154)
        ... 25 more


```

**Comment by julie-sullivan** [comment]
fixed by f1d5a3475bddf22e9229f818bc052aed2dd53ba9
