### ISSUE TITLE
go-annotations data source throws java.lang.RuntimeException: class "org.intermine.model.bio.Publication" has no "crossReferences" collection

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1138]
This may be a bit more w.r.t. the tutorial, but since everything has gone so swimmingly with my InterMine build from a chado data source that I thought I'd post up this error when I try to integrate GO annotations using the go-annotation datasource (and yes I sorted the annotations file). BTW the GO ontology import went fine. Here's the stack trace:
```
-retrieve-tgt-from-custom-file:
[integrate] [main] INFO com.zaxxer.hikari.HikariDataSource - HikariCP pool db.common-tgt-items is starting.
[integrate] Processing file: /home/sam/NCGR/chado-drupal/GO/gene_association.goa_uniprot_noiea.sorted

BUILD FAILED
/home/sam/intermine/imbuild/integrate.xml:54: The following error occurred while executing this line:
/home/sam/intermine/imbuild/source.xml:145: java.lang.RuntimeException: class "org.intermine.model.bio.Publication" has no "crossReferences" collection
	at org.intermine.xml.full.Item.checkCollection(Item.java:507)
	at org.intermine.xml.full.Item.addCollection(Item.java:290)
	at org.intermine.bio.dataconversion.GoConverter.newPublication(GoConverter.java:638)
	at org.intermine.bio.dataconversion.GoConverter.process(GoConverter.java:234)
	at org.intermine.task.FileConverterTask.execute(FileConverterTask.java:116)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	at org.intermine.task.Integrate.performAction(Integrate.java:223)
	at org.intermine.task.Integrate.performAction(Integrate.java:135)
	at org.intermine.task.Integrate.execute(Integrate.java:127)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

**Comment by sammyjava** [comment]
And here's my project.xml for the record:
```
<project type="bio">
  <property name="target.model" value="genomic"/>
  <property name="source.location" location="../bio/sources/"/>
  <property name="common.os.prefix" value="common"/>
  <property name="intermine.properties.file" value="chadomine.properties"/>
  <property name="default.intermine.properties.file" location="../default.intermine.integrate.properties"/>

  <sources>

	<!-- import Uniprot protein data for our three species -->
	<source name="uniprot-organisms" type="uniprot">
	  <property name="uniprot.organisms" value="3821 3880 3885"/>
	  <property name="src.data.dir" location="/home/sam/NCGR/chado-drupal/uniprot/" />
	  <property name="createinterpro" value="true"/>
	  <property name="creatego" value="true"/>
	  <property name="allowduplicates" value="false"/>
	  <property name="loadfragments" value="false"/>
	  <property name="loadtrembl" value="true"/>
	</source>

	<!-- load chado data for one organism -->
	<source name="chado-db-3821" type="chado-db" dump="true">
	  <property name="source.db.name" value="chadoncgr"/>
	  <property name="organisms" value="3821"/>
	  <property name="dataSourceName" value="ChadoBase"/>
	  <property name="converter.class" value="org.intermine.bio.dataconversion.ChadoDBConverter"/>
	  <property name="processors" value="org.intermine.bio.dataconversion.SequenceProcessor org.intermine.bio.dataconversion.StockProcessor"/>
	</source>

	<!-- load chado data for one organism -->
	<source name="chado-db-3880" type="chado-db" dump="true">
	  <property name="source.db.name" value="chadoncgr"/>
	  <property name="organisms" value="3880"/>
	  <property name="dataSourceName" value="ChadoBase"/>
	  <property name="converter.class" value="org.intermine.bio.dataconversion.ChadoDBConverter"/>
	  <property name="processors" value="org.intermine.bio.dataconversion.SequenceProcessor org.intermine.bio.dataconversion.StockProcessor"/>
	</source>

	<!-- load chado data for one organism -->
	<source name="chado-db-3885" type="chado-db" dump="true">
	  <property name="source.db.name" value="chadoncgr"/>
	  <property name="organisms" value="3885"/>
	  <property name="dataSourceName" value="ChadoBase"/>
	  <property name="converter.class" value="org.intermine.bio.dataconversion.ChadoDBConverter"/>
	  <property name="processors" value="org.intermine.bio.dataconversion.SequenceProcessor org.intermine.bio.dataconversion.StockProcessor"/>
	</source>

	<!-- import GO ontology -->
	<source name="go" type="go">
	  <property name="src.data.file" location="/home/sam/NCGR/chado-drupal/GO/go-basic.obo"/>
	</source>

	<!-- import GO Uniprot annotation -->
	<source name="go-annotation" type="go-annotation">
	  <property name="ontologyfile" location="/home/sam/NCGR/chado-drupal/GO/gene_association.goa_uniprot_noiea.sorted"/>
	  <property name="src.data.dir" location="/home/sam/NCGR/chado-drupal/GO"/>
	</source>

	<!-- update pubs -->
    <source name="update-publications" type="update-publications">
      <property name="src.data.file" location="build/publications.xml"/>
    </source>

	<!-- update organism records so we can match organisms between the two databases -->
    <source name="entrez-organism" type="entrez-organism">
      <property name="src.data.file" location="build/organisms.xml"/>
    </source>

  </sources>

  <post-processing>

    <post-process name="create-references"/>
    <post-process name="transfer-sequences" dump="true"/>

    <!-- this runs the postprocessing steps in all sources -->
    <post-process name="do-sources"/>

    <post-process name="summarise-objectstore"/>
    <post-process name="create-autocomplete-index"/>
    <post-process name="create-search-index"/>

  </post-processing>

</project>
```

**Comment by julie-sullivan** [comment]
Hi  @sammyjava! Sorry you are having problems.

The error message I see says that it tried to add a `cross reference` to a `publication`, but failed because `publications` have no `cross references`.

`Publications` do have `xrefs`, here is the XML that specifies this:

https://github.com/intermine/intermine/blob/beta/bio/sources/go-annotation/go-annotation_additions.xml#L25-L27

The data model is built by merging together all the *_additions.xml files when you run a build. Is is possible you ran this source after already building the database? If so, a fix would be to do this:

1. run the `ant clean` target. 
    * removes the old compiled files that contain the old data model (where `publications` don't have `xrefs`)
2. run `ant build-db` in $MINE/dbmodel
    * rebuilds the database and the model. 
3. restart your build

Try that?
Julie

**Comment by julie-sullivan** [comment]
Also @sammyjava, you might find our developers mailing list helpful:

http://intermine.readthedocs.org/en/latest/support/mailing-list/

**Comment by sammyjava** [comment]
Yup, you got it, Julie. I was thinking that the MalariaMine tutorial config had added the appropriate additions to publications for go-annotations, but I have no idea why I was thinking that. :) I've joined the dev list -- I'll be getting pretty heavy into coding Chado data conversion processors, because we're building a bit InterMine for legumes off of Chado data in a Tripal database. I'll try to coordinate that with Kim Rutherford, who seems to be the chado integration dev. Thanks!
