### ISSUE TITLE
IntegrationWriterDataTrackingImplTest failing tests, sometimes.

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1150]
@sergiocontrino Can you help me look at this? It only happens once in a while, so some sort of race condition? 

```
BUILD SUCCESSFUL

Total time: 4 minutes 10 seconds

[Thread-98] INFO com.zaxxer.hikari.pool.HikariPool - HikariCP pool db.unittest is shutting down.

[Thread-96] INFO com.zaxxer.hikari.pool.HikariPool - HikariCP pool db.unittest is shutting down.

[Finalizer] INFO com.zaxxer.hikari.pool.HikariPool - HikariCP pool db.userprofile-test is shutting down.

[Thread-88] INFO com.zaxxer.hikari.pool.HikariPool - HikariCP pool db.unittest is shutting down.

CHECKING results

ERROR: Class org.intermine.dataloader.IntegrationWriterDataTrackingImplTest, method testUpdateObjectManyToOne

org.intermine.objectstore.ObjectStoreException: Error - could not fetch object with ID of 1000074 for query SELECT DISTINCT a1_ FROM org.intermine.model.testmodel.Manager AS a1_ WHERE (a1_.name = 'EmployeeA1')

	at org.intermine.objectstore.intermine.ResultsConverter.convert(ResultsConverter.java:204)

	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1236)

	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1131)

	at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.execute(ObjectStoreWriterInterMineImpl.java:1680)

	at org.intermine.objectstore.ObjectStoreAbstractImpl.getObjectByExample(ObjectStoreAbstractImpl.java:369)

	at org.intermine.dataloader.IntegrationWriterAbstractImpl.getObjectByExample(IntegrationWriterAbstractImpl.java:730)

	at org.intermine.dataloader.IntegrationWriterDataTrackingImplTest.testUpdateObjectManyToOne(IntegrationWriterDataTrackingImplTest.java:460)

	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)

	at junit.extensions.TestSetup$1.protect(TestSetup.java:23)

	at junit.extensions.TestSetup.run(TestSetup.java:27)

ERROR: Class org.intermine.dataloader.IntegrationWriterDataTrackingImplTest, method testUpdateObjectManyToOneNull

org.intermine.objectstore.ObjectStoreException: Error - could not fetch object with ID of 1000074 for query SELECT DISTINCT a1_ FROM org.intermine.model.testmodel.Manager AS a1_ WHERE (a1_.name = 'EmployeeA1')

	at org.intermine.objectstore.intermine.ResultsConverter.convert(ResultsConverter.java:204)

	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1236)

	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1131)

	at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.execute(ObjectStoreWriterInterMineImpl.java:1680)

	at org.intermine.objectstore.ObjectStoreAbstractImpl.getObjectByExample(ObjectStoreAbstractImpl.java:369)

	at org.intermine.dataloader.IntegrationWriterAbstractImpl.getObjectByExample(IntegrationWriterAbstractImpl.java:730)

	at org.intermine.dataloader.IntegrationWriterDataTrackingImplTest.testUpdateObjectManyToOneNull(IntegrationWriterDataTrackingImplTest.java:499)

	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)

	at junit.extensions.TestSetup$1.protect(TestSetup.java:23)

	at junit.extensions.TestSetup.run(TestSetup.java:27)

ERROR: Class org.intermine.dataloader.IntegrationWriterDataTrackingImplTest, method testUpdateObjectOneToMany

org.intermine.objectstore.ObjectStoreException: Error - could not fetch object with ID of 1000074 for query SELECT DISTINCT a1_ FROM org.intermine.model.testmodel.Manager AS a1_ WHERE (a1_.name = 'EmployeeA1')

	at org.intermine.objectstore.intermine.ResultsConverter.convert(ResultsConverter.java:204)

	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1236)

	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1131)

	at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.execute(ObjectStoreWriterInterMineImpl.java:1680)

	at org.intermine.objectstore.ObjectStoreAbstractImpl.getObjectByExample(ObjectStoreAbstractImpl.java:369)

	at org.intermine.dataloader.IntegrationWriterAbstractImpl.getObjectByExample(IntegrationWriterAbstractImpl.java:730)

	at org.intermine.dataloader.IntegrationWriterDataTrackingImplTest.testUpdateObjectOneToMany(IntegrationWriterDataTrackingImplTest.java:547)

	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)

	at junit.extensions.TestSetup$1.protect(TestSetup.java:23)

	at junit.extensions.TestSetup.run(TestSetup.java:27)

2232 tests were run

3 TESTS FAILED
```

**Comment by sergiocontrino** [comment]
this looks familiar: i think it is the error (or part of it) that travis was giving after the jars update (?) (the 'upper' travis build ?)

**Comment by julie-sullivan** [comment]
@sergiocontrino Yes, I've seen this error a couple times but only once in a while. I am worried that they were caused by #1096 or #1123 but because they only happen periodically I don't know.

When you restart the travis tests, they always pass the second time.

I looked at the tests and this is a merging issue, so it does worry me.

**Comment by julie-sullivan** [comment]
I think this has been fixed.
