### ISSUE TITLE
GO enrichment widget --  background change error

### ISSUE THREAD

**Issue by kkarra** [intermine/intermine#1164]
A user wrote to us about this bug.. I can replicate this in YeastMine and Flymine.
In Flymine:
- make a list of genes on 2L using one of the templates
- make the example list provided
- go to GO enrichment widget
- change default background to use the 2L genes list.

You will see this error in the browser:
Invalid JSON Response for Gene Ontology Enrichment
error is false; was expecting Null but got Service failed. Please contact support.
statusCode is false; was expecting HTTP code 200 but got 500

This is what I found in the logs:
12/10/15,11:22:43 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
callback: jQuery203007991247624158859_1444674141294
widget: go_enrichment_for_gene
list: list1
correction: Holm-Bonferroni
maxp: 0.05
token: g1a5S0Y5Cd11Dcsalbpc
errorCorrection: Holm-Bonferroni
pValue: 0.05
current_population: Gene list for S. cerevisiae 12 Oct 2015 10.32
remember_population: false
_: 1444674141300
java.util.UnknownFormatConversionException: Conversion = '$'

  at java.util.Formatter.checkText(Formatter.java:2503)
  at java.util.Formatter.parse(Formatter.java:2467)
  at java.util.Formatter.format(Formatter.java:2414)
  at java.util.Formatter.format(Formatter.java:2367)
  at java.lang.String.format(String.java:2769)
  at org.intermine.webservice.server.widget.EnrichmentWidgetResultService.execute(EnrichmentWidgetResultService.java:134)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.widget.WidgetsServlet.runService(WidgetsServlet.java:51)
  at org.intermine.webservice.server.widget.WidgetsServlet.doGet(WidgetsServlet.java:35)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)

**Comment by yochannah** [comment]
So, oddly, this was supposed to result in an error, just a more sane one. When I fix the $ interpolation issue, this is the result: 
![image](https://cloud.githubusercontent.com/assets/9271438/10454982/5e66eb46-71b0-11e5-9a53-3f11a5fda569.png)

**Comment by kkarra** [comment]
Thanks!
