### ISSUE TITLE
PDB failing

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1179]
```
[integrate] java.lang.NumberFormatException: For input string: "RIER"
[integrate] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[integrate] 	at java.lang.Integer.parseInt(Integer.java:492)
[integrate] 	at java.lang.Integer.valueOf(Integer.java:582)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser$JournalParser.<init>(PDBFileParser.java:2501)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.buildjournalArticle(PDBFileParser.java:2446)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.triggerEndFileChecks(PDBFileParser.java:2193)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:2107)
[integrate] 	at org.intermine.bio.dataconversion.PdbConverter.processPDBFile(PdbConverter.java:126)
[integrate] 	at org.intermine.bio.dataconversion.PdbConverter.process(PdbConverter.java:104)

**Comment by julie-sullivan** [comment]
It doesn't like the journal in file `1a27.pdb`:

```
JRNL        AUTH   C.MAZZA                                                      
JRNL        TITL   HUMAN TYPE I 17BETA-HYDROXYSTEROID DEHYDROGENASE: SITE       
JRNL        TITL 2 DIRECTED MUTAGENESIS AND X-RAY CRYSTALLOGRAPHY               
JRNL        TITL 3 STRUCTURE-FUNCTION ANALYSIS                                  
JRNL        REF    THESIS, UNIVERSITE JOSEPH                  1997              
JRNL        REF  2 FOURIER                                                      
JRNL        PUBL   GRENOBLE : UNIVERSITE JOSEPH FOURIER (THESIS)                
JRNL        REFN     
```

**Comment by julie-sullivan** [comment]
`1crm.pdb`

```
[integrate] file name 1crm.pdb
[integrate] null
[integrate] java.lang.NumberFormatException: For input string: "TION"
[integrate] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[integrate] 	at java.lang.Integer.parseInt(Integer.java:492)
[integrate] 	at java.lang.Integer.valueOf(Integer.java:582)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser$JournalParser.<init>(PDBFileParser.java:2501)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.buildjournalArticle(PDBFileParser.java:2446)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.triggerEndFileChecks(PDBFileParser.java:2193)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:2107)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:1963)
[integrate] 	at org.biojava.bio.structure.io.PDBFileReader.getStructure(PDBFileReader.java:486)
[integrate] 	at org.intermine.bio.dataconversion.PdbConverter.processPDBFile(PdbConverter.java:129)
[integrate] 	at org.intermine.bio.dataconversion.PdbConverter.process(PdbConverter.java:104)

```

Which has this text:

```
JRNL        AUTH   K.K.KANNAN                                                   
JRNL        TITL   STRUCTURE AND FUNCTION OF CARBONIC ANHYDRASES                
JRNL        EDIT   R.SRINIVASAN                                                 
JRNL        REF    BIOMOLECULAR STRUCTURE,       V.   1   165 1981              
JRNL        REF  2 CONFORMATION, FUNCTION AND                                   
JRNL        REF  3 EVOLUTION                                                    
JRNL        PUBL   PERGAMON PRESS, OXFORD                                       
JRNL        REFN  
```

**Comment by julie-sullivan** [comment]
I ignored those and got this error:

```
BUILD FAILED
/local-homes/julie/git/intermine/imbuild/integrate.xml:54: The following error occurred while executing this line:
/local-homes/julie/git/intermine/imbuild/source.xml:162: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
	at java.lang.StringBuffer.append(StringBuffer.java:237)
	at org.biojava.bio.structure.PDBHeader.printTitle(PDBHeader.java:249)
	at org.biojava.bio.structure.PDBHeader.toPDB(PDBHeader.java:105)
	at org.biojava.bio.structure.io.FileConvert.toPDB(FileConvert.java:196)
	at org.biojava.bio.structure.StructureImpl.toPDB(StructureImpl.java:559)
	at org.intermine.bio.dataconversion.PdbConverter.processPDBFile(PdbConverter.java:170)
	at org.intermine.bio.dataconversion.PdbConverter.process(PdbConverter.java:104)

```

**Comment by julie-sullivan** [comment]
And a bunch of these:

```
[integrate] Oct 21, 2015 1:17:58 PM org.biojava.bio.structure.StructureTools get1LetterCode
[integrate] WARNING: unknown group name MSE
[integrate] Oct 21, 2015 1:17:59 PM org.biojava.bio.structure.StructureTools get1LetterCode
[integrate] WARNING: unknown group name PTR
[integrate] Oct 21, 2015 1:17:59 PM org.biojava.bio.structure.StructureTools get1LetterCode
[integrate] WARNING: unknown group name ZAL
[integrate] Oct 21, 2015 1:17:59 PM org.biojava.bio.structure.StructureTools get1LetterCode
[integrate] WARNING: unknown group name AR0
[integrate] Oct 21, 2015 1:17:59 PM org.biojava.bio.structure.StructureTools get1LetterCode
[integrate] WARNING: unknown group name ALC
[integrate] Oct 21, 2015 1:17:59 PM org.biojava.bio.structure.StructureTools get1LetterCode
[integrate] WARNING: unknown group name DGL

```

**Comment by julie-sullivan** [comment]
```
[integrate] Hetatom null DGL false 17 does not align with Hetatom 64 ALC trueatoms: 11 16
[integrate] org.biojava.bio.structure.StructureException: could not match residues
[integrate] 	at org.biojava.bio.structure.io.SeqRes2AtomAligner.mapChains(SeqRes2AtomAligner.java:330)
[integrate] 	at org.biojava.bio.structure.io.SeqRes2AtomAligner.align(SeqRes2AtomAligner.java:264)
[integrate] 	at org.biojava.bio.structure.io.SeqRes2AtomAligner.align(SeqRes2AtomAligner.java:152)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.triggerEndFileChecks(PDBFileParser.java:2207)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:2107)
[integrate] 	at org.biojava.bio.structure.io.PDBFileParser.parsePDBFile(PDBFileParser.java:1963)
[integrate] 	at org.biojava.bio.structure.io.PDBFileReader.getStructure(PDBFileReader.java:486)
[integrate] 	at org.intermine.bio.dataconversion.PdbConverter.processPDBFile(PdbConverter.java:127)
[integrate] 	at org.intermine.bio.dataconversion.PdbConverter.process(PdbConverter.java:104)
[integrate] 	at org.intermine.task.DirectoryConverterTask.execute(DirectoryConverterTask.java:104)
```

**Comment by julie-sullivan** [comment]
@rachellyne I made a bug report with biojava, but we are getting an "out of memory" issue when we try to parse PDB files. Leaving for now
