### ISSUE TITLE
Postgres warning - connection closed

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1180]
```
[ajp-bio-8009-exec-13765] WARN com.zaxxer.hikari.proxy.ConnectionProxy - Connection org.postgresql.jdbc4.Jdbc4Connection@5f6c33ee (HikariPool-0) marked as broken because of SQLSTATE(08003), ErrorCode(0).
org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:837)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.prepareStatement(AbstractJdbc3Connection.java:275)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.prepareStatement(AbstractJdbc2Connection.java:311)
        at com.zaxxer.hikari.proxy.ConnectionProxy.prepareStatement(ConnectionProxy.java:268)
        at com.zaxxer.hikari.proxy.ConnectionJavassistProxy.prepareStatement(ConnectionJavassistProxy.java)
        at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.performUnsafeOperation(ObjectStoreInterMineImpl.java:284)
        at org.intermine.api.bag.SharedBagManager.getSharedBags(SharedBagManager.java:174)
        at org.intermine.api.bag.BagManager.getBags(BagManager.java:389)
        at org.intermine.api.bag.BagManager.getCurrentBags(BagManager.java:405)
```

**Comment by julie-sullivan** [comment]
restarting tomcat fixed this issue. on postgres 9.4

**Comment by julie-sullivan** [comment]
beta flymine just now:

```
2015-10-23 13:57:16 ERROR org.intermine.api.tracker.track.TrackAbstract     - Problem executing the statement: INSERT INTO searchtrack VALUES ( '*kinase*','','E27CC69B5885F07C756EB4071452365E','2015-10-23 13:57:16.405')
org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)

```

**Comment by julie-sullivan** [comment]
Can't log in:

```
[ajp-nio-8009-exec-217] WARN com.zaxxer.hikari.proxy.ConnectionProxy - Connection org.postgresql.jdbc4.Jdbc4Connection@3bf4c713 (HikariPool-0) marked as broken because of SQLSTATE(08003), ErrorCode(0).
org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:837)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.getAutoCommit(AbstractJdbc2Connection.java:798)
        at com.zaxxer.hikari.proxy.ConnectionJavassistProxy.getAutoCommit(ConnectionJavassistProxy.java)
        at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.createTempBagTables(ObjectStoreInterMineImpl.java:1421)
        at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1160)
        at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1131)
        at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.execute(ObjectStoreWriterInterMineImpl.java:1691)
        at org.intermine.objectstore.ObjectStoreAbstractImpl.getObjectByExample(ObjectStoreAbstractImpl.java:369)
        at org.intermine.api.profile.ProfileManager.getUserProfile(ProfileManager.java:911)
        at org.intermine.api.profile.ProfileManager.hasProfile(ProfileManager.java:245)
        at org.intermine.web.struts.LoginForm.validate(LoginForm.java:101)
        at org.apache.struts.action.RequestProcessor.processValidate(RequestProcessor.java:950)
        at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:198)
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)

```

**Comment by julie-sullivan** [comment]
hasn't happened again don't know what that was
