### ISSUE TITLE
Web service: /list/tags doesn't work

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1222]
From @JoelRichardson 

http://iodocs.labs.intermine.org/flymine-beta/docs#/ws-list-tags/GET/list/tags

* list tags are broken now - https://github.com/intermine/intermine/issues/1182
* List Tags service, the GET all option (where no list is specified) returns an empty list.

**Comment by julie-sullivan** [comment]
Error in logs:

```
2015-11-13 15:41:11 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
format: json
org.intermine.api.profile.UserNotFoundException: User __ANONYMOUS_USER__ doesn't exist

  at org.intermine.api.profile.TagManager.checkUserExists(TagManager.java:96)
  at org.intermine.api.profile.TagManager.getTags(TagManager.java:413)
  at org.intermine.api.profile.TagManager.getUserTagNames(TagManager.java:255)
  at org.intermine.api.profile.TagManager.getUserTagNames(TagManager.java:235)
  at org.intermine.webservice.server.lists.ListTagService.getAllTags(ListTagService.java:88)
  at org.intermine.webservice.server.lists.ListTagService.execute(ListTagService.java:64)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.core.WebServiceServlet.respond(WebServiceServlet.java:73)
  at org.intermine.webservice.server.core.WebServiceServlet.doGet(WebServiceServlet.java:114)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
```
