### ISSUE TITLE
List upload: error

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1248]
```
java.lang.NullPointerException
	at org.intermine.web.struts.BagBuildController.execute(BagBuildController.java:136)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
```

**Comment by julie-sullivan** [comment]
I redeployed and now it works. I believe this is because I switched branches a bunch of times prior to this, and hadn't done a clean. user error.
