### ISSUE TITLE
Web service: error running template to list

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1253]
From @JoelRichardson 

```
2015-12-03 15:42:50 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
name: Gene_Orth
path: Gene.homologues.homologue.id
listName: nonnewname
replaceExisting: true
constraint1: Gene
op1: LOOKUP
value1: cdc2
code1: A
extra1: D. melanogaster
java.lang.UnsupportedOperationException

  at java.util.Collections$UnmodifiableCollection.remove(Collections.java:1078)
  at org.intermine.webservice.server.template.TemplateToListService.getQuery(TemplateToListService.java:116)
  at org.intermine.webservice.server.query.QueryToListService.execute(QueryToListService.java:92)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.core.WebServiceServlet.respond(WebServiceServlet.java:73)
  at org.intermine.webservice.server.core.WebServiceServlet.doGet(WebServiceServlet.java:114)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)

```

**Comment by julie-sullivan** [comment]
I fixed that error then got this error:

```
51827 [ajp-nio-8009-exec-39] ERROR org.intermine.webservice.server.WebService  - Service failed by internal error. Request parameters: 
name: Gene_Orth
path: Gene.homologues.homologue.id
constraint1: Gene
op1: LOOKUP
value1: cdc2
code1: A
extra1: D. melanogaster
java.lang.IllegalArgumentException: Query has incorrect number of SELECT elements.

  at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.addToBagFromQuery(ObjectStoreWriterInterMineImpl.java:1195)
  at org.intermine.api.profile.InterMineBag.addToBagFromQuery(InterMineBag.java:786)
  at org.intermine.webservice.server.query.QueryToListService.generateListFromQuery(QueryToListService.java:154)
  at org.intermine.webservice.server.query.QueryToListService.execute(QueryToListService.java:95)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.core.WebServiceServlet.respond(WebServiceServlet.java:73)
  at org.intermine.webservice.server.core.WebServiceServlet.doGet(WebServiceServlet.java:114)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
```
I don't think this ever worked.
