### ISSUE TITLE
result table unable to display 'NaN' values (was: Template results produce error when row count is very large.)

### ISSUE THREAD

**Issue by joshkh** [intermine/intermine#1266]
Running template
http://intermine.modencode.org/thalemineval/template.do?name=gene_expression_report

With list "democyto266"
## QUERY:

STACK: TypeError: Cannot read property 'column' of null
at http://cdn-dev.intermine.org/js/intermine/im-tables/2.0.0/imtables.js:6007:37
at http://cdn-dev.intermine.org/js/intermine/im-tables/2.0.0/imtables.js:21496:31
at http://cdn-dev.intermine.org/js/intermine/im-tables/2.0.0/imtables.js:21499:15
at Array.map (native)
at Table.module.exports.Table.fillRowsCollection (http://cdn-dev.intermine.org/js/intermine/im-tables/2.0.0/imtables.js:21484:21)
at http://cdn-dev.intermine.org/js/intermine/im-tables/2.0.0/imtables.js:21475:24
at lib$es6$promise$$internal$$tryCatch (http://cdn-dev.intermine.org/js/intermine/imjs/3.15.0/im.js:6264:16)
at lib$es6$promise$$internal$$invokeCallback (http://cdn-dev.intermine.org/js/intermine/imjs/3.15.0/im.js:6276:17)
at lib$es6$promise$$internal$$publish (http://cdn-dev.intermine.org/js/intermine/imjs/3.15.0/im.js:6247:11)
at MutationObserver.lib$es6$promise$asap$$flush (http://cdn-dev.intermine.org/js/intermine/imjs/3.15.0/im.js:6058:9)

**Comment by julie-sullivan** [comment]
@sergiocontrino Is there anything the log files? Also, this doesn't happen with other templates. What's different about this one?

This template works:

http://intermine.modencode.org/thalemineval/template.do?name=ge_agnes&scope=all

And it looks identical. Why is that? 

I doubt this is a front end problem.

**Comment by julie-sullivan** [comment]
@sergiocontrino I've reassigned to you, let me know if you need help debugging.

Good template:

```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.probes.expressions.sample.experiment.title Gene.probes.expressions.signal Gene.probes.expressions.averageSignal Gene.probes.expressions.averageControl Gene.probes.expressions.averageRatio Gene.probes.expressions.sample.experiment.category Gene.probes.name Gene.probes.expressions.sample.name" longDescription="original query" sortOrder="Gene.probes.expressions.sample.experiment.title asc" constraintLogic="A and B and C and D">
  <constraint path="Gene" code="A" op="LOOKUP" value="FT" extraValue="A. thaliana"/>
  <constraint path="Gene.probes.expressions.sample.experiment.title" code="B" op="=" value="ABA time course in wildtype seedlings"/>
  <constraint path="Gene.probes.expressions.sample.type" code="C" op="=" value="treatment"/>
  <constraint path="Gene.probes.expressions.averageRatio" code="D" op="&gt;" value="0.5"/>
</query>
```

Bad template

```
<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.probes.expressions.sample.experiment.title Gene.probes.expressions.averageRatio Gene.probes.expressions.signal Gene.probes.expressions.averageSignal Gene.probes.expressions.averageControl Gene.probes.name Gene.probes.expressions.sample.name" longDescription="Displays the expressions for treatment samples ordered by average ratio." sortOrder="Gene.probes.expressions.averageRatio desc" constraintLogic="A and B">
  <constraint path="Gene" code="A" op="LOOKUP" value="ft" extraValue="A. thaliana"/>
  <constraint path="Gene.probes.expressions.sample.type" code="B" op="=" value="treatment"/>
</query>
```

**Comment by sergiocontrino** [comment]
@joshkh, @julie-sullivan was right, it is a data issue.

**Comment by sergiocontrino** [comment]
the error is due to imtable being unable to display NaN values in a number fields.
i'll try to avoid them in the loading, but reopen this for reference. if a quick fix is possible (treat them as null? or 0?) even better!

**Comment by sergiocontrino** [comment]
i think this happens only in thalemine, where we compute some values.
for example, in thalemineval
```
 SELECT a1_.id AS a1_id, a5_.id AS a5_id, a3_.id AS a3_id, a2_.id AS a2_id, a4_.id AS a4_id, a5_.title AS orderbyfield1, a1_.primaryIdentifier AS orderbyfield2, a1_.symbol AS orderbyfield3, a3_.averageRatio AS orderbyfield4, a3_.signal AS orderbyfield5, a3_.averageSignal AS orderbyfield6, a3_.averageControl AS orderbyfield7, a2_.name AS orderbyfield8, a4_.name AS orderbyfield9 FROM Gene AS a1_, Probe AS a2_, Expression AS a3_, Sample AS a4_, Experiment AS a5_, GenesProbes AS indirect0 WHERE a1_.id = indirect0.Genes AND indirect0.Probes = a2_.id AND a2_.id = a3_.probeId AND a3_.sampleId = a4_.id AND a4_.experimentId = a5_.id AND a1_.id IN (1016110) AND LOWER(a4_.type) LIKE 'treatment' AND LOWER(a2_.name) LIKE E'256136\\_s\\_at' AND LOWER(a4_.name) LIKE E'atgen\\_d-47\\_3-us\\_rep3\\_ath1' ORDER BY a5_.title, a1_.primaryIdentifier, a1_.symbol, a3_.averageRatio, a3_.signal, a3_.averageSignal, a3_.averageControl, a2_.name, a4_.name, a1_.id, a5_.id, a3_.id, a2_.id, a4_.id
```
produces a record with the 'NaN' value.

or in the db you can
```
aradc18b=> select distinct g.primaryidentifier, g.symbol, e.averageRatio from probe p, expression e, genesprobes x, gene g
where p.id = e.probeid
and x.probes = p.id
and g.id = x.genes
and e.averageRatio > 50000
;
```

and obtain 
```
 primaryidentifier |  symbol   | averageratio 
-------------------+-----------+--------------
 AT3G55720         | AT3G55720 |       161191
 AT1G28330         | DYL1      |        55908
 AT5G66390         | AT5G66390 |       908984
 AT3G55720         | AT3G55720 |       171899
 AT1G12950         | RSH2      |       475917
 AT1G12950         | RSH2      |       105364
 AT5G66390         | AT5G66390 |      4270480
 AT1G05660         | AT1G05660 |       547484
 AT2G16365         | AT2G16365 |          NaN
 AT1G54300         | AT1G54300 |          NaN
 AT3G55720         | AT3G55720 |        77105
 AT3G55720         | AT3G55720 |        68280
 AT4G16010         | AT4G16010 |          NaN
 AT1G05660         | AT1G05660 |     148200.6
 AT1G05650         | AT1G05650 |      52575.2
 AT5G66390         | AT5G66390 |       187644
 AT5G66390         | AT5G66390 |      3798430
 AT3G55720         | AT3G55720 |       148307
 AT3G55720         | AT3G55720 |       146345
 AT1G05660         | AT1G05660 |       683876
 AT2G16290         | AT2G16290 |          NaN
 AT1G12950         | RSH2      |       983474
 AT5G66390         | AT5G66390 |       962985
 AT3G60650         | AT3G60650 |       511090
 AT3G55720         | AT3G55720 |       368752
 AT1G80100         | HP6       |          NaN
 AT1G12950         | RSH2      |        64377
 AT5G09530         | PELPK1    |    108141.61
 AT1G05660         | AT1G05660 |       590898
 AT5G49590         | AT5G49590 |          NaN
 AT2G15190         | AT2G15190 |          NaN
 AT1G12950         | RSH2      |       313625
 AT5G66390         | AT5G66390 |        56160
 AT1G12950         | RSH2      |       105788
 AT1G28330         | DYL1      |        55073
 AT1G12950         | RSH2      |        70120
 AT4G23920         | UGE2      |        59424
 AT1G28330         | DYL1      |        51464
 AT1G05660         | AT1G05660 |       227064
 AT3G11550         | CASP2     |          NaN
 AT5G66390         | AT5G66390 |       256185
 AT4G11320         | AT4G11320 |          NaN
 AT1G12950         | RSH2      |       212131
 AT3G60650         | AT3G60650 |        61854
 AT4G23920         | UGE2      |      1214036
 AT1G11265         | AT1G11265 |          NaN
 AT5G66390         | AT5G66390 |       205919
 AT1G12950         | RSH2      |        50987
 AT4G11310         | AT4G11310 |          NaN
 AT5G30545         | AT5G30545 |          NaN
 AT1G18510         | TET16     |          NaN
 AT5G66390         | AT5G66390 |       330540
 AT5G66390         | AT5G66390 |        74880
 AT3G55720         | AT3G55720 |       822101
 AT3G27980         | AT3G27980 |          NaN
 AT3G15490         | AT3G15490 |          NaN
 AT1G12950         | RSH2      |      1725930
 AT3G55720         | AT3G55720 |       131333
 AT1G58150         | AT1G58150 |          NaN
 AT1G12950         | RSH2      |        80125
 AT5G66390         | AT5G66390 |       175088
 AT4G38080         | AT4G38080 |     86305.28
 AT4G07800         | AT4G07800 |          NaN
 AT3G55720         | AT3G55720 |        88988
 AT5G66390         | AT5G66390 |      2532290
 AT1G12950         | RSH2      |       568896
 AT1G21060         | AT1G21060 |          NaN
 AT2G10400         | AT2G10400 |          NaN
 AT5G66390         | AT5G66390 |     13927600
 AT1G12950         | RSH2      |       103376
 AT3G55720         | AT3G55720 |       103465
 AT5G66390         | AT5G66390 |       196579
 AT1G48710         | AT1G48710 |          NaN
 AT1G56600         | GolS2     |        86860
 AT3G55720         | AT3G55720 |       223844
 AT1G28330         | DYL1      |        96638
 AT3G55720         | AT3G55720 |       252775
 AT1G28330         | DYL1      |       114409
 AT5G36190         | AT5G36190 |          NaN
 AT1G28330         | DYL1      |       443316
 AT5G19530         | ACL5      |          NaN
 AT5G66390         | AT5G66390 |        83917
 AT3G63440         | CKX6      |          NaN
 AT1G12950         | RSH2      |       243084
 AT3G55720         | AT3G55720 |       479765
 AT1G12950         | RSH2      |       131590
 AT5G66390         | AT5G66390 |       633072
 AT1G12950         | RSH2      |       324170
 AT1G52190         | AT1G52190 |          NaN
 AT3G60650         | AT3G60650 |       717824
 AT1G12950         | RSH2      |        62981
 AT1G56600         | GolS2     |        52420
 AT1G05650         | AT1G05650 |       227064
 AT1G12950         | RSH2      |       367460
 AT3G25710         | BHLH32    |          NaN
 AT5G66390         | AT5G66390 |     15658400
 AT3G56540         | AT3G56540 |          NaN
 AT4G23920         | UGE2      |        53934
 AT5G66390         | AT5G66390 |       262632
 AT1G12950         | RSH2      |        92317
 AT1G05650         | AT1G05650 |       590898
 AT1G48720         | AT1G48720 |          NaN
 AT3G55720         | AT3G55720 |       199009
 AT1G05650         | AT1G05650 |       683876
 AT1G56600         | GolS2     |       105565
 AT1G62670         | RPF2      |          NaN
 AT3G55720         | AT3G55720 |        78803
 AT3G55720         | AT3G55720 |       119410
 AT1G05660         | AT1G05660 |      52575.2
 AT1G05650         | AT1G05650 |     148200.6
 AT5G66390         | AT5G66390 |       104581
 AT1G54540         | AT1G54540 |     76956.21
 AT1G12950         | RSH2      |       835202
 AT5G66390         | AT5G66390 |       867666
 AT1G12950         | RSH2      |       219884
 AT3G55720         | AT3G55720 |       699890
 AT5G66390         | AT5G66390 |        68340
 AT1G12950         | RSH2      |        54349
 AT3G52770         | ZPR3      |          NaN
 AT3G13250         | AT3G13250 |          NaN
 AT3G19780         | AT3G19780 |          NaN
 AT5G66390         | AT5G66390 |       102509
 AT5G66390         | AT5G66390 |       350176
 AT1G12950         | RSH2      |       751108
 AT1G05650         | AT1G05650 |       547484
 AT2G05090         | AT2G05090 |          NaN
 AT1G54540         | AT1G54540 |     64865.23
 AT3G55720         | AT3G55720 |       563539
 AT1G28330         | DYL1      |       346143
 AT2G26700         | PID2      |          NaN
 AT1G43980         | AT1G43980 |          NaN
 AT1G56600         | GolS2     |       508957
 AT1G05660         | AT1G05660 |       126311
 AT2G32630         | AT2G32630 |          NaN
 AT4G28410         | AT4G28410 |          NaN
 AT3G55720         | AT3G55720 |        54171
 AT2G16200         | AT2G16200 |          NaN
 AT5G66390         | AT5G66390 |       375868
 AT5G66390         | AT5G66390 |       341580
 AT5G13205         | AT5G13205 |          NaN
 AT2G16300         | AT2G16300 |          NaN
 AT4G34970         | ADF9      |      56464.5
 AT1G56600         | GolS2     |       141530
 AT1G05650         | AT1G05650 |        81244
 AT3G55720         | AT3G55720 |        78582
 AT5G66390         | AT5G66390 |       247905
 AT1G56600         | GolS2     |       155100
 AT1G28330         | DYL1      |       331969
 AT1G12950         | RSH2      |        55767
 AT1G05650         | AT1G05650 |      75275.2
 AT1G28330         | DYL1      |       305437
 AT1G51000         | AT1G51000 |          NaN
 AT1G05660         | AT1G05660 |       633634
 AT3G45360         | AT3G45360 |          NaN
 AT1G11290         | CRR22     |          NaN
 AT1G12950         | RSH2      |       146322
 AT1G32450         | NRT1.5    |          NaN
 AT1G56600         | GolS2     |       114840
 AT2G01390         | EMB3111   |          NaN
 AT3G55720         | AT3G55720 |       326548
 AT5G66390         | AT5G66390 |     13294500
 AT1G12950         | RSH2      |       302373
 AT2G29650         | PHT4;1    |          NaN
 AT1G56600         | GolS2     |        53256
 AT1G05660         | AT1G05660 |       245070
 AT1G12950         | RSH2      |       427998
 AT1G05650         | AT1G05650 |        69066
 AT1G28330         | DYL1      |       239704
 AT1G56600         | GolS2     |       553673
 AT1G12950         | RSH2      |        51754
 AT3G55720         | AT3G55720 |       227995
 AT2G01360         | AT2G01360 |          NaN
 AT5G28070         |           |          NaN
 AT3G55720         | AT3G55720 |        63630
 AT5G66390         | AT5G66390 |      5693980
 AT3G42090         | AT3G42090 |          NaN
 AT1G05650         | AT1G05650 |      79933.8
 AT1G12950         | RSH2      |       385882
 AT3G55720         | AT3G55720 |       330638
 AT4G07760         | AT4G07760 |          NaN
 AT1G28330         | DYL1      |       161597
 AT1G05660         | AT1G05660 |     137312.6
 AT5G66390         | AT5G66390 |       196559
 AT2G47860         | SETH6     |          NaN
 AT1G12950         | RSH2      |       319992
 AT5G09480         | AT5G09480 |     91650.93
 AT3G55720         | AT3G55720 |       657333
 AT3G55720         | AT3G55720 |       339190
 AT3G55720         | AT3G55720 |       281487
 AT1G12950         | RSH2      |        67604
 AT3G52020         | scpl39    |          NaN
 AT4G23920         | UGE2      |      65849.2
 AT3G59720         | AT3G59720 |          NaN
 AT3G55720         | AT3G55720 |       168899
 AT3G63445         | AT3G63445 |          NaN
 AT5G66390         | AT5G66390 |      2846990
 AT1G56600         | GolS2     |        68790
 AT3G05770         | AT3G05770 |          NaN
 AT1G28330         | DYL1      |       471498
 AT1G58140         | AT1G58140 |          NaN
 AT5G59060         | AT5G59060 |          NaN
 AT1G28330         | DYL1      |       229889
 AT4G38080         | AT4G38080 |    252796.63
 AT1G56600         | GolS2     |       106513
 AT1G12950         | RSH2      |       136486
 AT5G27480         | AT5G27480 |          NaN
 AT1G28330         | DYL1      |       306997
 AT1G28330         | DYL1      |        68040
 AT1G05650         | AT1G05650 |     137312.6
 AT2G03160         | SK19      |          NaN
 AT3G57180         | BPG2      |          NaN
 AT5G66390         | AT5G66390 |       919213
 AT1G62400         | HT1       |          NaN
 AT1G12950         | RSH2      |       117632
 AT1G28330         | DYL1      |       111906
 AT3G31955         | AT3G31955 |          NaN
 AT4G21340         | B70       |          NaN
 AT3G55720         | AT3G55720 |       120124
 AT2G12390         | AT2G12390 |          NaN
 AT1G28330         | DYL1      |        52566
 AT1G28330         | DYL1      |        70945
 AT1G33850         | AT1G33850 |          NaN
 AT5G66390         | AT5G66390 |       170790
 AT4G37650         | SHR       |          NaN
 AT1G28330         | DYL1      |        54736
 AT1G34510         | AT1G34510 |     66020.47
 AT1G28330         | DYL1      |        90862
 AT5G66390         | AT5G66390 |       165270
 AT5G66390         | AT5G66390 |        71483
 AT1G05660         | AT1G05660 |      79933.8
 AT1G56600         | GolS2     |        94491
 AT1G12950         | RSH2      |       209387
 AT2G10490         | AT2G10490 |          NaN
 AT4G16020         | AT4G16020 |          NaN
 AT5G66390         | AT5G66390 |       711747
 AT1G05660         | AT1G05660 |        69066
 AT3G30440         | AT3G30440 |          NaN
 AT1G21945         | AT1G21945 |          NaN
 AT5G66390         | AT5G66390 |       136679
 AT1G56600         | GolS2     |        63234
 AT5G57220         | CYP81F2   |    171329.11
 AT1G56600         | GolS2     |       188894
 AT5G66390         | AT5G66390 |      5064580
 AT5G66390         | AT5G66390 |       211059
 AT3G42930         | AT3G42930 |          NaN
 AT1G12950         | RSH2      |        69922
 AT1G28330         | DYL1      |        57115
 AT1G56530         | AT1G56530 |          NaN
 AT1G05650         | AT1G05650 |       245070
 AT5G66390         | AT5G66390 |     14946700
 AT1G28330         | DYL1      |        79228
 AT3G47260         | AT3G47260 |          NaN
 AT1G05650         | AT1G05650 |       633634
 AT1G12950         | RSH2      |        66772
 AT3G61330         | AT3G61330 |          NaN
 AT4G23920         | UGE2      |     121011.2
 AT5G66390         | AT5G66390 |       896647
 AT5G44330         | AT5G44330 |          NaN
 AT1G28330         | DYL1      |       326513
 AT3G55720         | AT3G55720 |       198391
 AT5G66390         | AT5G66390 |        53613
 AT1G05660         | AT1G05660 |        81244
 AT1G05660         | AT1G05660 |      75275.2
 AT1G12950         | RSH2      |       151767
 AT1G12950         | RSH2      |       102653
 AT5G09530         | PELPK1    |      92608.7
 AT3G55720         | AT3G55720 |       494816
 AT3G31403         | AT3G31403 |          NaN
 AT1G05650         | AT1G05650 |       126311
 AT2G40790         | CXXS2     |          NaN
 AT5G66390         | AT5G66390 |       939345
 AT3G55720         | AT3G55720 |       106376
 AT1G12950         | RSH2      |        99667
 AT3G60650         | AT3G60650 |        56967
 AT3G55720         | AT3G55720 |       267807
 AT5G66390         | AT5G66390 |       358783
 AT2G01530         | MLP329    |          NaN
(277 rows)

```

note that 'NaN' is a upper limit and that you can use it as a value, e.g. 
```
select distinct g.primaryidentifier, g.symbol from probe p, expression e, genesprobes x, gene g
where p.id = e.probeid
and x.probes = p.id
and g.id = x.genes
and e.averageRatio = 'NaN'
;
```

**Comment by julie-sullivan** [comment]
@sergiocontrino Can I close this ticket?

**Comment by sergiocontrino** [comment]
yes, let's close it. data is fixed.
