### ISSUE TITLE
Java 8 - Duplicate default methods 

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1343]
`Duplicate default methods named spliterator with the parameters () and () are inherited from the types List<Object> and Set<Object>`

In Results.java (and therefore SingletonResults.java too)

**Comment by julie-sullivan** [comment]
If the fix for this is not backwards compatible, let's save it for InterMine 2.0.

**Comment by julie-sullivan** [comment]
@sammyjava Reports this issue

```
This update (I'm pretty sure it's this one of the May 12 updates) has broken SequenceProcessor in chado-db, a variation of which I use. I've reverted back to April 26 14:07:28 (Julie: footer tweaks) and this problem goes away; I pulled back to May 12 16:52:32 (Julie: merge Java 8) and my data source throws the following stack trace during integration of data into the production database:

     [echo] 
     [echo]       Loading chado-genomics (legfed-chado-db) tgt items into production DB
     [echo]     
[integrate] [main] INFO com.zaxxer.hikari.HikariDataSource - HikariCP pool db.production is starting.
[integrate] [main] INFO com.zaxxer.hikari.HikariDataSource - HikariCP pool db.common-tgt-items is starting.
[integrate] Creating index: CREATE INDEX Chromosome__key_primaryidentifier ON Chromosome (primaryIdentifier)
[integrate] Creating index: CREATE INDEX Organism__key_taxonid ON Organism (taxonId)
[integrate] Creating index: CREATE INDEX Ontology__key_name ON Ontology (name)
[integrate] Creating index: CREATE INDEX PolypeptideDomain__key_primaryidentifier ON PolypeptideDomain (primaryIdentifier)
[integrate] Creating index: CREATE INDEX SOTerm__key_name ON SOTerm (name)
[integrate] Creating index: CREATE INDEX OntologyTerm__key_name ON OntologyTerm (name)
[integrate] Creating index: CREATE INDEX GeneticMarker__key_primaryidentifier ON GeneticMarker (primaryIdentifier, organismid)
[integrate] Creating index: CREATE INDEX ConsensusRegion__key_primaryidentifier ON ConsensusRegion (primaryIdentifier)

BUILD FAILED
/home/intermine/intermine/imbuild/integrate.xml:54: The following error occurred while executing this line:
/home/intermine/intermine/imbuild/source.xml:330: java.lang.RuntimeException: java.lang.ClassCastException: org.intermine.objectstore.query.SingletonResults cannot be cast to java.util.Set
    at org.intermine.dataconversion.ItemToObjectTranslator.translateFromDbObject(ItemToObjectTranslator.java:418)
    at org.intermine.objectstore.translating.ObjectStoreTranslatingImpl.execute(ObjectStoreTranslatingImpl.java:167)
    at org.intermine.objectstore.fastcollections.ObjectStoreFastCollectionsForTranslatorImpl.execute(ObjectStoreFastCollectionsForTranslatorImpl.java:193)
    at org.intermine.dataloader.BatchingFetcher$NoseyObjectStore.execute(BatchingFetcher.java:580)
    at org.intermine.objectstore.query.ResultsBatches.fetchBatchFromObjectStore(ResultsBatches.java:193)
    at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:241)
    at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:236)
    at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:146)
    at org.intermine.objectstore.query.ResultsBatches.getBatch(ResultsBatches.java:164)
    at org.intermine.objectstore.query.ResultsBatches.getRowsFromBatch(ResultsBatches.java:139)
    at org.intermine.objectstore.query.Results.range(Results.java:197)
    at org.intermine.objectstore.query.SingletonResults.range(SingletonResults.java:65)
    at org.intermine.objectstore.query.Results.get(Results.java:226)
    at org.intermine.objectstore.query.Results$Iter.hasNext(Results.java:378)
    at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:135)
    at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:60)
    at org.intermine.dataloader.ObjectStoreDataLoaderTask.execute(ObjectStoreDataLoaderTask.java:128)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:390)
    at org.apache.tools.ant.Target.performTasks(Target.java:411)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
    at org.intermine.task.Integrate.performAction(Integrate.java:219)
    at org.intermine.task.Integrate.performAction(Integrate.java:132)
    at org.intermine.task.Integrate.execute(Integrate.java:123)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:390)
    at org.apache.tools.ant.Target.performTasks(Target.java:411)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
    at org.apache.tools.ant.Main.runBuild(Main.java:809)
    at org.apache.tools.ant.Main.startAnt(Main.java:217)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.ClassCastException: org.intermine.objectstore.query.SingletonResults cannot be cast to java.util.Set
    at org.intermine.model.bio.ExonShadow.setFieldValue(ExonShadow.java:411)
    at org.intermine.dataconversion.ItemToObjectTranslator.translateFromDbObject(ItemToObjectTranslator.java:402)
    ... 48 more

```

**Comment by danielabutano** [comment]
Current code:
1) the interface LazyCollection<E> extends Lazy and Set
2) LazyCollection is implemented only by 2 classes: Results and ProxyCollection
3) Results extends AbstractList and ProxyCollection extends AbstractSet
4) SingletonResults extends Results (that extends AbstractList) but implements Set<Object>

Proposal changes:
1) update the LazyCollection to extend Collection instead of Set
2) update SingletonResults to implement Collection instead of Set. 
The second change causes the runtime exception during data loading: the ItemToObjectTranslator invokes obj.setFieldValue (where obj is an instance of FastPathObject) passing the singleton result as value, but his is not a Set anymore then the ClassCastException.
We could convert singleton result to a set before passing it to the setFiledValue() method but  I was wondering if it's correct remove Set from the SingletonResult class's signature.
