### ISSUE TITLE
Priorities config - throw nice exception if formatted incorrectly.

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1353]
it throws a weird error instead.
```
The following error occurred while executing this line:
/Users/me/intermine_work/intermine/imbuild/source.xml:330: org.intermine.objectstore.ObjectStoreException: Failed to instantiate IntegrationWriter class: org.intermine.dataloader.IntegrationWriterDataTrackingImpl
	at org.intermine.dataloader.IntegrationWriterFactory.getIntegrationWriter(IntegrationWriterFactory.java:78)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.intermine.dataloader.IntegrationWriterDataTrackingImpl.getInstance(IntegrationWriterDataTrackingImpl.java:143)
	... 38 more
Caused by: java.lang.IllegalArgumentException: Class 'celegans-gff3-gene,' not found in model, check priorities configuration file.

```

**Comment by julie-sullivan** [comment]
There was a tab behind the previous file, so it was parsing `celegans-gff3-gene,` as a data type.

**Comment by julie-sullivan** [comment]
(PriorityConfig.java)[https://github.com/intermine/intermine/blob/dev/intermine/integrate/main/src/org/intermine/dataloader/PriorityConfig.java] has no way of knowing `celegans-gff3-gene` is not a class.

```
Class 'celegans-gff3-gene,' not found in model, check priorities configuration file.
```

Is a really clear error message! Maybe remove all the tabs.

**Comment by julie-sullivan** [comment]
Priority config, as well as integration keys and data model xml are config files that are fairly fragile. Often the error message is not informative as well.
