### ISSUE TITLE
Query results - JSON Objects format not working?

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1355]
Trying to run this query using JSONObjects results in an error:

```
<query model="genomic" view="Gene.symbol Gene.secondaryIdentifier Gene.primaryIdentifier Gene.organism.name Gene.organism.taxonId Gene.homologues.homologue.primaryIdentifier Gene.homologues.homologue.secondaryIdentifier Gene.homologues.homologue.symbol Gene.homologues.homologue.organism.name Gene.homologues.homologue.organism.taxonId Gene.homologues.dataSets.name Gene.homologues.dataSets.url Gene.goAnnotation.evidence.code.code Gene.goAnnotation.evidence.publications.pubMedId Gene.goAnnotation.evidence.publications.title Gene.goAnnotation.ontologyTerm.identifier Gene.goAnnotation.ontologyTerm.name Gene.goAnnotation.ontologyTerm.namespace" sortOrder="Gene.symbol ASC" constraintLogic="B and C and A" name="intermod_go" > <constraint path="Gene.goAnnotation.qualifier" op="IS NULL" code="B" />  <constraint path="Gene.goAnnotation.ontologyTerm.obsolete" op="=" value="false" code="C" />
<constraint path="Gene.homologues.homologue.symbol" op="=" value="AVP" code="A" /></query>
```

In tomcat logs

```
520766351 [ajp-bio-8009-exec-74] ERROR org.intermine.webservice.server.WebService  - Service failed by internal error. Request parameters: 
query: <query model="genomic" view="Gene.symbol Gene.secondaryIdentifier Gene.primaryIdentifier Gene.organism.name Gene.organism.taxonId Gene.homologues.homologue.primaryIdentifier Gene.homologues.homologue.secondaryIdentifier Gene.homo
logues.homologue.symbol Gene.homologues.homologue.organism.name Gene.homologues.homologue.organism.taxonId Gene.homologues.dataSets.name Gene.homologues.dataSets.url Gene.goAnnotation.evidence.code.code Gene.goAnnotation.evidence.public
ations.pubMedId Gene.goAnnotation.evidence.publications.title Gene.goAnnotation.ontologyTerm.identifier Gene.goAnnotation.ontologyTerm.name Gene.goAnnotation.ontologyTerm.namespace" sortOrder="Gene.symbol ASC" constraintLogic="B and C a
nd A" name="intermod_go" > <constraint path="Gene.goAnnotation.qualifier" op="IS NULL" code="B" />  <constraint path="Gene.goAnnotation.ontologyTerm.obsolete" op="=" value="false" code="C" />
<constraint path="Gene.homologues.homologue.symbol" op="=" value="AVP" code="A" /></query>
size: 10
format: jsonobjects
org.intermine.webservice.server.output.JSONFormattingException: This result element ( RGD:2184 7004167 Gene) does not belong on this map ({primaryIdentifier=MGI:88121, symbol=Avp, objectId=4703643, class=Gene, secondaryIdentifier=null, 
organism={taxonId=10090, objectId=4480717, name=Mus musculus, class=Organism}}) - objectIds don't match (4703643 != 7004167)

  at org.intermine.webservice.server.output.JSONResultsIterator.setOrCheckId(JSONResultsIterator.java:229)
  at org.intermine.webservice.server.output.JSONResultsIterator.setOrCheckClassAndId(JSONResultsIterator.java:188)
  at org.intermine.webservice.server.output.JSONResultsIterator.addFieldToMap(JSONResultsIterator.java:261)
  at org.intermine.webservice.server.output.JSONResultsIterator.addAttributeToCurrentNode(JSONResultsIterator.java:393)
  at org.intermine.webservice.server.output.JSONResultsIterator.addReferencedCellToJsonMap(JSONResultsIterator.java:318)
  at org.intermine.webservice.server.output.JSONResultsIterator.addCellToJsonMap(JSONResultsIterator.java:246)
  at org.intermine.webservice.server.output.JSONResultsIterator.addRowToJsonMap(JSONResultsIterator.java:115)
  at org.intermine.webservice.server.output.JSONResultsIterator.next(JSONResultsIterator.java:97)
  at org.intermine.webservice.server.output.JSONResultsIterator.next(JSONResultsIterator.java:38)
  at org.intermine.webservice.server.output.JSONResultProcessor.write(JSONResultProcessor.java:57)
  at org.intermine.webservice.server.query.result.QueryResultService.runResults(QueryResultService.java:351)
  at org.intermine.webservice.server.query.result.QueryResultService.runPathQuery(QueryResultService.java:302)
  at org.intermine.webservice.server.query.result.QueryResultService.execute(QueryResultService.java:106)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.query.result.QueryResultServlet.runService(QueryResultServlet.java:61)
  at org.intermine.webservice.server.query.result.QueryResultServlet.doPost(QueryResultServlet.java:43)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

```

**Comment by julie-sullivan** [comment]
worksforme
