### ISSUE TITLE
Webconfig - don't allow collections. Either fail validation or update to allow

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1393]
You can't put collections in the field config.
1. QueryBuilder summary - works fine
2. Inline collections - ? fails
3. Report page - fails with the error below. 

```
Caused by: java.lang.RuntimeException: Attempt to to get value of field "allInteractors" for collection: Complex [function="A transcription factor complex which binds to the promoters of target genes and recruits co-activators and histone acetyltransferases, such as p300, CBP and P300/CBP-associated factor, facilitating transcription. In response to TGF-beta/activin-family protein binding, TGF-beta type II receptors phosphorylate TGF-beta type I receptors (ALK4, 5 and 7) which in turn phosphorylates SMAD2 on two Ser-465 and Ser-467, and SMAD3 on Ser-423 and Ser-425. This enables binding to SMAD4 to form heteromeric SMAD complexes that enter the nucleus to initiate gene transcription.
Because of their relatively low DNA-binding affinity, SMAD complexes interact with a wide variety of DNA-binding proteins. Crosstalk with other signalling pathways and interaction with other DNA-binding cofactors define the specific binding patterns of SMADs; in addition, interaction with coactivators/corepressors modulates their transcriptional activity. Heterotrimer ", id=37005629, identifier="EBI-10021614", name="SMAD2-SMAD3-SMAD4 complex", properties="Preferential formation of the regulatory R-Smad/SMAD4 heterotrimer over the R-Smad homotrimer is largely enthalpy driven, contributed by the unique presence of strong electrostatic interactions within the heterotrimeric interfaces. These electrostatic interactions exist only in the heterotrimer due to specific charged residues in the SMAD4 subunit, Asp-493 and Arg-378, mediating complementary electrostatic interactions with the neighbouring R-Smad subunits. ", systematicName="SMAD2:SMAD3:SMAD4"]It must be simple object. This operation is not allowed for collection.
        at org.intermine.api.util.PathUtil.resolvePath(PathUtil.java:66)
        at org.intermine.web.logic.results.ReportObject.resolvePath(ReportObject.java:386)
        at org.intermine.web.logic.results.ReportObject.setupFieldValues(ReportObject.java:376)
        at org.intermine.web.logic.results.ReportObject.getFieldValue(ReportObject.java:336)
        at org.intermine.web.logic.results.ReportObject.getObjectSummaryFields(ReportObject.java:212)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:97)
        ... 81 more
```

Maybe just discard the collections (for now) so that we don't get an error.  Or is that confusing?

**Comment by julie-sullivan** [comment]
Tell @kkarra

**Comment by julie-sullivan** [comment]
1. ignore error, just drop collections silently
2. fix so collections are allowed
3. forbid collections, e.g. fail validation so collections are forbidden.

**Comment by julie-sullivan** [comment]
@kkarra this is fixed in dev, so will be in the next release.
