### ISSUE TITLE
BDGP - add anatomy term identifiers

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1421]
BDGP load anatomy terms. We think these terms will merge (mostly) with FlyBase anatomy terms. Add the integration key.

**Comment by julie-sullivan** [comment]
@rachellyne Please test this! Might be a bad idea.

**Comment by julie-sullivan** [comment]
failed.

```
774356 [ajp-nio-8009-exec-53] ERROR org.intermine.webservice.server.WebService  - Service failed by internal error. Request parameters: 
start: 0
size: 250
query: <query model="genomic" view="Gene.name Gene.mRNAExpressionResults.stageRange Gene.mRNAExpressionResults.expressed Gene.mRNAExpressionResults.mRNAExpressionTerms.name Gene.mRNAExpressionResults.dataSet.dataSource.name" sortOrder="Gene.name ASC" constraintLogic="A and C and B" name="Gene_BDGP" ><constraint path="Gene.organism.name" op="=" value="Drosophila melanogaster" code="C" /><constraint path="Gene.mRNAExpressionResults.dataSet.name" op="=" value="BDGP in situ data set" code="B" /><constraint path="Gene" op="LOOKUP" value="runt" code="A" /></query>
format: json
java.lang.IllegalArgumentException: No simple name for class: AnatomyTerm,MRNAExpressionTerm

  at org.intermine.util.DynamicUtil.getSimpleClassName(DynamicUtil.java:288)
  at org.intermine.webservice.server.core.TableRowIterator$7.visitLeft(TableRowIterator.java:527)
  at org.intermine.webservice.server.core.TableRowIterator$7.visitLeft(TableRowIterator.java:516)
  at org.intermine.webservice.server.core.Either$Left.accept(Either.java:138)
  at org.intermine.webservice.server.core.DisjointRecursiveList.forEach(DisjointRecursiveList.java:109)
  at org.intermine.webservice.server.core.TableRowIterator.recursiveNext(TableRowIterator.java:516)
  at org.intermine.webservice.server.core.TableRowIterator.next(TableRowIterator.java:498)
  at org.intermine.webservice.server.query.result.TableRowService.runPathQuery(TableRowService.java:115)
  at org.intermine.webservice.server.query.result.QueryResultService.execute(QueryResultService.java:106)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.query.result.QueryResultServlet.runService(QueryResultServlet.java:61)
  at org.intermine.webservice.server.query.result.QueryResultServlet.doPost(QueryResultServlet.java:43)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
 ...
```

Merge correctly.

**Comment by julie-sullivan** [comment]
@rachellyne Should I leave this as is? BDGP is creating `MRNAExpressionTerm` and the FlyBase source is creating `AnatomyTerm`. 

What should I do?

**Comment by rachellyne** [comment]
I think we'll have to leave it - unless we can create a reference to the anatomy ontology term where there is one?

**Comment by julie-sullivan** [comment]
Okay I will revert this change and close this ticket.

I think this effort will be part of #412

**Comment by nuin** [comment]
@julie-sullivan We are getting a similar error only on 2.x with Phenotype and Phenotype Ontology classes

Is there a way to debug this and see what's wrong?

```@cgrove It seems some problem with the 2.0 and not accepting some configurations we had on 1.8.5
```]77881422 [http-nio-8080-exec-117] ERROR org.intermine.webservice.server.WebService  - Service failed by internal error. Request parameters:
start: 0
size: 250
query: <query model="genomic" view="Allele.primaryIdentifier Allele.symbol Allele.phenotype.identifier Allele.phenotype.name" sortOrder="Allele.primaryIdentifier ASC" ><constraint path="Allele.primaryIdentifier" op="IS NOT NULL" code="A" /></query>
format: json
java.lang.IllegalArgumentException: No simple name for class: Phenotype,PhenotypeOntology```

**Comment by julie-sullivan** [comment]
`Phenotype,PhenotypeOntology` -- Your code is merging these two classes, so this means the integration keys must be missing/incomplete.

Your `phenotype_ontology` source is definitely missing a few classes: https://github.com/WormBase/wormmine-bio-sources/blob/im-266/phenotype_ontology/resources/phenotype_ontology_keys.properties

I didn't see the Phenotype data source, but you'll want to update that too.

If you update your keys to specifically include `PhenotypeOntology` and `Phenotype`, this problem should go away.
