### ISSUE TITLE
HTTPS - web services using hardcoded HTTP 

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1443]
I started using HTTPS for humanmine and noticed the queries weren't working as expected. There is a hardcoded HTTP somewhere. Which is dumb.

**Comment by julie-sullivan** [comment]
I still get an error

```
ERROR [ajp-nio-8009-exec-15] (WebService.java:622) - Service failed by internal error. Request parameters: 
query: <query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.proteins.primaryIdentifier Gene.proteins.primaryAccession Gene.proteins.name Gene.id" sortOrder="Gene.primaryIdentifier ASC" name="Gene_Protein" ><constraint pat
h="Gene" op="LOOKUP" value="PPARG" extraValue="H. sapiens" code="A" /></query>
summaryPath: Gene.id
format: jsonrows
org.intermine.webservice.server.exceptions.ServiceException: XML validation failed. https://beta.humanmine.org/beta/service/webservice/query.xsd

  at org.intermine.webservice.server.query.result.XMLValidator.validate(XMLValidator.java:80)
  at org.intermine.webservice.server.query.result.PathQueryBuilder.buildQuery(PathQueryBuilder.java:72)
  at org.intermine.webservice.server.query.result.PathQueryBuilder.<init>(PathQueryBuilder.java:58)
  at org.intermine.webservice.server.query.AbstractQueryService.getQueryBuilder(AbstractQueryService.java:81)
  at org.intermine.webservice.server.query.result.QueryResultService.execute(QueryResultService.java:103)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.query.result.QueryResultServlet.runService(QueryResultServlet.java:61)
  at org.intermine.webservice.server.query.result.QueryResultServlet.doPost(QueryResultServlet.java:43)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
 ...
 caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

```

It looks like it's still trying to go to http://beta.humanmine.org?

![https](https://cloud.githubusercontent.com/assets/1663057/19386839/6436a1fe-920e-11e6-9704-5b317985a20c.png)

Tell @sergiocontrino

**Comment by nuin** [comment]
I am getting the exact same error on WormMine

```
570235 [http-bio-8080-exec-24] INFO org.intermine.webservice.server.query.result.XMLValidator  - Using the xmlSchemaUrl http://im-256.wormbase.org/tools/wormmine/webservice/query.xsd
570237 [http-bio-8080-exec-24] ERROR org.intermine.webservice.server.WebService  - Service failed by internal error. Request parameters:
query: <query model="genomic" view="Protein.primaryIdentifier Protein.motifs.primaryIdentifier Protein.organism.name Protein.id" sortOrder="Protein.primaryIdentifier ASC" name="proteins_with_specific_motif" ><constraint path="Protein.motifs.primaryIdentifier" op="=" value="PFAM:PF13508" code="A" /></query>
summaryPath: Protein.id
format: jsonrows
org.intermine.webservice.server.exceptions.ServiceException: XML validation failed. http://im-256.wormbase.org/tools/wormmine/webservice/query.xsd```
