### ISSUE TITLE
OMIM script fails after a while

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1493]
```
MIM[182100] pubmedID does not exist: {u'source': u'Naturwissenschaften 21: 560-561, 1953.', u'mimNumber': 182100, u'authors': u'Grubb, R.', u'title': u'Zur Genetik des Lewis-Systems.', u'referenceNumber': 6}
MIM[182100] pubmedID does not exist: {u'source': u'Copenhagen: Munksgaard (pub.)  1954.', u'mimNumber': 182100, u'authors': u'Mohr, J.', u'title': u'A Study of Linkage in Man.', u'referenceNumber': 20}
MIM[182100] pubmedID does not exist: {u'source': u'Philadelphia: F. A. Davis Co. (pub.)  1968.', u'mimNumber': 182100, u'authors': u'Race, R. R., Sanger, R.', u'title': u'Blood Groups in Man. (5th ed.)', u'referenceNumber': 22}
MIM[182100] pubmedID does not exist: {u'source': u'New York: Oxford Univ. Press (pub.)  1988.', u'mimNumber': 182100, u'authors': u'Roychoudhury, A. K., Nei, M.', u'title': u'Human Polymorphic Genes: World Distribution.', u'referenceNumber': 25}
Traceback (most recent call last):
  File "./get_omim_pubmed.py", line 101, in <module>
    main()
  File "./get_omim_pubmed.py", line 91, in main
    pubmed_cited_list = get_omim_pubmed(mim_number, log)
  File "./get_omim_pubmed.py", line 42, in get_omim_pubmed
    data = resp.json() # In case the JSON decoding fails, r.json simply returns None.
  File "/usr/local/lib/python2.7/dist-packages/requests-2.8.1-py2.7.egg/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.6.5-py2.7-linux-x86_64.egg/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.6.5-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson-3.6.5-py2.7-linux-x86_64.egg/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by julie-sullivan** [comment]
I just tried with a handful of entries and it exited fine. There is an unexpected value somewhere.

**Comment by julie-sullivan** [comment]
Specifically for OMIM:103780 there should be 49 publications.
```
103780  1       11102287
103780  2       2339688
103780  3       6474187
103780  4       19193628
103780  5       17921519
103780  6       1969501
103780  7       1979357
103780  8       15731118
103780  9       9880654
103780  10      18541917
103780  11      15863807
103780  12      2882604
103780  13      2298906
103780  14      18319328
103780  15      16571603
103780  16      17928304
103780  17      10923994
103780  18      18276852
103780  19      12749054
103780  20      23239122
103780  21      24268660
103780  22      12915525
103780  23      16385453
103780  24      17804423
103780  25      20332099
103780  26      10869113
103780  27      18056758
103780  28      26430123
103780  29      8807664
103780  30      12215082
103780  31      15094791
103780  32      12665621
103780  33      9603607
103780  34      16000316
103780  35      18996923
103780  36      10089015
103780  37      11329392
103780  38      3189329
103780  39      16534506
103780  40      10819022
103780  41      15630072
103780  42      9603606
103780  43      758678
103780  44      10395222
103780  45      17923853
103780  46      4036659
103780  47      17250611
103780  48      15229186
103780  49      17622222
```

The script stopped prematurely.
