### ISSUE TITLE
Publications update failing - UTF encoding

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1532]
```
Caused by: java.sql.SQLException: Error writing to database, running statement COPY Item (implementations, className, identifier, id) FROM STDIN BINARY, data size = 97287
        at org.intermine.sql.writebatch.FlushJobPostgresCopyImpl.flush(FlushJobPostgresCopyImpl.java:56)
        at org.intermine.sql.writebatch.Batch$BatchFlusher.run(Batch.java:461)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1049)
        at org.postgresql.core.v3.QueryExecutorImpl.startCopy(QueryExecutorImpl.java:766)
        at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:48)
        at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:209)
        at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:192)
        at org.intermine.sql.writebatch.FlushJobPostgresCopyImpl.flush(FlushJobPostgresCopyImpl.java:51)
        ... 2 more
Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0xed 0xa0 0xb5
  Where: COPY attribute, line 16980, column intermine_value
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1049)
        at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:892)
        at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:40)
        at org.postgresql.copy.CopyManager.copyIn(CopyManager.java:216)
        ... 4 more

```

**Comment by julie-sullivan** [comment]
1. The InterMine data source "update-publications" sends a bunch of PubMed IDs to NCBI's web service
2. Their web service returns, for each publication, the publication title, author etc. 
3. This is processed by the InterMine (Java) data source successfully. Publication objects are created and updated with the new information
4. Postgres stores these publication objects. This is what fails. Likely a funny character that Postgres thinks is UTF but is not.

An example request

```
[integrate] retrieving: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?tool=flymine&db=pubmed&rettype=abstract&retmode=xml&id=2933589,16245368,15591776,6419127,6209582,10352938,19098452,9147475,1524678,20609497,21327109,17274673,19788048,9285100,1326278,2433596,16580865,17617744,3838366,10469568,8264796,18052087,16963840,18497339,15578726,3491322,10087504,17686645,18610840,10471116,2863757,21570500,2825030,2825025,3022150,366724,16283771,8537108,26545777,18834961,19484742,2823150,3093892,23010571,25657994,4215718,15908120,23782956,21874239,8055875,22572157,17076679,1944255,25681212,16631377,18312938,16212417,11959398,2995821,9150946,17127621,7835232,10652580,18078367,25767741,2989698,10994649,14730209,16677074,107465,15650299,3003578,21319131,2879245,3409840,12762840,2879243,11700865,1673382,21468593,16114325,12359132,10622252,2936963,15952736,3839290,3600759,6440030,7711835,2505992,10959840,7997261,21621375,60899,3921850,17951129,6334807,11780064,6336315,11780067,11896977,21593607,3657987,19154770,16278369,7997270,3020431,10647776,22321011,17684005,12892531,20458337,6208535,16384638,9507743,3001529,12742085,15464421,2531377,2421165,12082544,6547996,16194878,6687716,23576305,19153051,10604883,12398221,18676163,12867083,16564713,10714828,9781040,16243425,14721776,6382022,16574458,12566959,6688857,1427768,16158934,3018581,12467198,12765338,3925348,9781036,21555002,3925347,27571896,3313057,9707407,6415485,11162141,16154903,21699545,22837859,9575347,6298628,9699963,10573014,4803843,16899810,12595760,6325927,20543562,16213650,27578112,9673349,17961633,19433310,11491531,11491533,15590417,6325948,14521551,12203945,18515060,3903517,19565474,19931550,12745312,19152659,16580862,737019,3453121,16087305,18501882,20665473,10810353,3754619,16301118,19800018,15999530,10100484,10708949,10708948,1279380,4015840,18298960,11681785,7550339,10226785,22231121
```

FlyMine is fine, RatMine and HumanMine failed. Likely one specific publication.

**Comment by julie-sullivan** [comment]
```
2017-04-18 13:23:31 ERROR org.intermine.bio.dataconversion.EntrezPublicationsRetriever     - Couldn't parse PubMed XML
java.lang.NullPointerException
        at org.intermine.bio.dataconversion.EntrezPublicationsRetriever$FullRecordHandler.endElement(EntrezPublicationsRetriever.java:547)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.endNamespaceScope(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.handleEndElement(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.endElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
```

Errors in the log. But it went ahead and processed other PubMed IDs.
I am pretty sure I just changed the data file instead of letting the Java handle it.

**Comment by julie-sullivan** [comment]
14747882 - has this entry

```The urinary NAT2 ratios (AFMU+AAMU) / (AFMU+AAMU+1X+1U)```

**Comment by julie-sullivan** [comment]
```
  sourcename   
---------------
 huge-gwas
 uniprot
 mgi-alleles
 pubmed-gene
 interpro
 psi-intact
 biogrid
 go-annotation
 omim
 psi-complexes
 signor
```
All the sources that load publications.

**Comment by sergiocontrino** [comment]
the offending entry is pubmedid 22020278, which has an 'illegal input sequence' after `<ArticleTitle>Aspartate`
which seems to derive from a 'thin space' in the text.
the resulting UTF-8 is not valid.

**Comment by sergiocontrino** [comment]
actually the culprit is 27041523, the letter 𝜅.
used iconv from utf to unicode (rather than ascii, which was giving loads of errors).

**Comment by sergiocontrino** [comment]
the original error refers to
`&iacute; &nbsp; &micro;`

í	latin small letter i with acute	0355	237	0xED	&iacute;
x{A0}	no-break space	0240	160	0xA0	&nbsp;
µ	micro sign	0265	181	0xB5	&micro;

**Comment by sergiocontrino** [comment]
summary of finds:
- offending entry: pubmedid 27041523.
- found doing utf to unicode conversion
`iconv -f UTF-8 -t UNICODE` publications.xml
- the offending char appear to be 𝜅 or `U+1D705   MATHEMATICAL ITALIC SMALL KAPPA`

not solved:
- how to screen for this char in the file
- what is the relationship with the sequence of chars of the previous comment

a note:
SQL_ASCII is a postgres encoding (or lack of it, see below), so we cannot run a test with it.

> The SQL_ASCII setting behaves considerably differently from the other settings. When the server character set is SQL_ASCII, the server interprets byte values 0-127 according to the ASCII standard, while byte values 128-255 are taken as uninterpreted characters. No encoding conversion will be done when the setting is SQL_ASCII. Thus, this setting is not so much a declaration that a specific encoding is in use, as a declaration of ignorance about the encoding. In most cases, if you are working with any non-ASCII data, it is unwise to use the SQL_ASCII setting because PostgreSQL will be unable to help you by converting or validating non-ASCII characters.

**Comment by danielabutano** [comment]
The Character 𝜅 or U+1D705 MATHEMATICAL ITALIC SMALL KAPPA is a supplementary character. A supplementary character is a character that goes beyond the original 16-bit limit.
**Standard UTF-8** uses sequences of one to four bytes to encode Unicode code points.
U+0000 to U+007F are encoded in one byte,
U+0080 to U+07FF in two bytes,
U+0800 to U+FFFF in three bytes,
and U+10000 to U+10FFFF in four bytes. 
**Modified UTF-8** represents supplementary characters by separately encoding the two surrogate code units of their UTF-16 representation. Each of the surrogate code units is represented by three bytes, for a total of six bytes.
**Modified UTF-8 UTF-8 cannot be used when standard UTF-8 is required (from Postgres)**
Modified UTF-8 is used by the Java Virtual Machine and the interfaces attached to it, in the java.io.DataInput and DataOutput interfaces and classes implementing or using them, and for serialization.

Solution: update the method writeUTF in the class PostgresDataOutputStream (extending DataOutput). The original method was very similar to writeUTF provided by DataOutputStream.

**Comment by danielabutano** [comment]
@julie-sullivan could you please test it in beta?

**Comment by julie-sullivan** [comment]
Can you make a pull request? Include details as to what I should do to test. 

THANKS!!

**Comment by julie-sullivan** [comment]
![kappa](https://cloud.githubusercontent.com/assets/1663057/25655333/72d2cd42-2fec-11e7-982d-5190f71fde1c.png)

Full build worked, symbols are showing up successfully in beta humanmine.
