### ISSUE TITLE
Tomcat 9 errors

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1542]
Jiannan Chen tried to load InterMine with tomcat 9 and got some weird errors. 

Check to make sure InterMine still works with tomcat 9!

**Comment by julie-sullivan** [comment]
Here is the full stacktrace:

```
3674633 [http-nio-8080-exec-9] ERROR org.intermine.web.struts.InterMineExceptionHandler  - java.lang.IllegalArgumentException: An invalid character [32] was present in the Cookie value
	at org.apache.tomcat.util.http.Rfc6265CookieProcessor.validateCookieValue(Rfc6265CookieProcessor.java:182)
	at org.apache.tomcat.util.http.Rfc6265CookieProcessor.generateHeader(Rfc6265CookieProcessor.java:115)
	at org.apache.catalina.connector.Response.generateCookieString(Response.java:999)
	at org.apache.catalina.connector.Response.addCookie(Response.java:947)
	at org.apache.catalina.connector.ResponseFacade.addCookie(ResponseFacade.java:386)
	at org.intermine.web.struts.BeginAction.setUserVisitedCookie(BeginAction.java:232)
	at org.intermine.web.struts.BeginAction.execute(BeginAction.java:172)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.intermine.web.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:139)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by justinccdev** [comment]
This failure can be fixed by Maxime's patch in [1].  This reveals another problem to do with DWR.  This may or may not be a Tomcat issue.  Tomcat 9 is in alpha and shouldn't be used yet.

[1] http://stackoverflow.com/questions/21780720/error-in-dwr-2-0-5

**Comment by julie-sullivan** [comment]
http://gmod.827538.n3.nabble.com/bad-cookie-value-with-tomcat-9-td4052916.html Is where Maxime reports this bug.

@justinccdev have you confirmed this fixes the problem? If so, I'll ask Jiannen to try it.

**Comment by justinccdev** [comment]
It does fix that problem. Yes, please ask him to try it.

**Comment by julie-sullivan** [comment]
Another tomcat 8.5+ error: #1507
