### ISSUE TITLE
Java client - requires genomic model

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1608]
```
ServiceFactory serviceFactory = new ServiceFactory(serviceRootUrl,authToken);
TemplateService templateService = serviceFactory.getTemplateService();

try{
    System.out.println(templateService.getTemplateNames());
}
catch (Exception e){
    System.out.println(e);
}
```

Generates this error:

```
org.xml.sax.SAXException: Model definition file 'genomic_model.xml' cannot be found
java.lang.IllegalArgumentException: Model definition file 'genomic_model.xml' cannot be found
	at org.intermine.pathquery.PathQueryHandler.startElement(PathQueryHandler.java:126)
	at org.intermine.template.xml.TemplateQueryHandler.startElement(TemplateQueryHandler.java:91)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
```

Instead use the `templates` end point.

**Comment by julie-sullivan** [comment]
This is where we get the error: https://github.com/intermine/intermine/blob/dev/intermine/pathquery/main/src/org/intermine/pathquery/PathQueryHandler.java#L124

We don't have `genomic_model.xml` in the client, but we are able to get the model from elsewhere.

Tell @danielabutano
