### ISSUE TITLE
MGI identifiers source failed

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1612]
```
BUILD FAILED
/data/code/flyminebuild/imbuild/integrate.xml:54: The following error occurred while executing this line:
/data/code/flyminebuild/imbuild/source.xml:145: java.lang.ArrayIndexOutOfBoundsException: 9
        at org.intermine.bio.dataconversion.MgiIdentifiersConverter.process(MgiIdentifiersConverter.java:63)
        at org.intermine.task.FileConverterTask.execute(FileConverterTask.java:116)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
```

**Comment by julie-sullivan** [comment]
It's downloading HTML, I don't know why. `wget` gets the correct file.
