### ISSUE TITLE
OBO files have terms without names

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1613]
Why do terms not have names?

```
[Typedef]
id: composed_primarily_of
name: composed_primarily_of
def: "x composed_primarily_of y iff: more than half of the mass of x is made from parts of y" []
xref: RO:0002473
is_a: has_part ! has_part

[Typedef]
id: connected_to
name: connected_to
def: "X connected_to Y if and only if X and Y share a fiat boundary." [FBC:DOS]
comment: Examples: Many tracts (neuron projection bundles) share a fiat boundary with the neuropil they innervate - any boundary between the two slice through many continuous neuron projections.  Note - this may be renamed to 'continuous with' at some point.
xref: RO:0002150

[Typedef]
id: contained_in
name: contained_in
xref: RO:0001018
holds_over_chain: located_in part_of
```

Error message:

```
BUILD FAILED
/data/code/flyminebuild/imbuild/integrate.xml:54: The following error occurred while executing this line:
/data/code/flyminebuild/imbuild/source.xml:289: Ontology term did not have a name:RO:0002473
        at org.intermine.bio.ontology.OboParser.readTerms(OboParser.java:253)
        at org.intermine.bio.ontology.OboParser.processOntology(OboParser.java:81)
        at org.intermine.bio.dataconversion.OboConverter.process(OboConverter.java:113)
        at org.intermine.bio.task.OboConverterTask.execute(OboConverterTask.java:111)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
```

@rachellyne These are from the FlyBase anatomy OBO file. Should we load these terms? Or discard them?

**Comment by julie-sullivan** [comment]
Refs #1486
