### ISSUE TITLE
Templates export in JSON format causes deadlock.

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1648]
The iOS app was successfully able to kill InterMines regularly, specifically the templates page.

* the mine only became unreponsive if there were simultaneous requests for `/service/template?format=json`. sequential requests are processed successfully
* only JSON, XML format works correctly
* not related to ranking #1309. I removed the code and still can crash a mine
* related to tags, I can take this code out and it prevents deadlock  #1154

Thread dump:

```
"ajp-nio-8009-exec-412" daemon prio=10 tid=0x00007f5ba40a0000 nid=0x9def waiting for monitor entry [0x00007f5874fcd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.intermine.pathquery.PathQuery.verifyQuery(PathQuery.java:1411)
        - waiting to lock <0x000000009ff458d0> (a org.intermine.api.template.ApiTemplate)
        at org.intermine.pathquery.PathQuery.isValid(PathQuery.java:1383)
        at org.intermine.api.template.TemplateManager.getValidGlobalTemplates(TemplateManager.java:320)
        at org.intermine.api.template.TemplateManager.getAspectTemplates(TemplateManager.java:272)
        at org.intermine.api.template.TemplateManager.getPopularTemplatesByAspect(TemplateManager.java:481)
        at org.intermine.api.template.TemplateManager.getPopularTemplatesByAspect(TemplateManager.java:467)
        at org.intermine.web.struts.BeginAction.execute(BeginAction.java:132)
...
   at  org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
        - locked <0x000000076314a788> (a org.apache.tomcat.util.net.NioChannel)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by julie-sullivan** [comment]
Fun fact, removing `synchronised` from this method works too https://github.com/intermine/intermine/blob/dev/intermine/pathquery/main/src/org/intermine/pathquery/PathQuery.java#L1410 :|

**Comment by yochannah** [comment]
@joystate fyi - we think Julie fixed the issue, which we probably wouldn't have been able to do without your help and Charles (great tool!)

As mentioned earlier,  it won't be propagated to all InterMines for some time we'll need to throttle /templates endpoint requests from the iOS app so they don't accidentally cause the deadlock conditions.

**Comment by julie-sullivan** [comment]
Summary

* Added a cache for valid global templates. This prevents the validation happening with every request. Validation checks the model, syntax etc so is more expensive.  
* Invalidated cache when the super user changed ANY template. 
* Invalidated cache when the super user changed (added / deleted) `IM_PUBLIC` tag
