### ISSUE TITLE
We are using sets and lists interchangably

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1675]
This needs to be fixed for InterMine 2.0. 

```
do-compile-with-gen-src:
    [javac] Compiling 209 source files to /local-homes/julie/git/intermine/intermine/objectstore/main/build/classes
[dependencies] /local-homes/julie/git/intermine/intermine/objectstore/main/src/org/intermine/objectstore/query/Results.java:38: error: class Results inherits unrelated defaults for spliterator() from types Set and List
[dependencies] public class Results extends AbstractList<Object> implements LazyCollection<Object>
[dependencies]        ^
[dependencies] /local-homes/julie/git/intermine/intermine/objectstore/main/src/org/intermine/objectstore/query/SingletonResults.java:27: error: class SingletonResults inherits unrelated defaults for spliterator() from types Set and List
[dependencies] public class SingletonResults extends Results implements Set<Object>
[dependencies]        ^
[dependencies] Note: /local-homes/julie/git/intermine/intermine/objectstore/main/src/org/intermine/objectstore/query/QueryField.java uses or overrides a deprecated API.
[dependencies] Note: Recompile with -Xlint:deprecation for details.
[dependencies] Note: Some input files use unchecked or unsafe operations.
[dependencies] Note: Recompile with -Xlint:unchecked for details.

```

**Comment by julie-sullivan** [comment]
https://github.com/julie-sullivan/intermine/blob/62b5d8a6da3b42054eb331979571a105d3f25b03/imbuild/library.xml#L34-L35

**Comment by julie-sullivan** [comment]
I can't run unit tests in Eclipse

```
java.lang.Error: Unresolved compilation problem: 
	Duplicate default methods named spliterator with the parameters () and () are inherited from the types List<Object> and Set<Object>

	at org.intermine.objectstore.query.Results.<init>(Results.java:38)
	at org.intermine.objectstore.dummy.DummyResults.<init>(DummyResults.java:31)
	at org.intermine.webservice.server.output.JSONRowFormatterTest.getIterator(JSONRowFormatterTest.java:175)
	at org.intermine.webservice.server.output.JSONRowFormatterTest.setUp(JSONRowFormatterTest.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by julie-sullivan** [comment]
Duplicate of  #1343
