### ISSUE TITLE
Template error - casting String to an array

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1706]
When I try to deploy a webapp with gradle, i get this error:

```
[INFO] DefaultRemoter - Exec: AjaxServices.getNewsPreview()
16:12:53 INFO  anonymous	global	ManagerLookup
16:12:53 ERROR java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.lang.String
	at org.intermine.web.struts.TemplateAction.templateFormToTemplateValues(TemplateAction.java:373)
	at org.intermine.web.struts.TemplateAction.execute(TemplateAction.java:162)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
```

It is because Java 8 is more strict and won't let us do dodgy things? Or Tomcat 8.x? Or both? That doesn't make sense because I'm able to deploy on the dev branch using both of those. 

Not sure!

**Comment by justinccdev** [comment]
Having chased this down right into struts and bean mapping code, it's still not obvious why this has changed.  It doesn't obviously appear to be a struts config issue.  Since the JSP will go away in favour of BlueGenes at some point, rather than chase this down further I performed the same hack fixes the remaining issues revealed by biotestmine/malariamine templates in a287177
