### ISSUE TITLE
Update Chebi JAR

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1734]
From @kkarra

```
BUILD FAILED
/data/tools/intermine/dev/intermine/imbuild/integrate.xml:54: The following error occurred while executing this line:
/data/tools/intermine/dev/intermine/imbuild/source.xml:145: javax.xml.ws.WebServiceException: {http://www.ebi.ac.uk/webservices/chebi}ChebiWebServiceService is not a valid service. Valid services are: {https://www.ebi.ac.uk/webservices/chebi}ChebiWebServiceService
at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:310)
at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:215)
at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:196)
at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:192)
at com.sun.xml.internal.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:104)
at javax.xml.ws.Service.<init>(Service.java:77)
at uk.ac.ebi.chebi.webapps.chebiWS.model.ChebiWebServiceService.<init>(ChebiWebServiceService.java:46)
at uk.ac.ebi.chebi.webapps.chebiWS.client.ChebiWebServiceClient.<init>(ChebiWebServiceClient.java:42)
at org.intermine.bio.dataconversion.PsiComplexesConverter.getChebiName(PsiComplexesConverter.java:380)
at org.intermine.bio.dataconversion.PsiComplexesConverter.processProtein(PsiComplexesConverter.java:356)
at org.intermine.bio.dataconversion.PsiComplexesConverter.processInteractions(PsiComplexesConverter.java:218)
at org.intermine.bio.dataconversion.PsiComplexesConverter.process(PsiComplexesConverter.java:170)
```

 Looks like they have an update jar..

https://mvnrepository.com/artifact/uk.ac.ebi.chebi.webapps.chebiWS.client/chebiWS-client/2.3.2

**Comment by julie-sullivan** [comment]
Fixed by 1cd4920feb199ffa08d61b460657172de98aa22d
