### ISSUE TITLE
Minification step fails

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1737]
```
BUILD FAILED
/home/hendrik.weisser/Software/InterMine/imbuild/library.xml:78: The following error occurred while executing this line:
/home/hendrik.weisser/Software/InterMine/imbuild/webapp.xml:93: java.lang.StringIndexOutOfBoundsException: String index out of range: 417
    at java.lang.String.substring(String.java:1963)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.printSourceString(JavaScriptCompressor.java:267)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:330)
    at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:533)
    at net.noha.tools.ant.yuicompressor.tasks.YuiCompressorTask.createJavaScriptCompressor(YuiCompressorTask.java:171)
    at net.noha.tools.ant.yuicompressor.tasks.YuiCompressorTask.compressFile(YuiCompressorTask.java:149)
at net.noha.tools.ant.yuicompressor.tasks.YuiCompressorTask.execute(YuiCompressorTask.java:101)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
    at org.intermine.task.Dependencies.execute(Dependencies.java:281)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    at org.apache.tools.ant.Main.runBuild(Main.java:857)
    at org.apache.tools.ant.Main.startAnt(Main.java:236)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
```

This is the line generating the error

```
<yui-compressor warn="false" charset="UTF-8" jsSuffix="-COMPRESSED.js" cssSuffix="-min.css" fromdir="${build.dir}" todir="${build.dir}">
```

Generated by running `ant` in the webapp directory for biotestmine.

```
openjdk version "1.8.0_151"
OS: Ubuntu 16.04 Server.
```

**Comment by julie-sullivan** [comment]
This has moved to gradle.
