### ISSUE TITLE
Gradle: error running LOOKUP templates

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1752]
Error when running a LOOKUP query in `All proteins in organism --> Publications.`
```
15:15:51 ERROR java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.lang.String
        at org.intermine.web.struts.TemplateForm.getMultiValueAttribute(TemplateForm.java:213)
        at org.intermine.web.struts.TemplateAction.templateFormToTemplateValues(TemplateAction.java:397)
        at org.intermine.web.struts.TemplateAction.execute(TemplateAction.java:162)
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
        at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)

```

**Comment by julie-sullivan** [comment]
This should be empty or NULL:

```
<input type="hidden" name="multiValueAttribute(1)" value="" id="multiValueAttribute(1)" />
```

I don't know what's going on.

**Comment by julie-sullivan** [comment]
![template-form](https://user-images.githubusercontent.com/1663057/35343224-fb50544e-0121-11e8-9b4a-c0bd86510037.png)

**Comment by julie-sullivan** [comment]
Tell @danielabutano

**Comment by julie-sullivan** [comment]
@danielabutano - I did not commit these fixes! But if you do this, all templates work as expected.

```
+++ b/intermine/webapp/src/main/java/org/intermine/web/struts/TemplateAction.java
@@ -394,7 +394,15 @@ public class TemplateAction extends InterMineAction
                             ConstraintOp constraintOp = ConstraintOp
                                     .getOpForIndex(Integer.valueOf(op));
                             String constraintValue = "";
-                            String multiValueAttribute = tf.getMultiValueAttribute(key);
+                            String multiValueAttribute = null;
+                            try {
+                                if (tf.getMultiValueAttribute(key) instanceof String) {
+                                    multiValueAttribute = tf.getMultiValueAttribute(key);
+                                }
+                            } catch (java.lang.ClassCastException e) {
+                                // There's an array instead of a String. I don't know why.
+                                // ignore! should be NULL
+                            }
                             if (multiValueAttribute != null && !("".equals(multiValueAttribute))) {
                                 constraintValue = tf.getMultiValueAttribute(key);
                                 List<String> multiValues = new ArrayList<String>();
@@ -406,7 +414,10 @@ public class TemplateAction extends InterMineAction
                                 String[] attributes = (String[]) tf.getAttributeValues(key);
                                 constraintValue = attributes[0];
                                 String[] extraValues = (String[]) tf.getExtraValues(key);
-                                String extraValue = extraValues[0];
+                                String extraValue = "";
+                                if (extraValues != null) {
+                                    extraValue = extraValues[0];
+                                }
                                 value = new TemplateValue(c, constraintOp, constraintValue,
                                         TemplateValue.ValueType.SIMPLE_VALUE, extraValue,
                                         switchOffAbility);
```
