### ISSUE TITLE
Gradle: error with ID resolvers

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1784]
```
Caused by: : java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: org.postgresql.util.PSQLException: This connection has been closed.
        at org.intermine.bio.task.GFF3ConverterTask.execute(GFF3ConverterTask.java:246)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.intermine.plugin.integrate.IntegrateUtils$_closure8.doCall(IntegrateUtils.groovy:191)
        at org.intermine.plugin.integrate.IntegrateUtils.invokeMethod(IntegrateUtils.groovy)
        at org.intermine.plugin.integrate.IntegrateUtils$_closure2.doCall(IntegrateUtils.groovy:57)
        at org.intermine.plugin.integrate.IntegratePlugin$_apply_closure7$_closure20.doCall(IntegratePlugin.groovy:158)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:681)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: org.postgresql.util.PSQLException: This connection has been closed.
        at org.intermine.bio.dataconversion.IdResolverFactory.getIdResolver(IdResolverFactory.java:64)
        at org.intermine.bio.dataconversion.IdResolverService.getFlyIdResolver(IdResolverService.java:121)
        at org.intermine.bio.dataconversion.MirandaGFF3RecordHandler.process(MirandaGFF3RecordHandler.java:51)
        at org.intermine.bio.dataconversion.GFF3Converter.process(GFF3Converter.java:397)
        at org.intermine.bio.dataconversion.GFF3Converter.parse(GFF3Converter.java:254)
        at org.intermine.bio.task.GFF3ConverterTask.execute(GFF3ConverterTask.java:241)
        ... 42 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.postgresql.util.PSQLException: This connection has been closed.
        at org.intermine.bio.dataconversion.FlyBaseIdResolverFactory.createIdResolver(FlyBaseIdResolverFactory.java:94)
        at org.intermine.bio.dataconversion.IdResolverFactory.getIdResolver(IdResolverFactory.java:60)
        ... 47 more
Caused by: java.lang.RuntimeException: org.postgresql.util.PSQLException: This connection has been closed.
        at org.intermine.bio.dataconversion.FlyBaseIdResolverFactory.createFromDb(FlyBaseIdResolverFactory.java:260)
        at org.intermine.bio.dataconversion.FlyBaseIdResolverFactory.createIdResolver(FlyBaseIdResolverFactory.java:90)
        ... 48 more
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:803)
        at org.postgresql.jdbc.PgConnection.createStatement(PgConnection.java:1615)
        at org.postgresql.jdbc.PgConnection.createStatement(PgConnection.java:410)
        at com.zaxxer.hikari.proxy.ConnectionProxy.createStatement(ConnectionProxy.java:226)
        at com.zaxxer.hikari.proxy.ConnectionJavassistProxy.createStatement(ConnectionJavassistProxy.java)
        at org.intermine.bio.dataconversion.FlyBaseIdResolverFactory.createFromDb(FlyBaseIdResolverFactory.java:215)
        ... 49 more

```

**Comment by julie-sullivan** [comment]
Fixed by https://github.com/intermine/intermine/commit/18634aa5530f5283693cd6b2e5112d7338215db0#diff-7ab9b6c1ea056e313f32d1c9384a9acd
