### ISSUE TITLE
Gradle: non fatal logging error

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1793]
```
Exception in thread "Thread-44" java.lang.ExceptionInInitializerError
        at org.intermine.sql.writebatch.BatchWriterPostgresCopyImpl.doInserts(BatchWriterPostgresCopyImpl.java:100)
        at org.intermine.sql.writebatch.BatchWriterSimpleImpl.write(BatchWriterSimpleImpl.java:77)
        at org.intermine.sql.writebatch.Batch.backgroundFlush(Batch.java:273)
        at org.intermine.sql.writebatch.Batch.backgroundFlush(Batch.java:253)
        at org.intermine.sql.writebatch.Batch.close(Batch.java:314)
        at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.close(ObjectStoreInterMineImpl.java:1060)
        at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.shutdown(ObjectStoreInterMineImpl.java:1099)
        at org.intermine.util.ShutdownHook.shutdown(ShutdownHook.java:84)
        at org.intermine.util.ShutdownHook.run(ShutdownHook.java:99)
Caused by: java.lang.ClassCastException: org.apache.logging.log4j.simple.SimpleLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext
        at org.apache.log4j.Logger$PrivateManager.getContext(Logger.java:59)
        at org.apache.log4j.Logger.getLogger(Logger.java:41)
        at org.intermine.sql.writebatch.FlushJobPostgresCopyImpl.<clinit>(FlushJobPostgresCopyImpl.java:27)
```

**Comment by julie-sullivan** [comment]
Whilst running a build:

```
starting command: /data/code/flyminebuild/flymine/gradlew --stacktrace --no-daemon integrate -Psource=entrez-organism

Exception in thread "Thread-44" java.lang.ExceptionInInitializerError
        at org.intermine.sql.writebatch.BatchWriterPostgresCopyImpl.doInserts(BatchWriterPostgresCopyImpl.java:100)
        at org.intermine.sql.writebatch.BatchWriterSimpleImpl.write(BatchWriterSimpleImpl.java:77)
        at org.intermine.sql.writebatch.Batch.backgroundFlush(Batch.java:273)
        at org.intermine.sql.writebatch.Batch.backgroundFlush(Batch.java:253)
        at org.intermine.sql.writebatch.Batch.close(Batch.java:314)
        at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.close(ObjectStoreInterMineImpl.java:1060)
        at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.shutdown(ObjectStoreInterMineImpl.java:1099)
        at org.intermine.util.ShutdownHook.shutdown(ShutdownHook.java:84)
        at org.intermine.util.ShutdownHook.run(ShutdownHook.java:99)
Caused by: java.lang.ClassCastException: org.apache.logging.log4j.simple.SimpleLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext
        at org.apache.log4j.Logger$PrivateManager.getContext(Logger.java:59)
        at org.apache.log4j.Logger.getLogger(Logger.java:41)
        at org.intermine.sql.writebatch.FlushJobPostgresCopyImpl.<clinit>(FlushJobPostgresCopyImpl.java:27)
        ... 9 more

-- snip --

Thu 19 Apr 23:20:56 BST 2018

starting command: /data/code/flyminebuild/flymine/gradlew --stacktrace --no-daemon integrate -Psource=update-publications

```
