### ISSUE TITLE
Keyword search: fatal error if index is not unpacked properly

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1801]
We need to check the index is unpacked properly. Recently a mine did not have enough space for the index to be written to disk but there were no error messages. The log message says it was written successfully:

```
95902 [http-bio-8080-exec-1172] INFO org.intermine.api.lucene.KeywordSearch  - 
Successfully restored search index information from database in 8 ms
```

Maybe it wrote to disk but could not unzip?

Ask @nuin for details.

**Comment by nuin** [comment]
The error I was getting was this

```
ostprocess:
[postprocess] Found 9 post-processes
[postprocess] Performing postprocess: create-search-index
[postprocess] Creating lucene index for keyword search...
[postprocess] Exception in thread "Lucene Merge Thread #2" org.apache.lucene.index.MergePolicy$MergeException: java.io.IOException: No space left on device
[postprocess]   at org.apache.lucene.index.ConcurrentMergeScheduler.handleMergeException(ConcurrentMergeScheduler.java:347)
[postprocess]   at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:312)
[postprocess] Caused by: java.io.IOException: No space left on device
[postprocess]   at java.io.RandomAccessFile.writeBytes0(Native Method)
[postprocess]   at java.io.RandomAccessFile.writeBytes(RandomAccessFile.java:520)
[postprocess]   at java.io.RandomAccessFile.write(RandomAccessFile.java:550)
[postprocess]   at org.apache.lucene.store.SimpleFSDirectory$SimpleFSIndexOutput.flushBuffer(SimpleFSDirectory.java:187)
[postprocess]   at org.apache.lucene.store.BufferedIndexOutput.writeBytes(BufferedIndexOutput.java:63)
[postprocess]   at org.apache.lucene.store.IndexOutput.writeBytes(IndexOutput.java:43)
[postprocess]   at org.apache.lucene.index.SegmentMerger.mergeNorms(SegmentMerger.java:727)
[postprocess]   at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:155)
[postprocess]   at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4359)
[postprocess]   at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3965)
[postprocess]   at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:231)
[postprocess]   at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:288)```

but the process would return successful on the last line of the output. When using an automated build, the process, even though failing, would allow the build to proceed due to the final output.

**Comment by julie-sullivan** [comment]
The error `No space left on device` is pretty clear. I'm going to close this for now, and ask that @danielabutano make sure there is proper error handling in the new search.

**Comment by nuin** [comment]
Main problem were the process ending as a `Success` and the error being far up. We basically use tmux on AWS so scrolling is limited. When I piped the stdout/stderr to a file, I was able to find the problem.
