### ISSUE TITLE
./gradlew buildUserDB doesn't create superuser

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1816]
I've been able to build a war under v2. However, the buildUserDB task is not creating the initial superuser, which makes the webapp crash during initialization:
```
08-Jun-2018 16:02:32.387 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.loadOnStartup Servlet [action] in web application [/soymine] threw load() exception
 javax.servlet.UnavailableException: Cannot set superuser.account 'shokin@ncgr.org' to be superuser. Does this profile exist?
	at org.apache.struts.action.ActionServlet.init(ActionServlet.java:402)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4962)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5274)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1856)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
However, v1 ant build-db-userprofile does still create that user:
```
userprofile-soymine=> select * from userprofile ;
 superuser |   id    |                                         password                                         |    username     | apikey | localaccount 
-----------+---------+------------------------------------------------------------------------------------------+-----------------+--------+--------------
 t         | 1000000 | 6huDGqW3f7sKoLq9WSdPSGE/i9fnJJsto2QysaxMTMk=o17xRRhKgclvpfdqjJ42gXcSciJ0KMfAET4rc7IV4/0= | shokin@ncgr.org |        | t
```
After which the webapp does fire up (there are other issues, but there's at least a running webapp there).

**Comment by julie-sullivan** [comment]
@sammyjava Nice catch! I missed that one. I've pushed my fix, try that? Thanks!!

**Comment by sammyjava** [comment]
Yup, it works!
