### ISSUE TITLE
DNaseI_hypersensitive_site (SO:0000685) misspelled

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1828]
What is in the NCBI GFF file:

	DNaseI_hypersensitive_site

https://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/GFF/

What is in the SO file:

	DNAseI_hypersensitive_site

http://www.sequenceontology.org/browser/current_svn/term/SO:0000685

This is causing errors. 

I have contacted the proper authorities. Tell @rachellyne

**Comment by julie-sullivan** [comment]
See https://github.com/intermine/humanmine/commit/c4028f9ec773dcf8c3385c70d45885348c10c3a6 for more new types added

**Comment by julie-sullivan** [comment]
I have done a search and replace on the text file for now.

`sed -i -e 's/DNAseI_hypersensitive_site/DNaseI_hypersensitive_site/g' ref_GRCh38.p12_top_level.gff3`

**Comment by julie-sullivan** [comment]
From the NCBI:

```
We have addressed this. For human, we have an updated interim 
annotation file representing the current state of curation as of late January posted at:
ftp://ftp.ncbi.nlm.nih.gov/genomes/Homo_sapiens/GRCh38_interim_annotation/

That GFF3 file picks up the changes to SO types, as well as some other improvements.

On /genomes/all/ we will re-dump the *latest* assemblies, so files for older assemblies 
that happen to have the non-standard SO term won't be updated. Those
 re-dumps will probably start in a month.
```

**Comment by julie-sullivan** [comment]
this is still an issue apparently.

```
Caused by: java.lang.IllegalArgumentException: no class found in model for: DNaseIHypersensitiveSite (original GFF record type: DNaseI_hypersensitive_site) for record: <GFF3Record: sequenceID: NC_000001.11 source: Curated Genomic type: DNaseI_hypersensitive_site start: 5742551 end: 5743135 score: null strand: null phase: null attributes: {ID=[id7999], Dbxref=[GeneID:108281186], Note=[region containing the chr1.1353 DHS; the nucleotide coordinates are approximate for this feature], experiment=[EXISTENCE:in vivo cleavage assay evidence [ECO:0001075][PMID:22955617]], gbkey=[regulatory], regulatory_class=[DNase_I_hypersensitive_site]}>
        at org.intermine.bio.dataconversion.GFF3Converter.process(GFF3Converter.java:327)
        at org.intermine.bio.dataconversion.GFF3Converter.parse(GFF3Converter.java:256)
        at org.intermine.bio.task.GFF3ConverterTask.execute(GFF3ConverterTask.java:249)
        ... 42 more

```

**Comment by julie-sullivan** [comment]
```
Validating gff3 file...
Result : Invalid File!!
Error:
	1. unknown feature type 'recombination_region' at line 1054139
```

**Comment by julie-sullivan** [comment]
Should use this instead:

ftp://ftp.ncbi.nlm.nih.gov/genomes/Homo_sapiens/GRCh38_interim_annotation/
