### ISSUE TITLE
when trying to create a list with the same name as another list via api, give informative error

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1835]
right now you simply get a 400 bad request when you try to use the same name twice, which can be a bit confusing - I initially thought the server had gone down or something when the error came up in a python tutorial.

Demo: https://github.com/yochannah/python-bug-demo/blob/master/demo.ipynb

**Comment by julie-sullivan** [comment]
Via the iodocs, you get at 500 error but no error message. In the logs:

```
2018-10-23 09:36:23 ERROR org.intermine.webservice.server.WebService  [] - Service failed by internal error. Request parameters: 
oldname: Gene_Orth
newname: monkey1
org.intermine.api.profile.ProfileAlreadyExistsException: Attempting to rename a bag to a new name that already exists: monkey1

  at org.intermine.api.profile.Profile.renameBag(Profile.java:763)
  at org.intermine.webservice.server.lists.ListRenameService.execute(ListRenameService.java:53)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.core.WebServiceServlet.respond(WebServiceServlet.java:73)
  at org.intermine.webservice.server.core.WebServiceServlet.doGet(WebServiceServlet.java:114)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
```

Here's a valid query to run:

```
<query name="" model="genomic" view="Gene.id" longDescription="">   <constraint path="Gene.primaryIdentifier" op="=" value="FBgn0259864"/> </query>
```

If you put in a bad path, you _do_ get the correct error message:

```
"executionTime":"2018.10.23 09:44::16","wasSuccessful":false,"error":"XML is well formatted but query contains errors:\nPath Gene.badPath in constraint is not in the model.\n","statusCode":400}
```

Also, it let's you create a list of zero, which I think is wrong too.

**Comment by uosl** [comment]
Adding the Bluegenes label as this has negative effects on the interface.

**Comment by danielabutano** [comment]
Now the ws returns 400 + nice user message error.
In addition replaceExisting has been fixed
