### ISSUE TITLE
Gradle: FASTA export fails

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1846]
FASTA export fails:

```
SEVERE: Servlet.service() for servlet [action] in context with path [/biotestmine] threw exception [Servlet execution threw an exception] with root cause
java.lang.ClassNotFoundException: org.biojava.nbio.core.sequence.template.Sequence
        at org.akhikhl.gretty.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:60)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at org.apache.struts.util.RequestUtils.applicationInstance(RequestUtils
```

[BUT `biojava-core` is in the list of dependencies. ](https://github.com/julie-sullivan/intermine/blob/release-candidate/bio/webapp/build.gradle#L41)

* Wrong JAR?
* Wrong place for dependency? 
* Is that JAR available to the webapp at runtime?

BED, GFF and tab/comma exports work as expected.

**Comment by julie-sullivan** [comment]
Get this on the list page:
```
Caused by: java.lang.NoClassDefFoundError: org/biojava/nbio/core/sequence/template/AbstractSequence
        at org.intermine.bio.web.export.SequenceHttpExporter.canExport(SequenceHttpExporter.java:185) ~[classes/:na]
        at org.intermine.web.struts.ExportController.execute(ExportController.java:77) ~[classes/:na]
```

**Comment by julie-sullivan** [comment]
```
11-Jul-2018 11:08:19.915 SEVERE [http-nio-8080-exec-26] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [action] in context with path [/flymine] threw exception [Servlet execution threw an exception] with root cause
 java.lang.ClassNotFoundException: org.biojava.nbio.core.sequence.template.AbstractSequence
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
        at org.intermine.bio.web.export.SequenceHttpExporter.export(SequenceHttpExporter.java:125)
        at org.intermine.bio.web.struts.GenomicRegionSearchAjaxAction.exportFeatures(GenomicRegionSearchAjaxAction.java:4
```

**Comment by julie-sullivan** [comment]
This is what I think is happening. 

* `bio-core` depends on `biojava-core.jar`
* `bio-webapp` depends on `biojava-core.jar` 
* `bio-webapp` depends on `bio-core` but using the WAR plugin's `providedCompile` -- which means `bio-core.jar` will not be included in the WAR

Since `bio-core.jar` is excluded from the WAR, I think gradle is also excluding `biojava-core.jar`.

I made the two packages (bio-core and bio-webapp) use different versions but this is a temporary (dumb) fix. There is a way to use the same version for both, but I haven't found it yet.

**Comment by julie-sullivan** [comment]
Removed biojava-core.jar from `bio-core`'s build file. Looks to be okay?

**Comment by danielabutano** [comment]
> Removed biojava-core.jar from `bio-core`'s build file. Looks to be okay?

Or set the transitive property to false in biowebapp
providedCompile (project(':bio-core'))  { transitive = false }
