### ISSUE TITLE
Error parsing DOES NOT CONTAIN constraint

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1847]
Originally reported by @jmacneal - the DOES_NOT_CONTAIN constraint doesn't appear to work.

Here's a query that works in humanmine: 

```xml
<query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.name Gene.goAnnotation.ontologyTerm.identifier Gene.goAnnotation.ontologyTerm.name Gene.organism.shortName" sortOrder="Gene.symbol ASC" constraintLogic="A and B" >
  <constraint path="Gene.goAnnotation.ontologyTerm.name" op="CONTAINS" value="DNA binding" code="A" />
  <constraint path="Gene.organism.shortName" op="=" value="H. sapiens" code="B" />
</query>
```

flip that to DOES NOT CONTAIN, and we'll get `[ERROR] 500 Service failed. Please contact support`: 

```xml
<query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.name Gene.goAnnotation.ontologyTerm.identifier Gene.goAnnotation.ontologyTerm.name Gene.organism.shortName" sortOrder="Gene.symbol ASC" constraintLogic="A and B" >
  <constraint path="Gene.goAnnotation.ontologyTerm.name" op="DOES NOT CONTAIN" value="DNA binding" code="A" />
  <constraint path="Gene.organism.shortName" op="=" value="H. sapiens" code="B" />
</query>
```
I went hunting to make sure DOES NOT CONTAIN is a thing, and it is: https://github.com/intermine/intermine/blob/3ae2631dbe244a029baf9d369510bd87e49ac927/intermine/objectstore/main/src/org/intermine/objectstore/query/ContainsConstraint.java 

Also tried DOES_NOT_CONTAIN, but this one says `[ERROR] 400 XML is not well formatted`

**Comment by julie-sullivan** [comment]
```
2018-10-22 12:36:41 ERROR org.intermine.webservice.server.WebService  [] - Service failed by internal error. Request parameters: 
query: <query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.name Gene.goAnnotation.ontologyTerm.identifier Gene.goAnnotation.ontologyTerm.name Gene.organism.shortName" sortOrder="Gene.symbol ASC" constraintLogic="A and B" >
  <constraint path="Gene.goAnnotation.ontologyTerm.name" op="DOES NOT CONTAIN" value="DNA binding" code="A" />
  <constraint path="Gene.organism.shortName" op="=" value="H. sapiens" code="B" />
</query>
size: 10
java.lang.IllegalArgumentException: Invalid constraint: org.intermine.objectstore.query.QueryExpression@3965ccb6 (a java.lang.String) DOES NOT CONTAIN java.lang.String: "dna binding" (a java.lang.String)

  at org.intermine.objectstore.query.SimpleConstraint.<init>(SimpleConstraint.java:68)
  at org.intermine.api.query.MainHelper.makeQueryStringConstraint(MainHelper.java:927)
  at org.intermine.api.query.MainHelper.putConstraintsInMap(MainHelper.java:569)
  at org.intermine.api.query.MainHelper.makeQuery(MainHelper.java:355)
  at org.intermine.api.query.MainHelper.makeQuery(MainHelper.java:137)
  at org.intermine.api.query.PathQueryExecutor.makeQuery(PathQueryExecutor.java:156)
  at org.intermine.api.query.PathQueryExecutor.execute(PathQueryExecutor.java:125)
  at org.intermine.webservice.server.query.result.QueryResultService.runResults(QueryResultService.java:336)
  at org.intermine.webservice.server.query.result.QueryResultService.runPathQuery(QueryResultService.java:302)
  at org.intermine.webservice.server.query.result.QueryResultService.execute(QueryResultService.java:106)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.query.result.QueryResultServlet.runService(QueryResultServlet.java:61)
  at org.intermine.webservice.server.query.result.QueryResultServlet.doGet(QueryResultServlet.java:36)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)

```
