### ISSUE TITLE
cargo task doesn't use port given in .intermine/mymine.properties

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1858]
I've got Tomcat listening to a non port-80 for the manager, but the cargo tasks assume port 80, even though I've got the port specified in ./intermine/soymine.properties:
```
webapp.deploy.url=http://localhost:8082
webapp.path=soymine
webapp.port=8082
```
Here's what ./gradlew cargoRedeployRemote throws, showing 80 rather than 8082:
```
Caused by: org.codehaus.cargo.container.ContainerException: Failed to redeploy [/home/shokin/soymine/webapp/build/libs/webapp.war]
        at org.codehaus.cargo.container.tomcat.internal.AbstractTomcatManagerDeployer.redeploy(AbstractTomcatManagerDeployer.java:188)
        at org.codehaus.cargo.ant.CargoTask.executeActions(CargoTask.java:794)
        at org.codehaus.cargo.ant.CargoTask.execute(CargoTask.java:572)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        ... 48 more
Caused by: java.io.FileNotFoundException: http://localhost:80/manager/text/list
```

**Comment by sammyjava** [comment]
This is also true if I supply webapp.hostname, by the way.

**Comment by julie-sullivan** [comment]
So did this fix it:

```
  def remotePort = 80
  if (props.hasProperty("webapp.port")) {
    remotePort = props.getProperty("webapp.port")
  }
```

**Comment by sammyjava** [comment]
YUP, your update works. Thanks!
