### ISSUE TITLE
Gradle: can't redeploy webapp

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1873]
I am getting the same error on my local machine that I got on our flymine server:

```
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42) ~[log4j-slf4j-impl-2.5.jar:2.5]
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46) ~[log4j-api-2.10.0.jar:2.10.0]
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29) ~[log4j-slf4j-impl-2.5.jar:2.5]
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358) ~[slf4j-api-1.7.25.jar:1.7.25]
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383) ~[slf4j-api-1.7.25.jar:1.7.25]
        at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[HikariCP-3.2.0.jar:?]
        at org.intermine.sql.Database.<init>(Database.java:121) ~[intermine-objectstore-2.0.0-RC-01.jar:?]
        at org.intermine.sql.DatabaseFactory.getDatabase(DatabaseFactory.java:54) ~[intermine-objectstore-2.0.0-RC-01.jar:?]
        at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.getInstance(ObjectStoreInterMineImpl.java:356) ~[intermine-objectstore-2.0.0-RC-01.jar:?]
        ... 61 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.util.ReflectionUtil
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285) ~[catalina.jar:8.5.20]
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119) ~[catalina.jar:8.5.20]
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42) ~[log4j-slf4j-impl-2.5.jar:2.5]
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46) ~[log4j-api-2.10.0.jar:2.10.0]
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29) ~[log4j-slf4j-impl-2.5.jar:2.5]
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358) ~[slf4j-api-1.7.25.jar:1.7.25]
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383) ~[slf4j-api-1.7.25.jar:1.7.25]
        at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[HikariCP-3.2.0.jar:?]
        at org.intermine.sql.Database.<init>(Database.java:121) ~[intermine-objectstore-2.0.0-RC-01.jar:?]
        at org.intermine.sql.DatabaseFactory.getDatabase(DatabaseFactory.java:54) ~[intermine-objectstore-2.0.0-RC-01.jar:?]
        at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.getInstance(ObjectStoreInterMineImpl.java:356) ~[intermine-objectstore-2.0.0-RC-01.jar:?]
        ... 61 more
2018-08-07 09:13:53 ERROR org.apache.struts.action.ActionServlet  [] - Unable to initialize Struts ActionServlet due to an unexpected exception or error thrown, so marking the servlet as unavailable.  Most likely, this is due to an incorrect or missing library dependency.
javax.servlet.ServletException: Production object store is null
        at org.intermine.web.struts.InitialiserPlugin.init(InitialiserPlugin.java:162) ~[classes/:?]

```

It looks like the Hikari log library is maybe conflicting with another log library?

This is a recent issue. What has changed?

**Comment by julie-sullivan** [comment]
I tried reverting this change but no luck. Hikari must not be the issue: https://github.com/intermine/intermine/commit/dca62c83a1c92e76a742e24a1a22fc6e3b19a1d0

**Comment by sammyjava** [comment]
If it's of any help, my current revision is a-cargo-ing just fine.

https://github.com/sammyjava/intermine

It's only 5 commits behind RC1.

**Comment by julie-sullivan** [comment]
@sammyjava thanks! That is helpful. I am only seeing this error on the FlyMine production server and my local workstation, all other servers and workstations are fine. But it only started today!

**Comment by julie-sullivan** [comment]
To fix I added a JAR that hikari needs but I now get this message:

```
> Task :webapp:summariseObjectStore
[summarizeObjectStore] SLF4J: Class path contains multiple SLF4J bindings.
[summarizeObjectStore] SLF4J: Found binding in [jar:file:/local-homes/julie/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.7/8095d0b9f7e0a9cd79a663c740e0f8fb31d0e2c8/slf4j-simple-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[summarizeObjectStore] SLF4J: Found binding in [jar:file:/local-homes/julie/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-jdk14/1.7.10/13675a57601d9106fe82314fe9eebb9b2d9b13c6/slf4j-jdk14-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[summarizeObjectStore] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
```
