### ISSUE TITLE
Gradle: bio services aren't being listed on the services listing

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1875]
`beta.humanmine.org/beta/service ` - leaves out FASTA GFF and BED related services.

The `web.xml` file in the WAR has the FASTA etc services being listed so what went wrong?

**Comment by julie-sullivan** [comment]
`web-bio.xml` isn't being merged in. `web-model` is though!

**Comment by julie-sullivan** [comment]
Fixed the merging but then this happened:

```
Caused by: java.lang.IllegalArgumentException: The servlets named [ws-gff3-query] and [gff3-query] are both mapped to the url-pattern [/service/query/results/gff3] which is not permitted
        at org.apache.tomcat.util.descriptor.web.WebXml.addServletMappingDecoded(WebXml.java:325)
        at org.apache.tomcat.util.descriptor.web.WebXml.addServletMapping(WebXml.java:318)
        ... 68 more

```
