### ISSUE TITLE
Users can't login occasionally

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1877]
From @kkarra: 

```
Every so often a user cannot login to the mine., I restart tomcat and that fixes it. 
```

Here's the error in the logs:

```
[ajp-nio-8019-exec-15] WARN com.zaxxer.hikari.proxy.ConnectionProxy - Connection org.postgresql.jdbc.PgConnection@30e03869 (db.userprofile-production) marked as broken because of SQLSTATE(08003), ErrorCode(0).
org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:803)
	at org.postgresql.jdbc.PgConnection.getAutoCommit(PgConnection.java:764)
	at com.zaxxer.hikari.proxy.ConnectionJavassistProxy.getAutoCommit(ConnectionJavassistProxy.java)
	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.createTempBagTables(ObjectStoreInterMineImpl.java:1449)
	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1160)
	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1131)
	at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.execute(ObjectStoreWriterInterMineImpl.java:1691)
	at org.intermine.objectstore.ObjectStoreAbstractImpl.getObjectByExample(ObjectStoreAbstractImpl.java:369)
	at org.intermine.api.profile.ProfileManager.getUserProfile(ProfileManager.java:912)
	at org.intermine.api.profile.ProfileManager.hasProfile(ProfileManager.java:246)
	at org.intermine.web.struts.LoginForm.validate(LoginForm.java:101)
	at org.apache.struts.action.RequestProcessor.processValidate(RequestProcessor.java:950)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:198)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:462)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.intermine.web.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:139)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:868)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Aug 13, 2018 10:17:37 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [action] in context with path [/yeastmine] threw exception
java.lang.RuntimeException: Unable to load user profile
	at org.intermine.api.profile.ProfileManager.getUserProfile(ProfileManager.java:914)
	at org.intermine.api.profile.ProfileManager.hasProfile(ProfileManager.java:246)
	at org.intermine.web.struts.LoginForm.validate(LoginForm.java:101)
	at org.apache.struts.action.RequestProcessor.processValidate(RequestProcessor.java:950)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:198)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:462)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.intermine.web.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:139)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:868)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.intermine.objectstore.ObjectStoreException: database error while creating temporary table for bag
	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.createTempBagTables(ObjectStoreInterMineImpl.java:1485)
	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1160)
	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1131)
	at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.execute(ObjectStoreWriterInterMineImpl.java:1691)
	at org.intermine.objectstore.ObjectStoreAbstractImpl.getObjectByExample(ObjectStoreAbstractImpl.java:369)
	at org.intermine.api.profile.ProfileManager.getUserProfile(ProfileManager.java:912)
	... 33 more
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:803)
	at org.postgresql.jdbc.PgConnection.getAutoCommit(PgConnection.java:764)
	at com.zaxxer.hikari.proxy.ConnectionJavassistProxy.getAutoCommit(ConnectionJavassistProxy.java)
	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.createTempBagTables(ObjectStoreInterMineImpl.java:1449)
	... 38 more
```

**Comment by julie-sullivan** [comment]
@kkarra Have you had any luck with this? Is this still a problem?

**Comment by kkarra** [comment]
haven't seen this problem lately..

**Comment by julie-sullivan** [comment]
Okay let's close but reopen if it starts happening again! (maybe it was a temporary network issue?)

**Comment by aturling** [comment]
I know this is closed but I am experiencing this on all of our InterMine instances whenever PostgreSQL has been restarted without also restarting Tomcat (e.g., PostgreSQL gets updated).

Here's the error after attempting to log in once the database has been restarted:

```
WARN  com.zaxxer.hikari.pool.ProxyConnection  [] - db.userprofile-production - Connection org.postgresql.jdbc.PgConnection@5a820330 marked as broken because of SQLSTATE(57P01), ErrorCode(0)
org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224) ~[postgresql-42.2.2.jar:42.2.2]
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:111) [HikariCP-3.2.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java) [HikariCP-3.2.0.jar:?]
	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1222) [intermine-objectstore-5.1.0.jar:?]
	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.executeWithConnection(ObjectStoreInterMineImpl.java:1123) [intermine-objectstore-5.1.0.jar:?]
	at org.intermine.objectstore.intermine.ObjectStoreWriterInterMineImpl.execute(ObjectStoreWriterInterMineImpl.java:1691) [intermine-objectstore-5.1.0.jar:?]
	at org.intermine.objectstore.ObjectStoreAbstractImpl.getObjectByExample(ObjectStoreAbstractImpl.java:368) [intermine-objectstore-5.1.0.jar:?]
	at org.intermine.api.profile.ProfileManager.getUserProfile(ProfileManager.java:915) [intermine-api-5.1.0.jar:?]
```

Restarting Tomcat fixes it but I have to monitor for this error to know when to restart it.
