### ISSUE TITLE
IODocs error: /sequence returns 500 by default

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1885]
If you enter a start and end and leave the query as-is, you get a 500 error. 

If you copy/paste, the web service runs just fine.

**Comment by julie-sullivan** [comment]
```
2018-09-07 15:12:36 ERROR org.intermine.webservice.server.WebService  [] - Service failed by internal error. Request parameters: 
end: 100000
query:  <query model="genomic" view="Chromosome.sequence.residues">     <constraint path="Chromosome" op="LOOKUP" value="X" extraValue="D. melanogaster"/> </query>
org.intermine.webservice.server.exceptions.ServiceException: org.json.JSONException: A JSONObject text must begin with '{' at 2 [character 3 line 1]

  at org.intermine.webservice.server.query.result.PathQueryBuilder.buildJSONQuery(PathQueryBuilder.java:93)
  at org.intermine.webservice.server.query.result.PathQueryBuilder.<init>(PathQueryBuilder.java:70)
  at org.intermine.webservice.server.clob.SequenceService.getQuery(SequenceService.java:187)
  at org.intermine.webservice.server.clob.SequenceService.execute(SequenceService.java:88)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.core.WebServiceServlet.respond(WebServiceServlet.java:73)
  at org.intermine.webservice.server.core.WebServiceServlet.doGet(WebServiceServlet.java:114)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
 ...
 caused by: org.json.JSONException: A JSONObject text must begin with '{' at 2 [character 3 line 1]

  at org.json.JSONTokener.syntaxError(JSONTokener.java:451)
  at org.json.JSONObject.<init>(JSONObject.java:196)
  at org.json.JSONObject.<init>(JSONObject.java:320)
  at org.intermine.webservice.server.query.result.PathQueryBuilder.buildJSONQuery(PathQueryBuilder.java:82)
  at org.intermine.webservice.server.query.result.PathQueryBuilder.<init>(PathQueryBuilder.java:70)
  at org.intermine.webservice.server.clob.SequenceService.getQuery(SequenceService.java:187)
  at org.intermine.webservice.server.clob.SequenceService.execute(SequenceService.java:88)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.core.WebServiceServlet.respond(WebServiceServlet.java:73)
  at org.intermine.webservice.server.core.WebServiceServlet.doGet(WebServiceServlet.java:114)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
 ...
```

**Comment by julie-sullivan** [comment]
There was a space in the config. I deleted it and now it works fine.
