### ISSUE TITLE
FlyMine: alleles priorities aren't being set properly

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1898]
I got an error because allele sequence ontology term is different for FlyBase (gene) and FlyBase-alleles (Allele). 

So I set the priority to be 

```
# FlyMine's genomic_priorities.properties
SequenceFeature.sequenceOntologyTerm = chado-db-flybase-dmel, uniprot, drosdel-gff, long-oligo, miranda, *
# added this line
Allele.sequenceOntologyTerm = flybase-alleles, chado-db-flybase-dmel, *
```

Note that `SequenceFeature.sequenceOntologyTerm` should have covered that case, really. But I added the allele anyway to be more specific.

I got this error:

```
Caused by: java.lang.IllegalArgumentException: There are multiple priorities configured for org.intermine.model.bio.Allele.sequenceOntologyTerm. Found a match on Allele.sequenceOntologyTerm and SequenceFeature.sequenceOntologyTerm
        at org.intermine.dataloader.PriorityConfig.getPriorities(PriorityConfig.java:120)
        at org.intermine.dataloader.PriorityConfig.<init>(PriorityConfig.java:70)
        at org.intermine.dataloader.IntegrationWriterDataTrackingImpl.<init>(IntegrationWriterDataTrackingImpl.java:178)
        ... 44 more

```

So it seems the check for duplicates is treating allele as a sequence feature but the actual integration is not.

**Comment by julie-sullivan** [comment]
```
Caused by: java.lang.RuntimeException: Exception while dataloading - to allow multiple errors, set the property "dataLoader.allowMultipleErrors" to true
Problem while loading item identifier 3_2962 because
Conflicting values for field Allele.sequenceOntologyTerm between chado-db-flybase-dmel (value "SOTerm [description=null, id=1000003, identifier=null, name="gene", namespace=null, obsolete=null, ontology=1000001]" in database with ID 3604463) and flybase-alleles (value "SOTerm [description=null, id=38016303, identifier=null, name="allele", namespace=null, obsolete=null, ontology=1000001]" being stored). This field needs configuring in the genomic_priorities.properties file
        at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:173)
        at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:60)
        at org.intermine.dataloader.ObjectStoreDataLoaderTask.execute(ObjectStoreDataLoaderTask.java:127)
        ... 40 more
Caused by: java.lang.IllegalArgumentException: Conflicting values for field Allele.sequenceOntologyTerm between chado-db-flybase-dmel (value "SOTerm [description=null, id=1000003, identifier=null, name="gene", namespace=null, obsolete=null, ontology=1000001]" in database with ID 3604463) and flybase-alleles (value "SOTerm [description=null, id=38016303, identifier=null, name="allele", namespace=null, obsolete=null, ontology=1000001]" being stored). This field needs configuring in the genomic_priorities.properties file
        at org.intermine.dataloader.SourcePriorityComparator.compare(SourcePriorityComparator.java:278)
        at org.intermine.dataloader.SourcePriorityComparator.compare(SourcePriorityComparator.java:34)
        at org.intermine.dataloader.IntegrationWriterDataTrackingImpl.store(IntegrationWriterDataTrackingImpl.java:369)
        at org.intermine.dataloader.IntegrationWriterAbstractImpl.store(IntegrationWriterAbstractImpl.java:187)
        at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:151)
        ... 42 more

```

**Comment by julie-sullivan** [comment]
worked correctly for last build
