### ISSUE TITLE
503 error loading localhost on gradle build of InterMine

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine#1903]
Logging this so we have a record in the future, although it's solved.

When I deploy a gradle version of InterMine on my local Tomcat, the deploy logs several errors to the console and returns 503 when I try to visit the InterMine in my browser. This happened with both HumanMine and Flymine. The stacktrace is at the end of this issue

### What fixed it: 

It turned out to be a permissions-related issue - my `~/.gradle` and `~/.m2` folders were on a remote drive that was mounted over the network to be my home directory, while my Tomcat was on the root of my local machine. The answer to the problem was to move Tomcat to my home directory, i.e. `~/apache-tomcat-8.x.x` - it seemingly needed to be in the same physical drive as the dependencies for my build. 
 
### Things that didn't fix it: 

- deleting all dependencies from `~/.gradle` and `~/.m2` and compiling from scratch 
- restarting tomcat
- trying a different version of tomcat.
- pointing to different postgres instances
- changing from Oracle java to OpenJDK and back again

The war I built also could deploy successfully on other people's Tomcats, a strong indicator that my issue was environment-related.

Interestingly, no log4j logs (including errors) ever made it into log files, making the errors fail semi-silently - while there were errors in the logs, there SHOULD have been a lot more than there were.  

### The error in localhost.2018-some-date.log:  

```java
05-Oct-2018 13:31:39.759 SEVERE [http-nio-8080-exec-21] org.apache.catalina.session.StandardSession.tellNew Session event listener threw exception
 java.lang.NullPointerException
	at org.intermine.web.logic.session.SessionMethods.initSession(SessionMethods.java:458)
	at org.intermine.web.logic.session.SessionListener.sessionCreated(SessionListener.java:31)
	at org.apache.catalina.session.StandardSession.tellNew(StandardSession.java:396)
	at org.apache.catalina.session.StandardSession.setId(StandardSession.java:368)
	at org.apache.catalina.session.StandardSession.setId(StandardSession.java:349)
	at org.apache.catalina.session.ManagerBase.createSession(ManagerBase.java:665)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:3039)
	at org.apache.catalina.connector.Request.getSession(Request.java:2429)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:896)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:908)
	at org.apache.jasper.runtime.PageContextImpl.initialize(PageContextImpl.java:137)
	at org.apache.jasper.runtime.JspFactoryImpl.internalGetPageContext(JspFactoryImpl.java:109)
	at org.apache.jasper.runtime.JspFactoryImpl.getPageContext(JspFactoryImpl.java:60)
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:100)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.intermine.web.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:139)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

05-Oct-2018 13:31:39.784 WARNING [http-nio-8080-exec-23] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet [action] is currently unavailable
05-Oct-2018 13:52:21.201 INFO [http-nio-8080-exec-24] org.apache.catalina.core.ApplicationContext.log Marking servlet [action] as unavailable
05-Oct-2018 13:52:21.201 SEVERE [http-nio-8080-exec-24] org.apache.catalina.core.StandardContext.loadOnStartup Servlet [action] in web application [/flymine] threw load() exception
 javax.servlet.UnavailableException: Production object store is null
	at org.apache.struts.action.ActionServlet.init(ActionServlet.java:402)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1183)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1099)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:989)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4931)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5241)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:507)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1654)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1483)
	at org.apache.catalina.manager.ManagerServlet.deploy(ManagerServlet.java:731)
	at org.apache.catalina.manager.ManagerServlet.doPut(ManagerServlet.java:424)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:664)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:595)
	at org.apache.catalina.valves.RequestFilterValve.process(RequestFilterValve.java:348)
	at org.apache.catalina.valves.RemoteAddrValve.invoke(RemoteAddrValve.java:52)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

05-Oct-2018 13:56:21.841 WARNING [http-nio-8080-exec-33] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet [action] is currently unavailable

```

**Comment by nuin** [comment]
@yochannah I am having the same problem locally and my Tomcat is in the same drive as the code or .gradle. Error is only reported on Tomcat's localhost log, not on Catalina.out.

I am investigating on my side.

**Comment by yochannah** [comment]
@nuin Any luck so far? Not sure if it helps but I had a similar issue some years back where the solution was to make sure my files were all on my local machine's disk rather than a remote mounted network drive (basically the exact opposite of the solution I mentioned above :laughing:).

**Comment by nuin** [comment]
@yochannah All my files are local, Tomcat is in /opt and Intermine in another dir in the same disk. I am still trying.

**Comment by pengchy** [comment]
@yochannah and @nuin Have you found the solution? I am having the same problem with my Tomcat and Postgres run on the same local directory. Furthermore, another Mine run on the same Tomcat/InterMine/Postgres works quite well.

The error status is:
1) successfully deploy the Mine, but visiting the webpag returned http error 503
2) only localhost.xxxx-xx-xx.log file returned error message and said:
`23-Feb-2020 11:53:33.996 WARNING [http-nio-10.4.0.17-8080-exec-65] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet [action] is currently unavailable`

I very appreciate any helpful information.

**Comment by nuin** [comment]
@pengchy The issue was on some web app configuration files that should not be there when we upgraded from 1.8.5 to 2.x, I am not sure which ones exactly. Sorry.

**Comment by pengchy** [comment]
Hi, it turned out that I have forgotten to perform buildUserDB before deploying the webapp. Thank you!
