### ISSUE TITLE
Solr: error on search

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1959]
Tell @danielabutano @arunans23 

I am getting this error on humanmine:

```

org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server
 at http://localhost:8983/solr/humanmine-search: undefined field classname
at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:643)
at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:255)
at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:244)
at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:194)
at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:974)
at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:990)
at org.intermine.api.searchengine.solr.SolrKeywordSearchHandler.performSearch(SolrKeywordSearchHandler.java:341)
at org.intermine.api.searchengine.solr.SolrKeywordSearchHandler.doKeywordSearch(SolrKeywordSearchHandler.java:65)
at org.intermine.web.struts.KeywordSearchResultsController.execute(KeywordSearchResultsController.java:128)
at org.apache.struts.tiles.actions.TilesAction.execute(TilesAction.java:76)
at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
```

**Comment by julie-sullivan** [comment]
Autocomplete also fails:
```
Error from server at http://localhost:8983/solr/humanmine-autocomplete: undefined field name
```

**Comment by julie-sullivan** [comment]
```
$ curl http://localhost:8983/solr/humanmine-autocomplete/select?q=*
{
  "responseHeader":{
    "status":0,
    "QTime":1,
    "params":{
      "q":"*"}},
  "response":{"numFound":0,"start":0,"docs":[]
  }}
$ curl http://localhost:8983/solr/humanmine-search/select?q=*
{
  "responseHeader":{
    "status":0,
    "QTime":65,
    "params":{
      "q":"*"}},
  "response":{"numFound":52144644,"start":0,"docs":[
      {
        "id":"53295424",
        "_version_":1618429863130038275},
      {
        "id":"53295425",
        "_version_":1618429863131086848},
      {
        "id":"53295426",
        "_version_":1618429863131086849},
      {
        "id":"53295427",
        "_version_":1618429863131086850},
      {
        "id":"53295428",
        "_version_":1618429863131086851},
      {
        "id":"53295429",
        "_version_":1618429863132135424},
      {
        "id":"53295430",
        "_version_":1618429863133184000},
      {
        "id":"53295431",
        "_version_":1618429863133184001},
      {
        "id":"53295432",
        "_version_":1618429863133184002},
      {
        "id":"53295433",
        "_version_":1618429863134232576}]
  }}
```

**Comment by julie-sullivan** [comment]
I tried just copying the `/data` directory over directly but got the same error.

**Comment by julie-sullivan** [comment]
I noticed `managed-schema` files were different. I've copied over that file but that didn't fix it.

Are there more files that I need to update?

**Comment by julie-sullivan** [comment]
I also tried:

* redeploying the webapp
* copying over the data directory, then restoring

Still same errors for both autocomplete and the search.

**Comment by julie-sullivan** [comment]
Okay working now! Here's what I did:

Copied the *entire* `solr-7.2.1` directory from dev server to production server, then ran this command:

`./solr restart`

I am guessing there is a better/faster/easier way? Or do I need to do that every time?

**Comment by arunans23** [comment]
Through my code, I am changing only the managed-schema. Other files should be the default ones. Anyhow I'll try on a server and let you know.

**Comment by julie-sullivan** [comment]
Okay thanks! Good to know. 

I did copy over `managed-schema` but I didn't do a `./solr restart`. Do you think that would have fixed it? 

I'll try that with FlyMine, that's likely what I did wrong.
