### ISSUE TITLE
PathQuery broken in 3.1.0

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1972]
I'm posting this up as an issue now because it is officially a bug: when I install a clean 3.1.0 branch, build it from a clean start, then build biotestmine, path queries hang on the webapp, either as submitted from the Query Builder or run from a standalone program. In both cases, the query times out.

Take a look at this mine:

http://dev.lis.ncgr.org:50030/biotestmine/begin.do

That's with a delete of all the gradle cache; a clean git clone of IM 3.1.0; followed by buildDB, integrate, postprocess, war, deploy.

Try any Query Builder query - it just hangs trying to generate results. No error message to be found.

If I run a pathquery from the command line using the Java API, for a gene with a given primaryIdentifier, I get the same result:
```
http://shokin-webapps:8080/biotestmine/service
PathQuery( view: [Gene.primaryIdentifier], orderBy: [Gene.primaryIdentifier ASC], constraints: {Gene.primaryIdentifier = PFB0405W=A}, logic: A, outerJoinStatus: {}, descriptions: {}, description: null)
Gene.primaryIdentifier
Tue Dec 18 09:39:51 MST 2018
org.intermine.webservice.client.exceptions.ServiceException: executedMethod.getStatusCode()=500; Error while accessing POST http://shokin-webapps:8080/biotestmine/service/query/results, params: {start=[0], query=[<query name="query" model="genomic" view="Gene.primaryIdentifier" longDescription="" sortOrder="Gene.primaryIdentifier asc"><constraint path="Gene.primaryIdentifier" op="=" value="PFB0405W"/></query>], format=[json]}, authorization-token: null, content-type: application/json;char-set:UTF-8, headers: {User-Agent=InterMine-WS-Client-Java-2.0 JavaLibrary/3.01.00, InterMine-Version=3.01.00}
    at org.intermine.webservice.client.util.HttpConnection.checkResponse(HttpConnection.java:227)
    at org.intermine.webservice.client.util.HttpConnection.executeMethod(HttpConnection.java:148)
    at org.intermine.webservice.client.util.HttpConnection.connect(HttpConnection.java:89)
    at org.intermine.webservice.client.core.Service.executeRequest(Service.java:149)
    at org.intermine.webservice.client.services.AbstractQueryService.getRows(AbstractQueryService.java:264)
    at org.intermine.webservice.client.services.QueryService.getRows(QueryService.java:402)
    at org.intermine.webservice.client.services.QueryService.getRows(QueryService.java:83)
    at org.intermine.webservice.client.services.AbstractQueryService.getRowListIterator(AbstractQueryService.java:181)
    at beanmine.QueryClient.main(QueryClient.java:53)
Caused by: org.intermine.webservice.client.exceptions.InternalErrorException: Service failed. Please contact support.
    at org.intermine.webservice.client.util.HttpConnection.handleErrorResponse(HttpConnection.java:274)
    at org.intermine.webservice.client.util.HttpConnection.checkResponse(HttpConnection.java:225)
    ... 8 more
Tue Dec 18 09:42:06 MST 2018
```
Note it just hangs for 2:15 and then quits with "Service failed."

Tomcat version: 8.5.32-1.fc28
webapp OS version: Fedora 28.
(build VM version: Fedora 29).
```
[shokin@shokin-mines biotestmine]$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by sammyjava** [comment]
So, I was able to diff the files from a good ChickpeaMine WAR (which I still had) and the bad ChickpeaMine WAR and actually found the problem. The good version had, in web.properties, imported from .intermine/chickpeamine.properties:

`webapp.baseurl=http://shokin-webapps`

where shokin-webapps=172.20.131.4 (the internal IP for the VM itself)

The BAD version had,

`webapp.baseurl=http://dev.lis.ncgr.org:50030`

where dev.lis.ncr.org=69.71.169.32 (the public IP for the KVM hosts that proxies HTTP requests to shokin-webapps). 

Well, it turns out that the web server can't reach the public IP:port of the KVM host that it's on, **NOW**, due to some recent changes to routing with a new LAN configuration (and sysadmin). It used to be able to with the old LAN configuration.

So, it was a network thing, but perhaps something to put into your "random things to look out for" bucket: even though you can reach the web server from your testing position, that doesn't mean that path queries work, because the web server has to be able to make HTTP requests to itself using the value of `webapp.baseurl`. Other functions, like on the displayers, are not affected by this, which confuses the situation!
