### ISSUE TITLE
HPO errors - can't handle "created_by" metadata

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#1999]
```
2. When I tried integrating HPO:
Caused by: Error: Unrecognized synonym type ID hasDbXref found
on line: 144205 of file:/home/amuszynska/Git/humanmine/data/hpo/2019-02-07/hp.obo
charnum: 8

This file was also downloaded via DataDownloader.
```

**Comment by julie-sullivan** [comment]
I updated the file and didn't get that error. However, I got a new one.

```
[convertOBO] Error: Attempted to set created-by field of object null which does not support modification metadata.
[convertOBO] on line: 17 of file:/micklem/data/hpo/2019-02-13/hp.obo
[convertOBO] charnum: -1
[convertOBO] line: created_by: Sebastian Köhler, Peter Robinson, The Human Phenotype Ontology Consortium, Monarch Initiative
[convertOBO]    at org.obo.dataadapter.DefaultOBOParser.readCreatedBy(DefaultOBOParser.java:1804)
[convertOBO]    at org.obo.dataadapter.OBOParseEngine.parseTagValue(OBOParseEngine.java:579)
[convertOBO]    at org.obo.dataadapter.OBOParseEngine.parseTag(OBOParseEngine.java:977)
[convertOBO]    at org.obo.dataadapter.OBOParseEngine.doParse(OBOParseEngine.java:392)
[convertOBO]    at org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:48)
[convertOBO]    at org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:72)
[convertOBO]    at org.obo.dataadapter.OBOFileAdapter.doOperation(OBOFileAdapter.java:273)
[convertOBO]    at org.intermine.bio.ontology.OboParser.processRelations(OboParser.java:136)
[convertOBO]    at org.intermine.bio.dataconversion.OboConverter.process(OboConverter.java:124)
[convertOBO]    at org.intermine.bio.task.OboConverterTask.execute(OboConverterTask.java:111)
```

**Comment by julie-sullivan** [comment]
See https://github.com/obophenotype/human-phenotype-ontology/issues/4408

**Comment by julie-sullivan** [comment]
For now I just deleted that line.
