### ISSUE TITLE
FlyMine - Dere fasta missing

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#2004]
```
Caused by: java.lang.RuntimeException: Failed to find any files to process for source: flybase-dere-gene-fasta looked in:
        /micklem/data/flybase/fasta/current
        at org.intermine.task.FileDirectDataLoaderTask.process(FileDirectDataLoaderTask.java:68)
        at org.intermine.bio.dataconversion.FastaLoaderTask.process(FastaLoaderTask.java:170)
        at org.intermine.task.DirectDataLoaderTask.execute(DirectDataLoaderTask.java:168)
        at org.intermine.bio.dataconversion.FastaLoaderTask.execute(FastaLoaderTask.java:215)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        ... 38 more
```

**Comment by julie-sullivan** [comment]
Duplicate of  #1985 I think.

**Comment by julie-sullivan** [comment]
```
FlyBase no longer reflects NCBI gene model annotation or genome assembly information for the following species: D. erecta, D. grimshawi, D. mojavensis, D. persimilis, D. sechellia, D. willistoni, D. yakuba
```

Should I remove these?

**Comment by julie-sullivan** [comment]
See ce60a418dd5d63058e2efacf50213e9059cded8c

**Comment by julie-sullivan** [comment]
```
FlyBase no longer reflects NCBI gene model annotation or genome assembly information 
for the following species: D. erecta, D. grimshawi, D. mojavensis, D. persimilis, D. sechellia, 
D. willistoni, D. yakuba. For the status of these gene model annotations, see the NCBI page 
Eukaryotic genomes annotated at NCBI. The FlyBase BLAST tool will continue to support 
queries against the reference genomes of these species, but not queries against annotated 
transcripts or proteins. For the current and future releases, there will be no JBrowse or 
GBrowse view of the gene model annotations for the listed species. The FlyBase archived 
release FB2017_05 includes the last NCBI annotation update that was imported into 
FlyBase for each of these species, including archived GBrowse views, BLAST capability, 
and bulk data download options. 
```

http://flybase.org/static/new-this-release
