### ISSUE TITLE
Null pointer exception when user doesn't have any lists. 

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#2030]
```
2019-03-13 10:04:12,205 [ajp-nio-8009-exec-47] ERROR (InterMineExceptionHandler,74) - java.lang.NullPointerException
        at java.util.TreeMap.getEntry(TreeMap.java:347)
        at java.util.TreeMap.get(TreeMap.java:278)
        at java.util.Collections$SynchronizedMap.get(Collections.java:2584)
        at java.util.Collections$UnmodifiableMap.get(Collections.java:1454)
        at org.intermine.api.bag.BagManager.getUserBag(BagManager.java:450)
        at org.intermine.web.struts.BagDetailsController.execute(BagDetailsController.java:98)
        at org.apache.struts.tiles.actions.TilesAction.execute(TilesAction.java:76)
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
        at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
        at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
```

**Comment by julie-sullivan** [comment]
Noticed bug when added Jaccard index.
