### ISSUE TITLE
Dull pointer if webapp does not have templates

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#2057]
```
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1014)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at org.intermine.metadata.SAXParser.parse(SAXParser.java:59)
        at org.intermine.metadata.SAXParser.parse(SAXParser.java:42)
        at org.intermine.template.xml.TemplateQueryBinding.unmarshalTemplates(TemplateQueryBinding.java:145)
        at org.intermine.api.profile.ProfileManager.wrapUserProfile(ProfileManager.java:555)
        at org.intermine.api.profile.ProfileManager.getProfile(ProfileManager.java:457)
        at org.intermine.api.profile.ProfileManager.getSuperuserProfile(ProfileManager.java:1021)
        at org.intermine.api.InterMineAPI.initUserProfileResources(InterMineAPI.java:109)
        at org.intermine.api.InterMineAPI.<init>(InterMineAPI.java:99)
        at org.intermine.web.struts.InitialiserPlugin.loadInterMineAPI(InitialiserPlugin.java:281)
        at org.intermine.web.struts.InitialiserPlugin.init(InitialiserPlugin.java:186)
        at org.apache.struts.action.ActionServlet.initModulePlugIns(ActionServlet.java:871)
        at org.apache.struts.action.ActionServlet.init(ActionServlet.java:359)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
```

**Comment by julie-sullivan** [comment]
Fixed by https://github.com/intermine/intermine-scripts/commit/01b3506ebc5af4e0ab55597b3ea9f9854efe130d
