### ISSUE TITLE
Add Util Java class to parse templates XML

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#2066]
Right now you can request the list of templates, put the intermine JAR on your class path and do this:

```
            res = TemplateQueryBinding.unmarshalTemplates(
                new InputStreamReader(connection.getResponseBodyAsStream()),
                TemplateQuery.USERPROFILE_VERSION);
```

But you get an error because getting the model is buried way deep. [ModelFactory.java](https://github.com/intermine/intermine/blob/dev/intermine/model/src/main/java/org/intermine/metadata/ModelFactory.java#L40) actually loads the `genomic_model.xml` file.

So in addition to this, we need the option of handling the unmarshaller the model.

**Comment by julie-sullivan** [comment]
This is the stacktrace

```
Exception in thread "main" java.lang.RuntimeException: org.xml.sax.SAXException: Model definition file 'genomic_model.xml' cannot be found
java.lang.IllegalArgumentException: Model definition file 'genomic_model.xml' cannot be found
        at org.intermine.template.xml.TemplateQueryBinding.unmarshalTemplates(TemplateQueryBinding.java:148)
        at org.intermine.client.services.TemplateService.getTemplates(TemplateService.java:222)
        at org.intermine.client.services.TemplateService.getTemplate(TemplateService.java:240)
        at samples.TemplateClient.main(TemplateClient.java:48)
Caused by: org.xml.sax.SAXException: Model definition file 'genomic_model.xml' cannot be found
java.lang.IllegalArgumentException: Model definition file 'genomic_model.xml' cannot be found
        at org.intermine.pathquery.PathQueryHandler.startElement(PathQueryHandler.java:126)
        at org.intermine.template.xml.TemplateQueryHandler.startElement(TemplateQueryHandler.java:91)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1359)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at org.intermine.metadata.SAXParser.parse(SAXParser.java:59)
        at org.intermine.metadata.SAXParser.parse(SAXParser.java:42)
        at org.intermine.template.xml.TemplateQueryBinding.unmarshalTemplates(TemplateQueryBinding.java:145)
        ... 3 more
Caused by: java.lang.IllegalArgumentException: Model definition file 'genomic_model.xml' cannot be found
        at org.intermine.metadata.ModelFactory.loadModel(ModelFactory.java:43)
        at org.intermine.metadata.Model.getInstanceByName(Model.java:93)
        at org.intermine.pathquery.PathQueryHandler.startElement(PathQueryHandler.java:124)
        ... 18 more
```
