### ISSUE TITLE
GO error - obsolete term

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#2073]
```
Caused by: Error: Attempted to specify obsolete value obsolete negative regulation of growth of symbiont involved in interaction with host for consider tag.
on line: 382869
charnum: -1
line: consider: GO:0044146
        at org.obo.dataadapter.DefaultOBOParser.endParse(DefaultOBOParser.java:1691)
        at org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:74)
        at org.obo.dataadapter.OBOFileAdapter.doOperation(OBOFileAdapter.java:273)
        ... 45 more
```

**Comment by julie-sullivan** [comment]
```

[Term]
id: GO:0044146
name: obsolete negative regulation of growth of symbiont involved in interaction with host
namespace: biological_process
def: "OBSOLETE. Any process that stops, prevents, or reduces the frequency, rate or extent of the increase in size or mass of an organism occurring in, on or near the exterior of its host organism." [GOC:jl, GO\
C:pamgo_curators]
comment: This term was obsoleted because it was partially redundant with other terms and its usage has been inconsistent.
synonym: "negative regulation of growth of symbiont during interaction with host" RELATED [GOC:tb]
is_obsolete: true
```

**Comment by julie-sullivan** [comment]
This is the term that is causing the error:

```
[Term]
id: GO:0075340
name: obsolete negative regulation of growth or development of symbiont during interaction with host
namespace: biological_process
def: "OBSOLETE. Any process that stops, prevents, or reduces the frequency, rate or extent of the increase in size or mass of an organism, or the progression of an organism from an initial condition to a later \
condition, occurring in, on or near the exterior of its host organism." [GOC:jl]
comment: This term was made obsolete because it contained a conjunction (or). It has been replaced with the terms 'negative regulation of development of symbiont during interaction with host ; GO:0044147' and '\
negative regulation of growth of symbiont during interaction with host ; GO:0044146'.
synonym: "negative regulation of growth or development of symbiont during interaction with host" EXACT []
is_obsolete: true
consider: GO:0044146
consider: GO:0044147
```
It's an obsolete term with another obsolete term. I don't know why `consider: GO:0044146` is an issue.

**Comment by julie-sullivan** [comment]
Fixed by https://github.com/geneontology/go-ontology/issues/17671
