### ISSUE TITLE
Complexes - duplicate protein accessions

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#2074]
The build broke because of duplicate instances of `O60583`:

```
Caused by: org.intermine.objectstore.ObjectStoreException: Duplicate objects found for pk org.intermine.model.bio.Protein.key_primaryacc: Protein [canonicalProtein=null, id=16277, isFragment=null, isUniprotCanonical=null, length=null, md5checksum=null, molecularWeight=null, name=null, organism=17154, primaryAccession="O60583", primaryIdentifier="O60583", secondaryIdentifier=null, sequence=null, symbol=null, uniprotAccession=null, uniprotName=null]
        at org.intermine.dataloader.BatchingFetcher.doPk(BatchingFetcher.java:446)
        at org.intermine.dataloader.ParallelBatchingFetcher$WorkUnit.fetch(ParallelBatchingFetcher.java:142)
        at org.intermine.dataloader.ParallelBatchingFetcher$Worker.run(ParallelBatchingFetcher.java:163)
```

Looking at the code, we can have multiple accessions because the unique key is identifier. Not all the features created are proteins as we can have small molecules.

**Comment by julie-sullivan** [comment]
```
ccnt2a-cdk9_human.xml:                    <primaryRef db="uniprotkb" dbAc="MI:0486" id="O60583-2" refType="identity" refTypeAc="MI:0356"/>
ccnt2a-cdk9_human.xml:                    <secondaryRef db="uniprotkb" dbAc="MI:0486" id="O60583-2" refType="isoform-parent" refTypeAc="MI:0243"/>
ccnt2a-cdk9_human.xml:                    <alias typeAc="MI:1316" type="complex systematic name">CCNT2[O60583-2]:CDK9</alias>
ccnt2b-cdk9_human.xml:                    <primaryRef db="uniprotkb" dbAc="MI:0486" id="O60583-1" refType="identity" refTypeAc="MI:0356"/>
ccnt2b-cdk9_human.xml:                    <alias typeAc="MI:1316" type="complex systematic name">CCNT2[O60583-1]:CDK9</alias>
```
I guess they're duplicates because of isoforms?

**Comment by julie-sullivan** [comment]
@danielabutano any idea why my commit is here twice, with a different hash?
