### ISSUE TITLE
Complexes: error on export

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#2078]
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer

  at org.intermine.webservice.server.complexes.ExportService.getComplex(ExportService.java:192)
  at org.intermine.webservice.server.complexes.ExportService.execute(ExportService.java:101)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.core.WebServiceServlet.respond(WebServiceServlet.java:73)
  at org.intermine.webservice.server.core.WebServiceServlet.doGet(WebServiceServlet.java:114)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
```

**Comment by julie-sullivan** [comment]
```
13-Aug-2019 12:57:16.368 WARNING [http-nio-8080-exec-249] psidev.psi.mi.jami.json.nary.AbstractMIJsonWriter.initialiseContext The ontology fetcher is null so all the features will be listed as otherFeatures
13-Aug-2019 12:57:16.370 WARNING [http-nio-8080-exec-249] psidev.psi.mi.jami.json.nary.AbstractMIJsonWriter.write Ignore interaction as it does not contain any participants : Complex: 10021614, MI:0314 (complex)
13-Aug-2019 12:58:06.754 WARNING [http-nio-8080-exec-271] psidev.psi.mi.jami.json.nary.AbstractMIJsonWriter.initialiseContext The ontology fetcher is null so all the features will be listed as otherFeatures
13-Aug-2019 12:58:06.755 WARNING [http-nio-8080-exec-271] psidev.psi.mi.jami.json.nary.AbstractMIJsonWriter.write Ignore interaction as it does not contain any participants : Complex: 10043332, MI:0314 (complex
```

**Comment by julie-sullivan** [comment]
https://yeastmine.yeastgenome.org/yeastmine/service/complexes/export/10047180

That is exporting an empty file.
