### ISSUE TITLE
Humanmine and Flymine gives invalid response to /service/web-properties

### ISSUE THREAD

**Issue by uosl** [intermine/intermine#2190]
`curl https://www.humanmine.org/humanmine/service/web-properties` should return JSON, which it does for Flymine, but Humanmine returns a 500 error with the body:

```
{
  "web-properties": null,
  "executionTime": "2020.01.23 15:30::11",
  "wasSuccessful": false,
  "error": "Service failed. Please contact support.",
  "statusCode": 500
}
```

Update: This now applies to Flymine as well, as of yesterday (after the release?).

**Comment by danielabutano** [comment]
From tomcat

> [2020-02-20 14:34:01] [info] java.lang.NullPointerException
[2020-02-20 14:34:01] [info] 2020-02-20 14:34:01,343 [http-nio-8080-exec-2492] WARN  (CommonsLoggingOutput,59) - --Erroring: batchId[0] message[java.lang.NullPointerException]
[2020-02-20 14:34:01] [info] ]172353752 [http-nio-8080-exec-2492] WARN org.directwebremoting.dwrp.BaseCallMarshaller  - --Erroring: batchId[0] message[java.lang.NullPointerException]
[2020-02-20 14:34:06] [info] 2020-02-20 14:34:06,933 [http-nio-8080-exec-2540] ERROR (WebService,622) - Service failed by internal error. Request parameters:
[2020-02-20 14:34:06] [info] java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
[2020-02-20 14:34:06] [info]   at org.intermine.webservice.server.webproperties.WebPropertiesService.setProperty(WebPropertiesService.java:110)
[2020-02-20 14:34:06] [info]   at org.intermine.webservice.server.webproperties.WebPropertiesService.appendProperties(WebPropertiesService.java:82)
[2020-02-20 14:34:06] [info]   at org.intermine.webservice.server.webproperties.WebPropertiesService.execute(WebPropertiesService.java:46)
[2020-02-20 14:34:06] [info]   at org.intermine.webservice.server.WebService.service(WebService.java:350)
[2020-02-20 14:34:06] [info]   at org.intermine.webservice.server.webproperties.WebPropertiesServlet.runService(WebPropertiesServlet.java:50)
[2020-02-20 14:34:06] [info]   at org.intermine.webservice.server.webproperties.WebPropertiesServlet.doGet(WebPropertiesServlet.java:36)
[2020-02-20 14:34:06] [info]   at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
[2020-02-20 14:34:06] [info]   at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
[2020-02-20 14:34:06] [info]  ...
[2020-02-20 14:34:06] [info] ]172359342 [http-nio-8080-exec-2540] ERROR org.intermine.webservice.server.WebService  - Service failed by internal error. Request parameters:
[2020-02-20 14:34:06] [info] java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
[2020-02-20 14:34:06] [info]   at org.intermine.webservice.server.webproperties.WebPropertiesService.setProperty(WebPropertiesService.java:110)
[2020-02-20 14:34:06] [info]   at org.intermine.webservice.server.webproperties.WebPropertiesService.appendProperties(WebPropertiesService.java:82)
[2020-02-20 14:34:06] [info]   at org.intermine.webservice.server.webproperties.WebPropertiesService.execute(WebPropertiesService.java:46)
[2020-02-20 14:34:06] [info]   at org.intermine.webservice.server.WebService.service(WebService.java:350)
[2020-02-20 14:34:06] [info]   at org.intermine.webservice.server.webproperties.WebPropertiesServlet.runService(WebPropertiesServlet.java:50)
[2020-02-20 14:34:06] [info]   at org.intermine.webservice.server.webproperties.WebPropertiesServlet.doGet(WebPropertiesServlet.java:36)
[2020-02-20 14:34:06] [info]   at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
[2020-02-20 14:34:06] [info]   at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
[2020-02-20 14:34:06] [info]  ...
[2020-02-20 14:34:14] [info] 2020-02-20 14:34:14,554 [http-nio-8080-exec-2541] WARN  (SqlGenerator,283) - Error while registering offset for query SELECT DISTINCT a1_.class AS a2_ FROM org.intermine.model.bio.SequenceFeature AS a1_ WHERE ?.overlappingFeatures CONTAINS a1_ 1: Gene [briefDescription=null, chromosome=1000

**Comment by danielabutano** [comment]
same #1927 and #1878.
This time has been fixed by code. the issue was configurations as 
`genomicRegionSearch.liftOver = false       
genomicRegionSearch.liftOver.url =`
OR
`bag.example.identifiers.protein=Q8T3M3,FBpp0081318,FTZ_DROME
bag.example.identifiers=CG9151, FBgn0000099, CG3629, TfIIB, Mad, CG1775, CG2262
`

**Comment by danielabutano** [comment]
When we redeloy flymine with this fix, we can re-added the properties bag.example.identifiers.protein commented as temporary fix!
