### ISSUE TITLE
Misleading message if property src.data.dir it's not properly configured in the project.xml file

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine#2235]
If in a obo source, we configure
` <property name="src.data.dir" value="/home/daniela/Projects/data/obo/"/>`
instead of 
` <property name="src.data.dir" location="/home/daniela/Projects/data/obo/"/>`
the console prints out the message 
> Don't know how to deal with file null
thrown [here](https://github.com/intermine/intermine/blob/dev/bio/core/src/main/java/org/intermine/bio/task/OboConverterTask.java#L110)
The OboConverteTask is set with a file having as a value the String "null".
Similar issue to

**Comment by motenko** [comment]
We think the problem is because somewhere the NULL character is converted to a string = "null" and then the file name is not NULL, but the string = "null".

This problem also happens when trying to load type="uniprot" using: 
<source name="uniprot" type="uniprot" >
 ... <property name="src.data.dir" value="&mm_data;/uniprot/latest/"/>

With an error: 
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: : dataDir is not a directory:null
        at org.intermine.task.DirectoryConverterTask.execute(DirectoryConverterTask.java:63)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)

**Comment by motenko** [comment]
Using a configuration of an obo source: 
 property name="src.data.file" value="&mm_data;/do/latest/DiseaseOntology.obo"

Reported error message:
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: : java.lang.IllegalArgumentException: Don't know how to deal with file null
        at org.intermine.bio.task.OboConverterTask.execute(OboConverterTask.java:115)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.intermine.plugin.integrate.IntegrateUtils$_closure9.doCall(IntegrateUtils.groovy:234)
