### ISSUE TITLE
intermine and Python 3.10

### ISSUE THREAD

**Issue by jburel** [intermine/intermine#2453]
Using the Python API with Python 3.10 leads to the following error
```
from intermine.webservice import Service
Traceback (most recent call last):
  File "/Users/jmarie/opt/anaconda3/envs/intermine-test/lib/python3.10/site-packages/intermine/webservice.py", line 9, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jmarie/opt/anaconda3/envs/intermine-test/lib/python3.10/site-packages/intermine/webservice.py", line 16, in <module>
    from collections import MutableMapping as DictMixin
ImportError: cannot import name 'MutableMapping' from 'collections' (/Users/jmarie/opt/anaconda3/envs/intermine-test/lib/python3.10/collections/__init__.py)
```
No problem with Python version <3.10

**Comment by jburel** [comment]
Replaced by https://github.com/intermine/intermine-ws-python/issues/96
