### ISSUE TITLE
query too long message (#155 again?)

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/intermine#645]
it seems that the query too long service error is not propagated to the webapp, where the message is 'Could not load the data-table'
found by aip, jira case MINE-266

https://jira.araport.org/browse/MINE-266

> 07/05/2014,12:35:25 INFO  org.directwebremoting.impl.DefaultRemoter     - Exec: AjaxServices.getFriendlyMineLinks()
> 07/05/2014,12:38:49 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
> token: 61O4n5LdP7H8b1G2p6ud
> query: <query model="genomic" view="Gene.goAnnotation.dataSets.name Gene.goAnnotation.dataSets.url Gene.exons.dataSets.name Gene.exons.dataSets.url Gene.probes.expressions.signal Gene.probes.expressions.averageSignal Gene.probes.expressions.averageControl Gene.probes.expressions.averageRatio Gene.probes.expressions.probe.gene.primaryIdentifier Gene.probes.expressions.probe.name Gene.probes.expressions.sample.name" sortOrder="Gene.goAnnotation.dataSets.name ASC" ></query>
> format: jsontable
> org.intermine.webservice.server.exceptions.ServiceException: Query would take too long to run
>   at org.intermine.webservice.server.query.result.QueryResultService.runResults(QueryResultService.java:338)
>   at org.intermine.webservice.server.query.result.QueryResultService.runPathQuery(QueryResultService.java:303)
>   at org.intermine.webservice.server.query.result.QueryResultService.execute(QueryResultService.java:109)
>   at org.intermine.webservice.server.WebService.service(WebService.java:349)
>   at org.intermine.webservice.server.query.result.QueryResultServlet.runService(QueryResultServlet.java:66)
>   at org.intermine.webservice.server.query.result.QueryResultServlet.doPost(QueryResultServlet.java:48)

**Comment by sergiocontrino** [comment]
after upgrade to 1.6, it seems that now this is failing silently (the page remains with the 'loading table' message. the runtime error is now 
java.lang.RuntimeException: ObjectStore error has occurred in size()

**Comment by sergiocontrino** [comment]
https://github.com/intermine/intermine/blob/3328168aa750f1175d9e7c6bb2a516455cfc9bd1/intermine/objectstore/main/src/org/intermine/objectstore/query/ResultsBatches.java#L236

**Comment by sergiocontrino** [comment]
tested on beta flymine with demanding query: it returns now a 504 server error, that seems the right thing to do. we could improve error message.
