### ISSUE TITLE
FlyBase: Mutagens now annotated using disease ontology

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#707]
We set mutagens by:
1. getting all annotations of alleles from the `feature_cvterm` table (previously only included Misc CV terms
2. seeing if the cv term has "origin of mutation" as a parent
3. if so, creates a mutagen for allele with name of term as description.

FlyBase have started annotating alleles with disease ontology in addition to the misc cv but here we are only looking in the misc cv:

https://github.com/intermine/intermine/blob/dev/bio/sources/chado-db/main/src/org/intermine/bio/dataconversion/FlyBaseProcessor.java#L1243

We are ignoring any annotations by other ontologies.
1. should we also process DO terms?
2. if so, which ones?

**Comment by julie-sullivan** [comment]
@rachellyne Can I close this? Or is this something we want to do.

**Comment by julie-sullivan** [comment]
@rachellyne Is this the file you were referring to:

http://flybase.org/wiki/FlyBase:Downloads_Overview#Human_disease

Should I load that? We already get those data from OMIM though, right?

**Comment by julie-sullivan** [comment]
I checked the FlyBase chado database and this is where we are getting allele annotations from:

```
FB2017_01=# SELECT DISTINCT db.* FROM feature, feature_cvterm, cvterm, dbxref d, db WHERE feature.feature_id = feature_cvterm.feature_id AND feature.feature_id IN (select feature_id from feature where uniquename LIKE 'FBal%') AND feature_cvterm.cvterm_id = cvterm.cvterm_id and cvterm.dbxref_id != 1916906 and cvterm.dbxref_id = d.dbxref_id and d.db_id = db.db_id;
 db_id |       name       | contact_id | description | urlprefix | url 
-------+------------------+------------+-------------+-----------+-----
    80 | FBcv             |            |             |           | 
     2 | SO               |          4 |             |           | 
   300 | DOID             |            |             |           | 
    74 | FBbt             |            |             |           | 
   125 | FlyBase_internal |            |             |           | 
     3 | GO               |          5 |             |           | 
(6 rows)
```

So no disease ontology. I was mistaken.

**Comment by julie-sullivan** [comment]
DOID is the disease ontology, and they've prepended zeros to the identifier.

**Comment by julie-sullivan** [comment]
Let's load from the data file instead.

**Comment by julie-sullivan** [comment]
Model exactly like go annotation.

**Comment by julie-sullivan** [comment]
allele_phenotypic_data_fb_2017_02.tsv.gz

**Comment by julie-sullivan** [comment]
We need to load Disease ontology as well.

**Comment by julie-sullivan** [comment]
```
Caused by: java.lang.IllegalArgumentException: Conflicting values for field Allele.sequenceOntologyTerm between chado-db-flybase-dmel (value "SOTerm [description=null, id=1000002, identifier=null, name="gene", namespace=null, obsolete=null, ontology=1000000]" in database with ID 3090708) and flybase-alleles (value "SOTerm [description=null, id=36000002, identifier=null, name="allele", namespace=null, obsolete=null, ontology=1000000]" being stored). This field needs configuring in the genomic_priorities.properties file
        at org.intermine.dataloader.SourcePriorityComparator
```

Some alleles are genes?

**Comment by rachellyne** [comment]
Alleles are genes, but there should be a definite distinction between the "gene" and the "allele" of a gene.
Can you give me the gene id?

**Comment by julie-sullivan** [comment]
No, the message didn't include it. oops. I just restarted the build. When it's done we'll make sure we've made the correct types.

**Comment by julie-sullivan** [comment]
```
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.IllegalArgumentException: Conflicting values for field Allele.symbol between chado-db-flybase-dmel (value "DnaJ-1[Scer\UAS.cKa]" in database with ID 1879524) and flybase-alleles (value "DnaJ-1[ScerUAS.cKa]" being stored). This field needs configuring in the genomic_priorities.properties file
        at org.intermine.dataloader.SourcePriorityComparator.compare(SourcePriorityComparator.java:269)
        at org.intermine.dataloader.SourcePriorityComparator.compare(SourcePriorityComparator.java:34)
        at java.util.TreeMap.put(TreeMap.java:545)
        at java.util.TreeSet.add(TreeSet.java:255)
        at org.intermine.dataloader.IntegrationWriterDataTrack
```

**Comment by julie-sullivan** [comment]
Looks correct now in beta flymine.
