### ISSUE TITLE
Precompute fails when too many joins

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#725]
Error whilst precomputing:

> at org.intermine.web.task.PrecomputeTemplatesTask.precomputeTemplates(PrecomputeTemplatesTask.java:218)
> at org.intermine.web.task.PrecomputeTemplatesTask.execute(PrecomputeTemplatesTask.java:150)
>  ... 16 more
> Caused by: org.intermine.objectstore.ObjectStoreException: Query SQL cannot be parsed, so cannot be precomputed

SQL can't be parsed:

> Caused by: line 1:502: unexpected token: AND
>         at org.intermine.sql.query.SqlParser.select_command(SqlParser.java:346)
>         at org.intermine.sql.query.SqlParser.sql_statement(SqlParser.java:166)
>         at org.intermine.sql.query.SqlParser.sql(SqlParser.java:121)
>         at org.intermine.sql.query.SqlParser.start_rule(SqlParser.java:73)
>         at org.intermine.sql.query.Query.<init>(Query.java:147)
>         ... 27 more

ANTLR parser should be upgraded. 

Error message should be fixed too:

> /data/code/flymine/intermine/imbuild/application.xml:206: Exception creating objectstore/profile manager
>  at org.intermine.web.task.PrecomputeTemplatesTask.execute(PrecomputeTemplatesTask.java:152)

The profile manager isn't the problem

**Comment by julie-sullivan** [comment]
Tell @kkarra
