### ISSUE TITLE
Query with outer join does not validate

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#786]
@ZFIN created a template but the template could not be run and prevented the rendering of the my mine page.
1. Fix the error with outer joins and constraints
2. Catch the exception gracefully so at least the users can get to their other templates.

> 2014-10-28 11:52:24 ERROR org.intermine.web.struts.InterMineExceptionHandler     - java.lang.RuntimeException: Template query org.intermine.api.template.ApiTemplate{ name: Wild_Type_Exp_Short_Return, title: Wild-type Expression (with four result columns), comment: , description: Default query returns expression in wild-type backgrounds in standard or control environments. To search for expression of a specific gene, type the symbol (or part of the symbol plus wildcards, e.g. _fgf8_) in the "Gene > Symbol" box. To look for expression in groups of genes, make a list of the genes and use the checkbox to constrain the query to your custom list.  To find expression in a particualr  anatomical structure, enter it in the "ZFA Term > Name" box. To find subcellular expression, use the "Ontology Term > Name" box. , PathQuery( view: [Expression.gene.symbol, Expression.startStage.name, Expression.endStage.name, Expression.anatomy.name], orderBy: [Expression.gene.symbol ASC], constraints: {Expression.genotype.isWildType = true=B, Expression.expressionFound = true=C, Expression.gene.symbol = _=D, Expression.anatomy.name = *=E, Expression.environment.primaryIdentifier = ZDB-EXP-041102-1=G, Expression.environment.primaryIdentifier = ZDB-EXP-070511-5=A, Expression.subterm.name = *=F}, logic: B and C and D and E and (G or A) and F, outerJoinStatus: {Expression.subterm=OUTER}, descriptions: {}, description: Default query returns expression in wild-type backgrounds in standard or control environments. To search for expression of a specific gene, type the symbol (or part of the symbol plus wildcards, e.g. *fgf8_) in the "Gene > Symbol" box. To look for expression in groups of genes, make a list of the genes and use the checkbox to constrain the query to your custom list.  To find expression in a particualr  anatomical structure, enter it in the "ZFA Term > Name" box. To find subcellular expression, use the "Ontology Term > Name" box. )} does not validate: [Outer join status path Expression.subterm is not relevant to the query]
> at org.intermine.api.template.TemplatePrecomputeHelper.getPrecomputeQuery(TemplatePrecomputeHelper.java:85)
> at org.intermine.api.template.TemplatePrecomputeHelper.getPrecomputeQuery(TemplatePrecomputeHelper.java:64)
> at org.intermine.web.struts.MyMineController.getPrecomputedSummarisedInfo(MyMineController.java:206)
> at org.intermine.web.struts.TemplatesController.execute(TemplatesController.java:47)

**Comment by julie-sullivan** [comment]
Fixed by ac81426bdcebf9a4a8b86d9d51e219cb5c478ea4
