### ISSUE TITLE
BioJava - update library

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#83]
We are on a very old (7 years?) version of the library.  Specifically, I think they fixed a memory leak.

**Comment by julie-sullivan** [comment]
@rachellyne I've removed PDB from FlyMine temporarily until we can update the BioJava library.

This is the error I get:

```
[integrate] WARNING: unknown group name MSE
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
Dumping heap to /tmp/java_pid19540.hprof ...
Heap dump file created [3684876297 bytes in 15.089 secs]

BUILD FAILED
/local-homes/julie/git/intermine/imbuild/integrate.xml:54: The following error occurred while executing this line:
/local-homes/julie/git/intermine/imbuild/source.xml:162: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
	at java.lang.StringBuffer.append(StringBuffer.java:237)
	at org.biojava.bio.structure.PDBHeader.printTitle(PDBHeader.java:249)
	at org.biojava.bio.structure.PDBHeader.toPDB(PDBHeader.java:105)
	at org.biojava.bio.structure.io.FileConvert.toPDB(FileConvert.java:196)
	at org.biojava.bio.structure.StructureImpl.toPDB(StructureImpl.java:559)
	at org.intermine.bio.dataconversion.PdbConverter.processPDBFile(PdbConverter.java:162)
	at org.intermine.bio.dataconversion.PdbConverter.process(PdbConverter.java:104)
	at org.intermine.task.DirectoryConverterTask.execute(DirectoryConverterTask.java:104)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl
```

This happens in Java 6 (open-jdk only), 7 and 8. FlyMine is using sun's Java 6 where this works.

I suppose BioJava is creating an array that is too big.

**Comment by julie-sullivan** [comment]
@sergiocontrino @rachellyne This is still a problem.

**Comment by julie-sullivan** [comment]
PDB won't be included in this next release of FlyMine.
