### ISSUE TITLE
Some tests fail occasionally

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#845]
This only happens every fifth time you run the test via eclipse but happens when you run the test via intermine/all.

We should replace custommonkey with a more up-to-date library.

```java
junit.framework.AssertionFailedError: org.custommonkey.xmlunit.Diff
[different] Expected number of child nodes '5' but was '2' - comparing <collection...> at /item[1]/collection[1] to <collection...> at /item[1]/collection[1]

	at junit.framework.Assert.fail(Assert.java:47)
	at org.custommonkey.xmlunit.XMLAssert.assertXMLEqual(XMLAssert.java:111)
	at org.custommonkey.xmlunit.XMLAssert.assertXMLEqual(XMLAssert.java:172)
	at org.custommonkey.xmlunit.XMLTestCase.assertXMLEqual(XMLTestCase.java:244)
	at org.intermine.xml.full.FullRendererTest.testRenderObjectDynamic(FullRendererTest.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

```

**Comment by julie-sullivan** [comment]
All tests pass via the command line and eclipse.
