### ISSUE TITLE
Human InterMine failed - huge-gwas source file has random tab on one line

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#888]
```java
BUILD FAILED
code/intermine/imbuild/source.xml:330: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "Anttila V"
        at org.intermine.dataconversion.ItemToObjectTranslator.translateFromDbObject(ItemToObjectTranslator.java:418)
        at org.intermine.objectstore.translating.ObjectStoreTranslatingImpl.execute(ObjectStoreTranslatingImpl.java:157)
        at org.intermine.objectstore.fastcollections.ObjectStoreFastCollectionsForTranslatorImpl.execute(ObjectStoreFastCollectionsForTranslatorImpl.java:193)
        at org.intermine.dataloader.BatchingFetcher$NoseyObjectStore.execute(BatchingFetcher.java:558)
        at org.intermine.objectstore.query.ResultsBatches.fetchBatchFromObjectStore(ResultsBatches.java:192)
        at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:241)
        at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:236)
        at org.intermine.objectstore.query.PrefetchManager.doRequest(PrefetchManager.java:146)
        at org.intermine.objectstore.query.ResultsBatches.getBatch(ResultsBatches.java:164)
        at org.intermine.objectstore.query.ResultsBatches.getRowsFromBatch(ResultsBatches.java:139)
        at org.intermine.objectstore.query.Results.range(Results.java:197)
        at org.intermine.objectstore.query.SingletonResults.range(SingletonResults.java:65)
        at org.intermine.objectstore.query.Results.get(Results.java:226)
        at org.intermine.objectstore.query.Results$Iter.hasNext(Results.java:378)
        at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:135)
        at org.intermine.dataloader.ObjectStoreDataLoader.process(ObjectStoreDataLoader.java:60)
        at org.intermine.dataloader.ObjectStoreDataLoaderTask.execute(ObjectStoreDataLoaderTask.java:128)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
```

**Comment by julie-sullivan** [comment]
@rachellyne Here is the new file:

```
rs4345220(NR	4p13)	Intergenic	NR	4p13	Migraine with aura	Anttila V	Nat Genet	2013	23793025	5,118 European ancestry cases, 74,239 European ancestry controls/NR	rs4345220-?[0.56]	1.15[[1.09-1.2] ]	2x10-6	Affmetrix & Illumina [~2.3 million] (Imputed)
```
Here is a typical line:
```
rs17470570(10q24.2)	Intergenic	10q24.2	Migraine without aura	Anttila V	Nat Genet	2013	23793025	7,107 European ancestry cases, 69,427 European ancestry controls/NR	rs17470570-G[0.08]	1.2[[1.11-1.30] ]	3x10-6	Affmetrix & Illumina [~2.3 million] (Imputed)
```
I don't know if you can see, but I think "NR	4p13" might contain a tab. Oh no! 

1. can you see if the updated file has this line removed?
2. I've removed that line from the data file and put it in a new directory `2014-10-14-edited`

**Comment by rachellyne** [comment]
It does.  I've downloaded again but it's still a tab.  It may be deliberate but I'm not sure what NR means.

**Comment by julie-sullivan** [comment]
@rachellyne Can you ask them to fix it? You can't have a tab delimited file with tabs in random spots, that's illegal!

I put that I removed that line in the README. Can we collectively try to remember to remove this line for next time? Should I start a data source spreadsheet?

**Comment by rachellyne** [comment]
yes, I'll email them.

**Comment by julie-sullivan** [comment]
@rachellyne it's fixed in the latest file, right? Or have we been using the same file still?

**Comment by rachellyne** [comment]
They haven't updated since August 2014, so keep using the file you fixed.
