### ISSUE TITLE
keyword search task aborts silently if it encounters an error

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#896]
If an exception is thrown during indexing, an error message is logged, and then the index is closed. It must fail loudly.

**Comment by julie-sullivan** [comment]
Here is an example of a silent failure:

```
2015-01-05 11:42:00 INFO  org.intermine.api.lucene.InterMineObjectFetcher     - decomposedClassesCache: No entry for class org.intermine.model.bio.AnatomyTerm$$EnhancerByCGLIB$$3aa88c3e, adding...
2015-01-05 11:42:00 WARN  org.intermine.api.lucene.InterMineObjectFetcher     - 
java.lang.IllegalArgumentException: No simple class for AnatomyTerm,SOTerm
        at org.intermine.util.DynamicUtil.getSimpleClass(DynamicUtil.java:351)
        at org.intermine.util.DynamicUtil.getSimpleClass(DynamicUtil.java:366)
        at org.intermine.api.lucene.InterMineObjectFetcher.getAttributeMapForObject(InterMineObjectFetcher.java:443)
        at org.intermine.api.lucene.InterMineObjectFetcher.addObjectToDocument(InterMineObjectFetcher.java:427)
        at org.intermine.api.lucene.InterMineObjectFetcher.createDocument(InterMineObjectFetcher.java:409)
        at org.intermine.api.lucene.InterMineObjectFetcher.handleObject(InterMineObjectFetcher.java:208)
        at org.intermine.api.lucene.InterMineObjectFetcher.iterateOverObjects(InterMineObjectFetcher.java:378)
        at org.intermine.api.lucene.InterMineObjectFetcher.run(InterMineObjectFetcher.java:168)
2015-01-05 11:42:00 INFO  org.intermine.api.lucene.KeywordSearch     - docs indexed=1; thread state=TERMINATED; docs/ms=2.5336982E-5; memory=1651169k/9102272k; time=39468ms
2015-01-05 11:42:00 INFO  org.intermine.api.lucene.KeywordSearch     - Indexing of 2 documents finished in 00:39.488 minutes
2015-01-05 11:42:00 INFO  org.intermine.api.lucene.KeywordSearch     - Deleting index directory: /data/tmp/search_index7310947914063159685
2015-01-05 11:42:00 WARN  org.intermine.api.lucene.KeywordSearch     - Deleted index directory!
2015-01-05 11:42:00 INFO     org.intermine.sql.writebatch.Batch     - Batch flusher has spent 0 ms waiting for the database (duty cycle 0%) (current duty cycle 0%)
2015-01-05 11:42:00 INFO  org.intermine.objectstore.intermine.ObjectStoreInterMineImpl     - Shutting down open ObjectStoreInterMineImpl with sequence = {InterMineObject=-128288762} and Database jdbc:postgresql://localhost/flymine-build
2015-01-05 11:42:00 INFO  org.intermine.objectstore.intermine.ObjectStoreInterMineImpl     - Close called on ObjectStoreInterMineImpl with sequence = {InterMineObject=-128288762}, time spent: Bag Tables: 2, SQL Gen: 17, SQL Optimise: 41, Estimate: 0, Execute: 16, Results Convert: 216
2015-01-05 11:42:00 INFO  org.intermine.objectstore.intermine.ObjectStoreInterMineImpl     - Temporary tables to drop: []
2015-01-05 11:42:00 INFO     org.intermine.sql.writebatch.Batch     - Batch flusher has spent 0 ms waiting for the database (dut
```

**Comment by alexkalderimis** [comment]
Yes - that was precise what I was trying to deal with: the Lucene's thorough failure to handle dynamic objects.
