### ISSUE TITLE
Better error message for running out of connections

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#912]
This error message is caused by having too many connections. There is no way to tell that's the problem from this stacktrace. 

```
/projects/intermine/imbuild/integrate.xml:54: The following error occurred while executing this line:
/projects/intermine/imbuild/source.xml:330: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.intermine.objectstore.ObjectStoreFactory.getObjectStore(ObjectStoreFactory.java:61)
        at org.intermine.dataloader.ObjectStoreDataLoaderTask.execute(ObjectStoreDataLoaderTask.java:128)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.intermine.task.Integrate.performAction(Integrate.java:223)
        at org.intermine.task.Integrate.performAction(Integrate.java:136)
        at org.intermine.task.Integrate.execute(Integrate.java:127)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.IllegalArgumentException: ObjectStore 'os.common-translated-std' not found in properties
        at org.intermine.objectstore.fastcollections.ObjectStoreFastCollectionsForTranslatorImpl.getInstance(ObjectStoreFastCollectionsForTranslatorImpl.java:97)
        ... 37 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.intermine.objectstore.ObjectStoreFactory.getObjectStore(ObjectStoreFactory.java:61)
        at org.intermine.objectstore.fastcollections.ObjectStoreFastCollectionsForTranslatorImpl.getInstance(ObjectStoreFastCollectionsForTranslatorImpl.java:90)
        ... 37 more
Caused by: java.lang.IllegalArgumentException: Unable to get sub-ObjectStore for Translating ObjectStore (check properties file)
        at org.intermine.objectstore.translating.ObjectStoreTranslatingImpl.getInstance(ObjectStoreTranslatingImpl.java:87)
        ... 43 more 
```

**Comment by julie-sullivan** [comment]
Fixed by #1029
