### ISSUE TITLE
Interaction region not a Bioentity causing problems in located features collection

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine#962]
Interaction region has a gene reference and a location reference. I think this is causing confusion.

If you look at the report page for ENSG00000097007 you'll see the located features collection does not load properly. I believe this is because it contains an interaction region object. I don't know how that happened.

We should make interaction region a bioentity if it's going to use the location object.

```
12/03/15,14:31:53 ERROR org.intermine.webservice.server.WebService     - Service failed by internal error. Request parameters: 
format: jsontable
query: <query model="genomic" view="Gene.locatedFeatures.feature.primaryIdentifier Gene.locatedFeatures.feature.symbol Gene.locatedFeatures.locatedOn.primaryIdentifier Gene.locatedFeatures.start Gene.locatedFeatures.end Gene.locatedFeatu
res.strand" ><join path="Gene.locatedFeatures.feature" style="OUTER"/><join path="Gene.locatedFeatures.locatedOn" style="OUTER"/><constraint path="Gene.id" op="=" value="396001645" code="A" /></query>
token: d1J4ccV0qdwaw0Qdhec1
java.lang.RuntimeException: java.lang.IllegalAccessException: Couldn't get field "[interface org.intermine.model.bio.InteractionRegion].symbol" (available fields are [endStatus, gene, id, interaction, location, ontologyTerm, startStatus]
)

  at org.intermine.api.results.ResultElement.<init>(ResultElement.java:52)
  at org.intermine.api.results.ExportResultsIterator.expandCollections(ExportResultsIterator.java:300)
  at org.intermine.api.results.ExportResultsIterator.decodeRow(ExportResultsIterator.java:283)
  at org.intermine.api.results.ExportResultsIterator.hasNext(ExportResultsIterator.java:113)
  at org.intermine.api.query.ResultIterator.hasNext(PathQueryExecutor.java:286)
  at org.intermine.webservice.server.query.result.QueryResultService.runResults(QueryResultService.java:345)
  at org.intermine.webservice.server.query.result.QueryResultService.runPathQuery(QueryResultService.java:302)
  at org.intermine.webservice.server.query.result.QueryResultService.execute(QueryResultService.java:106)
  at org.intermine.webservice.server.WebService.service(WebService.java:350)
  at org.intermine.webservice.server.query.result.QueryResultServlet.runService(QueryResultServlet.java:61)
  at org.intermine.webservice.server.query.result.QueryResultServlet.doPost(QueryResultServlet.java:43)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
 ...
```

**Comment by sergiocontrino** [comment]
i think this is fixed by #1132
