### ISSUE TITLE
Intermittent error creating an inline results table.

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine#972]
```

18/08/14,10:28:15 INFO org.intermine.web.logic.results.InlineResultsTable - TIME - InlineResultsTable constructor took: 0ms.
18/08/14,10:28:15 ERROR org.apache.struts.tiles.taglib.InsertTag - ServletException in '/reportCollectionTable.jsp': null
org.apache.jasper.JasperException: java.util.ConcurrentModificationException 

Caused by: java.util.ConcurrentModificationException
at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:761)
at java.util.LinkedList$ListItr.next(LinkedList.java:696)
at org.apache.taglibs.standard.tag.common.core.ForEachSupport$SimpleForEachIterator.next(ForEachSupport.java:108)
at org.apache.taglibs.standard.tag.common.core.ForEachSupport.next(ForEachSupport.java:130)
at javax.servlet.jsp.jstl.core.LoopTagSupport.doAfterBody(LoopTagSupport.java:266) 
```

**Comment by julie-sullivan** [comment]
@kkarra does this still happen? On which report pages?

**Comment by julie-sullivan** [comment]
not enough info
